### ISSUE TITLE
Add delete document functionality

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#10]

**Comment by danicatalan** [comment]
I uploaded the video with an approach to solve this functionality: https://github.com/huridocs/uwazi-assets/tree/master/10_float_button

We need these buttons inside the floating menu because we need to manipulate the document from the viewer, and we don't have any card inside it.

I just deleted the "View document" option because:

- We have this action very clear right now inside the cards.
- We don't need this actions inside the viewer.

With these changes, we have the same floating button on _library - uploads - viewer_. Works like a charm!

I love the new approach that we talked today, but we can't remove them from the floating button for UI consistency. I bet for getting this approach right now, design the card UI upgrade with new actions and the other changes, and maintain both ways of edit a document - from floating btn and card actions.

@txau what do you think?

**Comment by txau** [comment]
So no action bar for every document for now? ok. looks good to me.

@daneryl this is related to #73 , watch out.

**Comment by konzz** [comment]
The delete functionality in the backend exists, it was implemented for uploads, where they can't have references, but if we are adding this to all documents, we must also delete the references pointing to and from the document. Also delete the uploaded file.

**Comment by konzz** [comment]
Solved in #216
