### ISSUE TITLE
Priority sorting on Uploads

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1033]
When uploading a document on Uploads, priority sorting is affecting the list. This means that if priority sorting is set as "Date presented to the court" and you upload a new document, this document doesn't have the property so it goes to the end of the list.

Should we use "Date added" always as default on Uploads?

**Comment by HSips** [comment]
Hey @danicatalan had just logged in to ask this..
My opinion is yes please, keep date added as the sorting format in uploads. I know we have way more uploads than we should on the OAU/AU database.. what was helping us to work is the sorting by date, which also then sorted out documents by alphabetical order, which was great.
A return to this is greatly appreciated.
Also, even more importantly, I looove the new sorting on pubic library. Like I had mentioned to you, so far, I think only Pretoria will need the 'date added' as sorting format in library. The rest of us need 'date published/issued'. Having it is great. Thanks!

**Comment by danicatalan** [comment]
Thanks for your feedback @HSips :)

**Comment by RafaPolit** [comment]
@danicatalan This was more or less talked about.  The thing is: you can always manually select the Date added (recently), and you are set.  The behavior you wanted is there after a single click, and it will keep as the selected preference as long as it is valid.  User selection overrides any priority sorting.

Perhaps we need to discuss this further with @txau  and @kjantin

**Comment by HSips** [comment]
thanks for this @RafaPolit The manual select work fine. Sorry had not noticed it earlier.

**Comment by kjantin** [comment]
Ideas for how to improve this:
- Store user preference for sorting in the uploads section (in user settings or a cookie)
- Making it clearer to the user how to use those sorting options in the top of the uploads section
@danicatalan I think we need to talk to some users to find out the best approach

**Comment by HSips** [comment]
Thanks @kjantin for this. 
1. Yes, I think storing user preference would be a tad helpful as well. 
2. On making it clearer, I had suggested on another issue - can't remember when - that it is not always clear that the sorting formats can be toggled down. Could be my personal impression. Maybe a little icon (+/-) may indicate to the user, especially in the library where we expect all sorts of users to interact with any given database, that that sorting list is a drop down menu.

I guess it is also fair to say that we are facing that particular problem in uploads because we have way too many uploads. So while many pilots may not notice it acutely in uploads, it may be far more helpful in the public library.

**Comment by danicatalan** [comment]
@kjantin @HSips we have an issue opened to fix the 2nd point (https://github.com/huridocs/uwazi/issues/954). Moving that issue in our current sprint.

**Comment by HSips** [comment]
@danicatalan cool!

**Comment by kjantin** [comment]
Thanks, @danicatalan! I'm going to close this issue.
