### ISSUE TITLE
OAU/AU instance - language versions and viewing old files

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1034]
Hey guys, had asked this as part of an older issue but closed it to restart here. I hope this is ok. 2 points really:
1. I am unable to view the documents I uploaded in October 2016. Example: https://humphrey.uwazi.io/en/document/716mlut5sw4jkyb9
I have tried to create 2 temporary document types called 'AU PRC evacuate' and AU Assembly evacuate' to move them into public library and hopefully view them from there but still. It keeps loading for hours. 
~~2. I would like to kindly ask for the OAU/AU instance to have 4 language versions: English; French; Portuguese; Arabic.~~ <-- has been addressed below
Kindly advice.

**Comment by kjantin** [comment]
> I would like to kindly ask for the OAU/AU instance to have 4 language versions: English; French; Portuguese; Arabic.

Hi @HSips, 
First I want to clarify the current translation options:
1. Add languages to your Uwazi instance allows you to translate the user interface - so you can translate the labels on properties, and menus, etc. But, these user interface languages don't automatically connect to your documents - so if the user clicks on _French_, they will not necessarily see only the French documents - they will instead see all of the documents but the user interface will be in French. 
2. Another option is to create a property called _Language_ and apply a language to each document, which is what you have already done. What is missing right now is the ability to easily see _all_ of the documents that have the property _French_. 

It turns out it will take a lot of time to add languages to an instance with existing content - we need to create a new instance with all of those languages and then migrate all of your information to that new instance. Therefore, we want to explore improving this process instead of continuing to migrate each instance individually. We also want to improve users' ability to filter all documents based on a property, such as _Language_. 

So, can you clarify what you are trying to achieve by adding these languages to your instance? (Maybe it is both goals listed above) Also, can you clarify when you would need this? It would be great if you are able to wait a while (maybe a few months) so we can develop a better process that others can use. Let us know! Thanks. 

Others will reply to your first question.

**Comment by HSips** [comment]
@kjantin THanks for this. Yes, we are aiming for both goals, because the French speaker goes to the French version of a site or database expecting to see only French version documents.
Yes, we can wait for a while, several months if needed. In fact, I only started asking because it struck me that it may get more and more complicated to work various language versions later than sooner.
Thanks for the clarifications.

**Comment by HSips** [comment]
On the first point, any advice on why/how I cannot view the documents I uploaded in October 2016?

**Comment by kjantin** [comment]
@HSips 
> On the first point, any advice on why/how I cannot view the documents I uploaded in October 2016?

I hope @konzz or @daneryl can respond to your question about those documents. 

One last thing about the _languages_ property, there's a way to make it easy for your visitors to find documents in a language. Here are the steps:
1. It's best if you apply the same _languages_ property to every document (and/or entity) type that you want filterable to language. So do that first...
2. Then, select all your document/entity types from the filter in your library, and also select a language from your _languages_ property, such as French.
3. Copy the URL for that filter
4. Paste that URL into a menu item called "French documents" or whatever you like. That way, users can access everything you have in French with just one click. 

Hope that helps!

**Comment by HSips** [comment]
Thanks for this @kjantin 
As I was explaining to @danicatalan the end product of the OAU/AU database will be rather huge.. The database will need to have 3 subdivisions of documents, and then still have the four language versions.. so, I am happy to hold off for now on using menu tabs to indicate language as we work through the mountains of info..
But will try it! Thanks!

**Comment by kjantin** [comment]
@HSips Unfortunately these documents are gone and we can't figure out why they disappeared. But we have noted this event and we'll look out for anything like this. If you experience this again, please open up another issue and let us know exactly what you were doing when this happens. We're sorry for the inconvenience of having to re-upload these documents! And we hope it doesn't happen again.
