### ISSUE TITLE
Missing/lost docs on CJGEA instance

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1081]
Hey @daneryl @konzz  Just had a working meet with Habiba of CJGEA. Noticed that of the 3 test docs on the uploads, the two which Habiba uploaded in Jan 2017 are also missing... NOw thankfully these were test docs for them so no biggy as per documents, but at least it tells us docs uploaded before Feb 2017 or late Jan in 2 instances went missing...
<img width="955" alt="missing docs" src="https://user-images.githubusercontent.com/22650647/27173715-4c16d048-51c2-11e7-9386-139d753a974a.png">

**Comment by HSips** [comment]
Thankfully, PALU and Pretoria don't seem to have this problem, from a random selection of docs..

**Comment by txau** [comment]
@HSips are you sure no one has manually deleted them?

**Comment by HSips** [comment]
@txau Yep. Sure. They are not manually deleted because the document 'cards' are still there. Same thing happened to the AU law instance.

**Comment by kjantin** [comment]
@HSips , I see 4 documents in the upload section:
1. Miss Anne Maingi uploaded Jan 7, 2017
2. FINAL Workshop Agenda pdf uploaded Jan 26, 2017
3. SSRN id2843913 uploaded May 22, 2017
4. T.AssemblyAUDec.291(XV) uploaded June 16, 2017

I am able to up open/view all of the PDFs except the first one titled "Miss Anne Maingi". There is also no meta data assigned to that PDF. So, it's possible that PDF never uploaded correctly and therefore no one would have taken the next step to assign a document type or properties. Or, that PDF was uploaded at some point, but was since deleted by someone or by our server. It's hard to know exactly what happened. But as mentioned in #1024, we will note this event and will keep an eye on it. If it happens again, please open a new issue and explain exactly the steps that were taken when uploading the PDFs.
