### ISSUE TITLE
Allow users to filter the collection using common properties and not relying on selecting a document/entity type

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#1086]
Current behavior:
In order to filter on any shared properties, I need to select some or all of my document/entity types to filter on. 
Requested behavior:
As a user, when I filter the document collection I don't want to have to select any/all document/entity types in order to find all of the documents/entities that share the property "Brazil".

**Comment by danicatalan** [comment]
We need to discuss a little bit about this. There are two approaches:

- If a property is shared in ALL document and entity types, display it on filters by default. This makes sense but it's too fussy, because one type without the property will remove it from the default.
- Allow users to add custom default properties (as currently with doc/ent types).

**Comment by danicatalan** [comment]
- Remove settings filters from **Metadata templates**. Setup all filters logic on **Filters** section.
- Allow users to modify how filters are grouped. There are two scenarios:
  - _Country of origin_ and _Country of destination_ grouped as _Country_ filter.
  - _Country_ property separated in _Country of origin_ and _Country of destination_.
- Allow users to setup properties as default filters (not just doc/ent types).
- Don't match filters just by name. Check how it works with matching with content.
- How basic mode and expert mode coexist while filtering?

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1398

**Comment by txau** [comment]
Addressed in https://github.com/huridocs/uwazi/issues/1398
