### ISSUE TITLE
Add delete reference functionality

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#11]

**Comment by danicatalan** [comment]
I have rename this functionality to **Remove connection**, because delete reference may be confused with _delete referenced document_.

I also include a specific unlink icon, to make it visually more different than the typical delete icon.

![remove-connection](https://cloud.githubusercontent.com/assets/6364153/16586418/19d5e508-42c6-11e6-887c-fe016ffd1cd9.png)

**Comment by txau** [comment]
Looks good to me. Moving it to dev.

**Comment by konzz** [comment]
Solved with #211
