### ISSUE TITLE
Improve multiple date ranges rendering

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1100]
The current format is too difficult to read. Maybe one range per line?

![screen shot 2017-06-26 at 11 56 30](https://user-images.githubusercontent.com/489831/27553000-9b09df9a-5a66-11e7-8241-f7dfbfc40504.png)

**Comment by danicatalan** [comment]
@konzz I updated `1100-metadata-rendering` branch with the new CSS to split every Multidate and Multidaterange on metadata. Also I added a subtle hover on cards to identify blocks of metadata:

![screen shot 2017-07-06 at 17 57 09](https://user-images.githubusercontent.com/6364153/27920364-939cf182-6274-11e7-94ad-0265df884246.png)

What we need now is to add <br> instead of commas to separate Multidates and Multidateranges when displayed on cards. Can you check this?

![image](https://user-images.githubusercontent.com/6364153/27920271-5a5a3286-6274-11e7-9e5f-4264912b8b93.png)

Thanks!

**Comment by RafaPolit** [comment]
@danicatalan @txau @kjantin 

The changes made to the library are finished and are 'type aware': only multidate and multidaterange type of properties render in multiple lines.

But the changes in styles made by @danicatalan also affect normal view of metadata in side panel and in entity view.

Are we sure we want this:
![screenshot from 2017-07-10 12-42-29](https://user-images.githubusercontent.com/4309019/28031643-929e016c-656d-11e7-806e-9c53567b48a1.png)

Instead of this:
![screenshot from 2017-07-10 12-42-53](https://user-images.githubusercontent.com/4309019/28031659-9d08cc9a-656d-11e7-8d4d-4ac7151782ea.png)

For very long multi-select like countries of mechanisms, or signers of documents, this could be really uncomfortable, hence the reason we did the coma-separated values.

What do you guys think?

**Comment by txau** [comment]
Is only for dates!

**Comment by danicatalan** [comment]
@RafaPolit yes, should create that className to break the lines. Let me know if you need help with the CSS properties for both classes.

**Comment by RafaPolit** [comment]
> Is only for dates!

Yes, this is what I thought as well.  This behavior has now been isolated only for multi-date type of properties.

**Comment by kjantin** [comment]
Why does the date range use a tilde instead of a dash? 
![image](https://user-images.githubusercontent.com/354426/28382407-f9f891c2-6c8b-11e7-9ec0-3f51dcf7f518.png)

**Comment by txau** [comment]
@kjantin you are right. Also that symbol has a mathematical connotation of "approximately", so probably is not the best character.
