### ISSUE TITLE
Sort by relevance while searching

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1116]
Elasticsearch assign a relevance to each document depending on the search performed. This collides with our current sorting methods that overrides this relevance.

We should design a way to manage this relevance while searching with current sort by methods.

**Comment by txau** [comment]
We need to find a solution for this since is tossing weird results as this one, while looking for "quito", but receiving first the fuzzy finder results as in "quinto":

![screen shot 2017-07-14 at 09 19 37](https://user-images.githubusercontent.com/489831/28219668-ff884fc6-6879-11e7-9983-dda26be5b1f8.png)

**Comment by danicatalan** [comment]
Another weird result, I was looking "Yarce" case but appears "marco":

![image](https://user-images.githubusercontent.com/6364153/29033824-916c20c8-7b96-11e7-8632-84766ac80f35.png)

**Comment by kjantin** [comment]
I'm running into the same problems when trying to demo the full text search. You would think that the more words you include, the most targeted the search would be and come back with fewer results, but when I search for "Conseil National pour la Défense de la Démocratie-Forces pour la Défense de la Démocratie" I get [40 results](https://hr-reports.uwazi.io/en/library/?q=(order:desc,searchTerm:%27Conseil%20National%20pour%20la%20D%C3%A9fense%20de%20la%20D%C3%A9mocratie-Forces%20pour%20la%20D%C3%A9fense%20de%20la%20D%C3%A9mocratie%27,sort:metadata.date_published)) because it's taking little parts of that phrase and searching on that too. :(

**Comment by RafaPolit** [comment]
Kristin's example is interesting, because it shows both the power and the shortcomings of using language specific search.  I'll try to explain the processing behind this:

- Search term is: Conseil "National pour la Défense de la Démocratie-Forces pour la Défense de la Démocratie" (this is in French)
- The text are mostly in English, therefore the 'language aware search' includes words like "la" and "de", because they are not common words inside English.
- If you show more results and scroll down to the document RECOMENDACIÓN No. 4VG /2016, which is in ES (spanish), now shown as ES due to the new language detector, you will see that "la" and "de" are NOT highlighted due to both being common (and removed) terms in Spanish.

So, obviously, having language specific awareness brings this issues to the table.  So, searching for French terms inside mostly English documents is bound to have this issues.  If you search for long phrases which include common English words like "the" or "a", they should not appear.

Again, I think that having the most relevant results will fix this, but yes, we should evolve the search procedure.  Still, there are tradeoffs from having language specific text search, that is for sure. This is one of them.

**Comment by txau** [comment]
@RafaPolit but even if we have sort by relevance, search results will be screwed up any time you sort by another criteria, like now.

I just think the sort by relevance is to be used in another context. A more general search engine that does not aggregate results by document.
