### ISSUE TITLE
Check loading entities with lots of connections

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1133]
https://cejil.uwazi.io/en/entity/100v6hugip7ousor
![screen shot 2017-07-13 at 14 53 08](https://user-images.githubusercontent.com/489831/28188112-370581e0-67de-11e7-9b3b-38ec12677c01.png)

**Comment by danicatalan** [comment]
@daneryl has more info about this problem:

> its not the server being blocked, its a long query to elasticsearch that finally stops with an error.

**Comment by daneryl** [comment]
@txau that entity has 1800+ connections, our server side search for connections its not optimized to handle this many, thats why is slow and nginx is timing out.
on the top of that this slowness is to generate de final query to elastic, elasticsearch is returning an error on this query because of a limit on speific parameters in an array.

the slowness is because of references.getByDocument(), we should fix the performance on this one by doing only one query instead of 1 per reference, and then figure out a better way to do the final query to elasticsearch.

**Comment by txau** [comment]
I guess you explanation is difficult to follow without the context. Anyway this is not only affecting this crash, but entities with many connections in general are loading super slow. We're clearly using the wrong strategy here. We need to fix this asap.

**Comment by RafaPolit** [comment]
Quick fix developed by @konzz has been merged which includes
- indexing the SharedIds and Source and Target document in MongoDB for faster searches
- "filtering" instead of "matching" the queries in Elasticsearch (which has no limit on parameters)

This has made the queries faster, and prevents Elastic errors.

System is still is doing a one-by-one references.getByDocument() as described by @daneryl , so I am not closing this issue yet.

Missing:
- [ ] Optimize references fetch to favor a single query rather than one per reference.
