### ISSUE TITLE
Delete connection button is not being displayed

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1136]
While logged in I should have the option to delete connections:

![screen shot 2017-07-13 at 18 34 37](https://user-images.githubusercontent.com/489831/28193525-a8b4df0e-67fa-11e7-9907-c36beda56c7b.png)

**Comment by danicatalan** [comment]
This is happening because the Signatory is assigned as a property on those Admissibility Reports, so there is just one way to remove this connection: editing the source document's metadata.

We should add a button here to remove directly that property value from the source document.

**Comment by RafaPolit** [comment]
Further info on this.

There are two types of connections: connections created automatically by metadata selects and multiselects, and connections made directly as connections.

The behavior is that you can delete connections created directly, but you cannot delete metadata connections.

Deleting a metadata connection (and therefore the metadata value) has implications we need to consider: what if the field is required and you are deleting the last one?  Is the user fully aware that he is 'removing' that property from the metadata?  Or does he think he is just deleting a connection and keeping the metadata?

I think we should not go this route, and just make every connection actually a connection, instead of the hybrids between metadata and actual connections.  Deleting the metadata properties is dangerous at this point IMHO without giving a lot more feedback to the user.

**Comment by kjantin** [comment]
This is working as we intended it to work.
