### ISSUE TITLE
Zoom inside the document

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1143]
For accessibility and readability purposes. This zoom is different to the browser zoom.

**Comment by kjantin** [comment]
This could be really complicated - needs further discussion.

**Comment by txau** [comment]
@kjantin in which sense do you feel this could be complicated?

**Comment by kjantin** [comment]
@txau I was just summarizing what the developers said about it - maybe we could discuss in next sprint

**Comment by RafaPolit** [comment]
The discussion was that we are using PDFtoJS to render the HTML.  It may include zooming or not, but since the idea is to render the HTML on server side eventually, we would lose that zooming and would have to develop it ourselves, or use a different approach other than relying on PDFtoJS.

So what we talked about is that it would be ideal to address this if and when we have server side HTML rendering of the PDFs.

**Comment by nwyu** [comment]
Closing this issue after discussion with programs team. This is seen as unnecessary functionality for now.
