### ISSUE TITLE
Integrate attachments into Metadata and rename it to downloads

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1146]

**Comment by RafaPolit** [comment]
I like the integration part. But why the renaming?

"Add an attachment", for instance, sounds much more intuitive than "add a Download to the document".

What don't we like about "attachments"? Where is it missleading?

**Comment by danicatalan** [comment]
I like te integration with Metadata, because Attachments are now hidden inside that tab.

Also I will keep calling them Attachments, because they are documents attached to the main one. We just can interact downloading them right now, but I can imagine a future with photos or videos attached to the main document and users will consume them with preview methods, without downloading them.

**Comment by danicatalan** [comment]
We should review this issue together with one that is currently on sprint: https://github.com/huridocs/uwazi/issues/1026

What do you think @txau?

**Comment by txau** [comment]
I think we have to rename it to downloads. I don't care about the possible future scenarios. We don't need to mix this with #1026, they are quite different actually.

**Comment by danicatalan** [comment]
This is a preview of what I think our current Attachments tab should be. I think it is a huge improvement in how users interact with this content, adding a lot of interesting information inside Metadata!

![preview](http://g.recordit.co/HVVZQZJoDl.gif)

**Comment by txau** [comment]
Looks great. A couple of comments:

- Do we need to display the number of downloads? 
- Are we changing the style of how we display items in the side panel? I think the boxes with borders and margins don't make effective use of all the real state.
- I think we can remove the "Current document" mark. I guess users will figure this out.

**Comment by danicatalan** [comment]
I don't know about the download counter. I'm my opinion is a nth on cards, completely a must on our future dashboard for admins, so I will keep the idea and decide in the future if we want to implement it together with other stats.

About the boxes, I made them inside boxes because the properties are already separated by a grey line, so it feels weird to have the same separation for properties and for attachments. What do you think?

![image](https://user-images.githubusercontent.com/6364153/28466262-299d61ea-6e2c-11e7-942a-47e10e8bc98f.png)

**Comment by txau** [comment]
I would remove the number and use a different style for the Downloads title, separating sections.

**Comment by danicatalan** [comment]
Updated. I think it looks great in documents. I kept the boxes on entities, but we can remove them too and display each download in one row (just remove a couple of CSS properties).

It's working fully functional on **1146-downloads-metadata**, but we should make QA and also modify all the E2E tests to this new layout.

![image](https://user-images.githubusercontent.com/6364153/28490423-2486655e-6eda-11e7-8e46-d5a21082a72e.png)

![image](https://user-images.githubusercontent.com/6364153/28490433-6d74b518-6eda-11e7-8919-f1de45b68041.png)

**Comment by txau** [comment]
@danicatalan LGTM

**Comment by RafaPolit** [comment]
As discussed during the sprint planning today:

Musts:
- [ ] Add the size of the file to the info on the item

Nice to have:
- [ ] Move the 'add download' button to the downloads section (only when logged in) in order for the button to me more 'intuitive' and have a clearer responsibility.  As is, you don't know what you are adding.

**Comment by kjantin** [comment]
Related to #1171

**Comment by txau** [comment]
@danicatalan check @RafaPolit comments please. You need to update the design.

**Comment by RafaPolit** [comment]
@danicatalan @txau We also need a 'blank statement': what happens when there is no downloads?

If the button is in the section, then we need to keep it and say: no downloads.  If the button is global, then should we not show downloads? Still a blank statement?

**Comment by RafaPolit** [comment]
Since these are now integrated to the metadata, I think that they should follow the 'metadata flow'.

We could show the delete and edit buttons only while editing (although it may be a bit cumbersome to edit the file names).  And we could show the + Add file just like we do on dates, also only when editing the entity or document.

**Comment by RafaPolit** [comment]
I have added the file size and moved the add button.  What do you guys think?
![screenshot from 2017-08-01 15-47-20](https://user-images.githubusercontent.com/4309019/28846390-df4026de-76d0-11e7-9e43-4d36433ebde2.png)

**Comment by RafaPolit** [comment]
@danicatalan I have created all the new styles required, this is ready to merge and waiting a PR.

If you want to try out things, please delete local branch and pull new one as it already has been rebased with dev.

**Comment by danicatalan** [comment]
We should hide the Downloads title if there's no downloads, just like a normal property. We can show the title and the button to add the first file if the user is admin or editor.

I like the button below the attachments. I updated the branch to fix some styling issues with sizes and paddings, so for me it's ready to deploy.

**Comment by txau** [comment]
@danicatalan @RafaPolit please don't forget to add the "Downloads" label to the translations.

**Comment by RafaPolit** [comment]
@txau Its already there. We have a new system that if you are translating something that isnt on the translations, you get a test error.   Its much harder to miss those now!

**Comment by RafaPolit** [comment]
This is all finished and ready to merge.  There was one important addition: we are now allowing updating, editing and deleting Downloads from within the Library and Uploads section directly, without needing to go inside the actual Document or Entity.

I think it makes for a much straightforward approach, and it fully integrates the downloads into the metadata, as the metadata is fully editable from the library.
