### ISSUE TITLE
Make sidepanel tabs more visible

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1148]
Users are not detecting sidepanel tabs easily because of visibility of the icons. We should improve those icon styles to make them more visible for the users.

![image](https://user-images.githubusercontent.com/6364153/28263076-cad11c7c-6ae5-11e7-8649-e855d59c8b98.png)

Also there's a request about changing the **Table of Content** icon. We can fix it inside this issue too.

**Comment by RafaPolit** [comment]
@danicatalan While you are at it, the z-index of the tooltips on the side panel are again messed up.

Could we please not do z-index on a 1-by-1 incremental, but have (like bootstrap) standards for priorities.

The problem here is that changing a single index messes up the entire priority stack.  We should have 'regions', like:
- Main sections from 0 to 99
- Side panel uses a higer level 100-499
- popups and modals use level 500-999
- on-top items like tooltips use 1000 +

That way, changing or adding a single item will not break again all the interface.
Thanks.

**Comment by danicatalan** [comment]
I can't replicate your issue, but I've never been such a fan of those z-index hacks. We should think z-index as layers and I understand your point (mentally assign a range for those layers) but In my opinion this will mess up the z-index more.

If they are messed up now, we shouldn't avoid the problem and fix it.

**Comment by RafaPolit** [comment]
> I can't replicate your issue
Really? Go to any entity! The tooltips for the tabs are behind the side panel (and you can see a small black point appearing in the single line of separation between the tabs and the side panel.

**Comment by danicatalan** [comment]
I see. I create a new issue to solve that problem #1169.
