### ISSUE TITLE
Bad margins / CSS rendering in settings

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1154]
- Weird scrollbars in settings > translations:

![screen shot 2017-07-19 at 11 22 52](https://user-images.githubusercontent.com/489831/28380467-ae65d330-6c74-11e7-9bc9-a766fed3bb67.png)

- No bottom margins in settings > filters

![screen shot 2017-07-19 at 11 24 50](https://user-images.githubusercontent.com/489831/28380545-f134f222-6c74-11e7-8a71-de89fc4cb965.png)

**Comment by danicatalan** [comment]
This CSS problems were caused because we kept the old layout on settings. I decided to update the layout with the CSS we are using in the whole app (full size width + sidepanel) and now it looks better and bugs are fixed automatically.

Apart from this update we can use this week to improve the whole Settings experience with some issues that are currently on sprint:

- Better styles, increase contrast between components and sections #1209
- Create good blank states for Filters, Pages, Menu... #1179 

What do you think?

![screen shot 2017-08-08 at 18 13 42](https://user-images.githubusercontent.com/6364153/29082381-98f4fc28-7c65-11e7-950a-f3721ee9ceba.png)
![screen shot 2017-08-08 at 18 13 28](https://user-images.githubusercontent.com/6364153/29082379-98f17896-7c65-11e7-96c0-5e0e72771ab1.png)
![screen shot 2017-08-08 at 18 13 20](https://user-images.githubusercontent.com/6364153/29082380-98f4a0b6-7c65-11e7-9222-72421bd1069d.png)

**Comment by RafaPolit** [comment]
@danicatalan Since you are already 'there', could you please also fix the spacing between the 'hints' and extra instructions in the collection pane.  The bottom margins are really weird, and the separation between sections is not that clear either.

**Comment by txau** [comment]
@danicatalan go for it then.

**Comment by danicatalan** [comment]
This is the direction I'm taking for the new UI settings. It's a good change just improving the CSS, but I still need to review every section and fix pertaining issues.

I will try to touch the markup as less as possible to not spend time on modifying E2E tests.

![image](https://user-images.githubusercontent.com/6364153/29132303-1b2dcc22-7d30-11e7-8f1b-98c73353427d.png)

![image](https://user-images.githubusercontent.com/6364153/29132319-21e249c6-7d30-11e7-85c4-c2dec401adfd.png)

**Comment by RafaPolit** [comment]
Looks much cleaner!

The size of the side panel, even though when it is on the right it looks perfect, at the left side it looks a tad too wide?  Perhaps it is because all the options are really short-named, but maybe we could try with a narrower left side panel?

**Comment by RafaPolit** [comment]
Now that I actually 'read' the labels... "Metadata" is the wrong name for it, isn't it? It should just be Data? Or Data models? But not metadata.

**Comment by txau** [comment]
@RafaPolit ""Metadata" is the wrong name for it, isn't it? It should just be Data? Or Data models? But not metadata."

I guess that label came from the idea of the data being the content of the documents, so the metadata is everything around it. It's a very tech label that probably most users don't relate to. We could definitely change it for something more meaningful, like "Bazinga!".

**Comment by danicatalan** [comment]
> Now that I actually 'read' the labels... "Metadata" is the wrong name for it, isn't it? It should just be Data? Or Data models? But not metadata.

@RafaPolit I was thinking the same. What about "Content"?
