### ISSUE TITLE
Add modal asking users if they want to upload an attachment in one or all languages

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1171]
Implement #1026.

As we talk on our last call, once a user uploads an attachment we will ask if they want to upload it on once language or in all of them.

The expect action in most of cases is to upload the attachments to all languages (the same when uploading the document on _My files_), so I decided to just use the green button on **"Upload to all languages"**.

![prompt](https://user-images.githubusercontent.com/6364153/28453423-a13267b2-6df7-11e7-8be7-58c34e1b8450.png)

- - - - -

![n5djkqsgjx2](https://user-images.githubusercontent.com/6364153/28453343-37231902-6df7-11e7-835d-b2cfa7f447bb.gif)

**Comment by txau** [comment]
We need to make sure that option doesn't show up if:

- There is only one language.
- The instance is not using fallback for languages.

**Comment by RafaPolit** [comment]
@txau @danicatalan @kjantin I was thinking that now that the button is within the downloads section, if it wouldn't make sense to just add another option.

I agree that on the bottom action buttons it was kind of 'too much', but perhaps now that it is elsewhere, we could forgo the modal and additional question, and go with something like this:

![screenshot from 2017-08-01 18-56-02](https://user-images.githubusercontent.com/4309019/28851927-519503c0-76eb-11e7-896a-d45c0267221e.png)

**Comment by danicatalan** [comment]
I'm scared about having too much actions and buttons on the interface with solutions like this.

**Comment by kjantin** [comment]
I think I prefer the approach that Dani proposed above, that the user would first click on the button to add a file, and then they would be asked how they want this file to work with other languages. I like the idea of bringing the user through the steps - it seems to make it easier and clearer.

**Comment by RafaPolit** [comment]
Ok, maybe I should have started by explaining why I was aiming (hoping?) for the other solution:
First, its much faster to implement (but this shouldn't be the main problem).

The real issue here as I see it is, follow the flow of the scenario proposed in the first post:
- User clicks "add"
- User selects file in modal 1
- Interface UPLOADS the file (this could take a while!, for some files minutes even)
- Afterwards the user is asked where he wants the file

What happens if the user thinks "that's it" and walks away from the procedure? We have a limbo file and a user asking why the uploads are not working.

Alternatively, we could ask before selecting the file (this would be even harder to implement as the click is 'tied' to the input field), and then the user selects the file and the upload process begins.

Still, I think it cumbersome to have three steps and two modals involved in uploading a file vs. the usual two step click and select everyone is so familiar with.  That was why I was looking for a different approach to the 'asking modal'.

Perhaps we can find another (or a middle ground solution)?

**Comment by danicatalan** [comment]
We can use a checkbox to decide if you upload the document but there's the risk of people doesn't reading that checkbox. With a nice integration with the button, maybe active it by default and nice to have remember the last choice to facilitate users uploading those documents.

![image](https://user-images.githubusercontent.com/6364153/28878337-433c6afc-779f-11e7-9132-b932277f0944.png)

**Comment by txau** [comment]
@danicatalan I think that is a bad approach because users are going to hit the button BEFORE they tick the checkbox. So many times, they are going to have to go back in their steps because they didn't think about other languages.

What about another mechanism, if you are logged in AND you have more than one language, we add an action button to the files for copying to other languages. BTW I don't see the delete button in the sketches.

**Comment by RafaPolit** [comment]
@txau, the delete and edit buttons are all in there.

> What about another mechanism, if you are logged in AND you have more than one language, we add an action button to the files for copying to other languages

That is exactly what I was aiming for with this:
![screenshot from 2017-08-01 18-56-02](https://user-images.githubusercontent.com/4309019/28896385-d8d66fe8-77a1-11e7-866c-2b10c6d940f0.png)

I still think this is the easiest and least confusing route.

**Comment by danicatalan** [comment]
@txau @RafaPolit We are overthinking this solution that doesn't add great value.

If you think adding two buttons is not a problem, go for the simplest solution (Add file in this language / Add file for all languages).
