### ISSUE TITLE
Stuck in "processing..." in uploads

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1197]
Uploaded files in CEJIL get stuck in "Processing..." for ever. Apparently files are uploaded but they are never flagged as completed.

**Comment by RafaPolit** [comment]
@txau Cannot replicate this (not locally not even on CEJIL's own instance).  Uploads are working as expected.

Perhaps its a particular PDF? Can they share with us the PDF that is failing?

**Comment by txau** [comment]
@RafaPolit apparently we were using old client side code. We had to reload.

Closing issue a solved.

**Comment by txau** [comment]
Apparently is still happening for 2 documents:

![screen shot 2017-08-09 at 17 05 18](https://user-images.githubusercontent.com/489831/29128866-5e8f09dc-7d25-11e7-98fa-888b8002d725.png)

**Comment by RafaPolit** [comment]
Looking into it.

**Comment by txau** [comment]
Not urgent.

**Comment by RafaPolit** [comment]
@txau, this where uploaded on August 1, which was the day the index reached its limit.  The issue is fixed, but those PDFs did not finished processing as expected.

Please tell CEJIL to delete them and reupload them.  Issues are fixed.  Those two items just are 'leftovers' from a previous issue.

We have tested those same PDFs and they are uploading correctly.  We are not deleting them ourselves so people can know which documents need to be reulploaded.

**Comment by txau** [comment]
Got it. Thx.
