### ISSUE TITLE
Versioning for client code deploys to avoid caching

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1199]
Right now client code is being cached in the browser and users sometimes are running old code.

**Comment by RafaPolit** [comment]
@daneryl and I developed a useful way of doing this in our previous project, maybe we can implement something similar here:
- Each request sends the local version in the header
- A server middleware checks that against the current server version (absence of value denotes old version as well, of course)
- It replies with the error code already accepted by the older code so people know whats happening

The one downside of this approach is that you had to remember to manually up the client version each time a change happened.  Maybe this can be automatically tied to something like the commit or something similar?

**Comment by txau** [comment]
What about time stamping the .js includes?

**Comment by daneryl** [comment]
@txau wen can do this with webpack https://webpack.js.org/guides/caching/, stamping its the simpler solution , what @RafaPolit proposes is for preventing a user being on an older client because he did not reloaded the page after a new deploy, any request to the server will inform the client that there is a new version available.
