### ISSUE TITLE
Reduce fuzziness in full text search until we can better handle relevance

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1210]

**Comment by danicatalan** [comment]
@txau @kjantin can we move this to `Priority: High` as it is low effort but much needed? Search box is unusable right now.

I know we want to keep false positives when Relevance is developed but anyway the amount of results is still absurd:

## Without keywords: 1694 results

![image](https://user-images.githubusercontent.com/6364153/29278932-7e5521a8-8116-11e7-820e-6f66c2128af7.png)

## With "hermanas serrano cruz" keywords: 1481 results

87% of the collection as results.

![image](https://user-images.githubusercontent.com/6364153/29278956-9f856d10-8116-11e7-9a03-8f53f6ef8c27.png)

**Comment by RafaPolit** [comment]
This is the result with the fuzziness turned off:
![screenshot from 2017-08-15 10-29-37](https://user-images.githubusercontent.com/4309019/29322883-bffa92f8-81a4-11e7-8f21-d29fde54e17a.png)

As I have said a million times now, its the relevance of results that will fix this issue, not turning off the fuzziness.

At any rate, this will be finished by today if there is urgency to deploy this.

**Comment by danicatalan** [comment]
Completely agree with you @RafaPolit, the relevance . Anyway the results now are more concrete (half the results), and we can build and configure the fuzzy finding from bottom to top.

For this specific case, I prefer to hide false positives until we have a good system because adding them is adding too much noise to the results (and I personally hate when a text search is showing me things I don't want, no matter if they are ordered by relevance, the number of total results is a lie).

**Comment by danicatalan** [comment]
@txau @RafaPolit about the urgency, I think this shouldn't be forgotten and that's why it has a high priority. But is not critical, so I don't think we should force to deploy just because this issue.

**Comment by txau** [comment]
@RafaPolit you are right, these results are very bad. I think we should switch this task to implementing the order by relevance.

Still, if users select an ordering criteria different than by relevance, every time they are using full text search the results are going to be a mess.

**Comment by RafaPolit** [comment]
@txau Ok! Just in case, until that is working we will keep fuzziness off.
