### ISSUE TITLE
Add labels to all properties in cards

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1264]
Date properties render the labels inside cards. For better readability, add label to all types of properties.

![image](https://user-images.githubusercontent.com/6364153/29708632-a5012f7e-8989-11e7-934d-fcc5a3c7c383.png)

**Comment by RafaPolit** [comment]
We talked about this on a prior sprint planning and it was more or less agreed that we would make that label showing configurable in settings.  That way, labels that are absolutely obvious (or that the admin deems it not useful to show the label) would not clutter the UI.

For instance, in a "Person" entity, if you have the gender property, have it render as Male, or Female, requires no label or explanation.  But if you are doing a dating profile, you would need to distinguish actual gender from dating preference, then the labels would make sense.

Where are these requirements coming from and why are we back to reporting solutions instead of problems to be solved in the Issues?

CC: @txau , @kjantin

**Comment by kjantin** [comment]
I agree it would be great to give the admin the ability to display labels. 
I think it's fine for the UX designer to suggest improvements without defining a specific problem from a user. 
I don't think it's a big priority, but it would be nice to have.
