### ISSUE TITLE
Map viewer for Uwazi

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1282]
- [x] Research library for maps

**Comment by RafaPolit** [comment]
I have done some research.

I found two that I think are very robust and should do well enough for our needs.  Perhaps the main difference is WebGL.  As noted in this article: https://blog.webkid.io/making-maps-with-react/ 

> Before you start developing your map you should decide if you need WebGL support or not. You may consider using WebGL if you have a lot of features to be displayed at once, let’s say 10k markers for example. For a normal map a library without WebGL support will be sufficient.

So, the options are:
- React Leaflet : https://github.com/PaulLeCam/react-leaflet
- React map GL : https://github.com/uber/react-map-gl

This first one is a React wrapper for the Leaflet mapping library, so its very well maintained and works great.  It does not uses WebGL (as far as I can tell) and, besides that 'possible' limitation, it lists this as other limitations:

> Leaflet makes direct calls to the DOM when it is loaded, therefore this library is not compatible with server-side rendering.
The components exposed are abstractions for Leaflet layers, not DOM elements. Some of them have properties that can be updated directly by calling the setters exposed by Leaflet while others should be completely replaced, by setting an unique value on their key property so that they are properly handled by React's algorithm.

The second one looks INCREDIBLE!  Developed by the Uber guys (always a good start, IMHO). Its very robust and has a ton of features.  It looks a little less friendly to implement.

Another issue to check would be the footprint, specially if we are not going to do load-on-demand.

Has anyone find something else? Stumbled upon the same ones?
@txau @daneryl @konzz

**Comment by konzz** [comment]
Based on this issue https://github.com/uber/react-map-gl/issues/353 I think that React map GL does not support server side rendering, still I don't think thats an issue for any of them

**Comment by kjantin** [comment]
How about OpenStreetMaps? http://wiki.openstreetmap.org/wiki/Main_Page

**Comment by RafaPolit** [comment]
I have run tests with the react-map-gl library.

As expected and what was already apparent when researching, it is POWERFUL! You just feel it while coding.  It just does what you would expect.  It also moves very smoothly from one position to the other, and, specially, when changing zoom values.

The React layer is really well thought and blends in perfectly with our code.

![peek 2017-09-12 16-19](https://user-images.githubusercontent.com/4309019/30348785-31acf264-97d6-11e7-9604-492934a379b1.gif)

Mouse and keyboard interaction allows for scrolling, rotating, tilting, really neat! Mobile interaction is really slick as well and it moves very naturally.

There is one big issue that we should discuss: this is a react component that exposes Mapbox GL JS.  Mapbox, while incredibly powerful, it is not forever free.

You need to register and get a mapbox access token. We would probably require each client to have their own token, because its free up to 50.000 map views per month.  After that, users would have to pay $0.50 per 1000 additional views.  Does not seem like a lot, and they have a 'pay as you go' plan.  But a 'view' is not a page load, its a bit more complex than that.  Interaction with the map spends views.

The documentation documentation says:

> Web maps consist of many individual tiles. As users interact with maps by panning or zooming, more tiles are loaded.
>
> A single map view is:
>
> Four tiles when the map uses Mapbox Studio styles.
15 tiles when the map uses Mapbox Editor projects or Mapbox Studio Classic styles.
One request to the Mapbox Static API.
These counts are typical for a single page view on most websites. More than one map view can be generated during a single session as your users interact with the map.

During my tests, and because I was changing styles, and tilts, and views, I spent 250 views on the whole day of testing, doing lots of refreshes and moving around.  So, making some assumptions, the 50.000 limit would allow around 10 people to spend the entire day during the entire month just looking at the maps.   Above that, clients would have to pay. 

As it is, if we (the clients) can live with live with the pay-as-you-go model, this library would be a really good addition to Uwazi.

I am going to give tomorrow the react-leaflet a go and see if it is as robust and as easy to implement and what other issues it may have.

**Comment by RafaPolit** [comment]
I have done the testing with the react-leaflet package.  It is nice, more or less the same integration as the Mapbox wrapper.  Server rendering is REALLY not supported, server throws errors if there isn't a client workaround to prevent the server side rendering, but that is not new, we have done similar things on the timeline.

The are a couple of downsides as we already knew:
- The 'snappiness' of WebGL vector based graphics vs the Image-based maps.
- Image-based viewers do not allow for tilting or rotating the view

This last one is a pity, because, as seen on the above comment's gif, it just really makes the map POP!.

The Leaflet option is not that catchy:
![screenshot from 2017-09-13 16-37-25](https://user-images.githubusercontent.com/4309019/30402207-9b4802c8-98a2-11e7-9042-f884425d0ea4.png)

One interesting part is that, if the clients want it, we can hook the mapbox 'nicer' maps to the leaflet viewer (being both OpenStreetMaps compatible), it can be done.  Still it would require a token, but now its not an obligation.  Its an option.  But it ends up looking almost the same (without the nice camera tilt and rotate):

![screenshot from 2017-09-13 16-45-17](https://user-images.githubusercontent.com/4309019/30402321-f4d8c278-98a2-11e7-9e6d-832fd82f8aa0.png)

I was really afraid that, with the robustness of the mapbox approach, that I would hate the leaflet one, but as it turns out, its just as good (minus the commented features).

If we can have possibly-paid scenarios, I'd choose the Mapbox option, if not, I think we can't go wrong with the react-leaflet version.

What do you guys think?

**Comment by txau** [comment]
Thanks for the info @RafaPolit. Both options seem robust and covering all the features we need. 

I'm a little bit concerned about the activity on Leaflet. The main dev also works at MapBox (he was likely recruited?), this project was super active 3-4 years ago but the pace seems to have slowed down (looking at their repo activity).

Can the MapBox option work with OSM tiles? If so would it be free for our users?

**Comment by danicatalan** [comment]
Closing this, implemented the Uber wrapper around MapboxGL JS.
