### ISSUE TITLE
Improve sorting property

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1289]
- [ ] Highlight the sorting property in cards. Different proposals:
  - [ ] Coloring
  - [ ] Icons in label

**Comment by danicatalan** [comment]
These are the two options proposed yesterday:

![sort-color](https://user-images.githubusercontent.com/6364153/30319561-86e7fc68-97b0-11e7-9230-e8ded2053975.png)

![sort-icon](https://user-images.githubusercontent.com/6364153/30319563-8705269e-97b0-11e7-9011-1fa439057964.png)

I'm surprised about the icon because we tried this before when the labels were hidden and did not worked well, but displaying all labels inside the cards make this very easy to implement and with less noise than colours.

The problem with it will appear if we allow users to show/hide labels in the future. I'm honestly thinking that feature is adding more complexity instead of adding value every time, so I'm in for the icon option in the label and forget about show/hide labels in the short term.

**Comment by RafaPolit** [comment]
What about the icon and using color ONLY on the label and not on the result, to make it a bit more obvious but not that strong as in the first one?

Also, I'm not convinced that that is the proper icon.  What about this one? : http://fontawesome.io/icon/sort-amount-desc/

Also, did you try to add the icon at the end of the label instead at the beginning? In my mind that would be more readable also.

**Comment by danicatalan** [comment]
@RafaPolit and I have been working on some options for this. All options involving colours are adding too much noise to cards, so we've decided to work just on icons. What do you think its the best option?

![icons options](https://user-images.githubusercontent.com/6364153/30337085-84cc5064-97e7-11e7-9769-005efad27926.png)

cc/ @txau @kjantin

**Comment by kjantin** [comment]
I think the icon is a little confusing because to me it isn't saying "this is the property that this list is sorted by" - instead I'm inclined to click on it to sort something. But I don't know of a better option, besides Rafa's idea of having the label of the property being sorted in bold, or somehow stand out. 
But, if I had to choose from one of the icons above I would choose the ones on the far left, where the icon sits to the left of all the properties.

**Comment by txau** [comment]
I'm also on the side of using color/bold.

**Comment by danicatalan** [comment]
![image](https://user-images.githubusercontent.com/6364153/42289203-82676ec0-7fbe-11e8-945d-a825ce0f53eb.png)
