### ISSUE TITLE
Sidebar width on mobile viewport

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#130]
I've been fixing the layout on different viewports and now we have the sidebar opened on mobile version with full-width. I think is antinatural because we never hide the content in other viewport sizes.

@txau what do you think about limit the sidebar width - like in this GIF?

![sidebar_size](https://cloud.githubusercontent.com/assets/6364153/15856157/1b26ef42-2cb4-11e6-9b6c-c3e57794c6d2.gif)

**Comment by txau** [comment]
@danicatalan Is this going to affect us in the future in the sense of having more maintenance? Ie. We design something for the sidebar but since its different sizes now, we have to tweak sizes for the mobile version.

If that is the case, I would say we go for full width even if its counterintuitive (actually it doesn't look that bad to me).

**Comment by danicatalan** [comment]
Nope, it is just change a col-xs-12 with a col-xs-10 class or similar. Content inside the sidebar fits the size automatically.

**Comment by txau** [comment]
Ok. If that is your opinion lets do it.

(I'm betting on a "I told you!" sometime soon =D)

**Comment by danicatalan** [comment]
I hope it wont be necessary :)
