### ISSUE TITLE
Link on CEJIL hero point to library with old sort-by property

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1368]
CEJIL's homepage has a hero with three links pointing to the library. Both _Causas_ and _Medidas provisionales_ are pointing to the library with the entities sorted by **Ultima Actualizacion**.

- https://sidh.cejil.org/es/library/?q=(order:desc,sort:metadata._ltima_actualizaci_n,types:!(%2758b2f3a35d59f31e1345b48a%27),userSelectedSorting:!t)
- https://sidh.cejil.org/es/library/?q=(order:desc,sort:metadata._ltima_actualizaci_n,types:!(%2758b2f3a35d59f31e1345b4a4%27),userSelectedSorting:!t)

Now they deleted **Ultima Actualizacion** and the links are broken.

![screenshot 97](https://user-images.githubusercontent.com/6364153/32776533-27f901a2-c933-11e7-832e-5181b3556cf0.png)

![image](https://user-images.githubusercontent.com/6364153/32776526-233a5cec-c933-11e7-8236-c8cce929507b.png)

**Comment by RafaPolit** [comment]
There are two important fixes in the PR:
- CejilHero custom hook now uses, as default, the undeletable creationDate as sorting property to prevent further default errors
- CejilHero custom hook now takes an optional "links" array. You can pass any /library/ link and it will use that instead of the defaults.  For the moment, it is limited to /library/ links.  You cannot link pages or other uwazi links.
