### ISSUE TITLE
Make list of highlighted text excerpts clickable?

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1391]
This is related to #1390 
When performing a full text search and clicking on a card, I see highlighted where in the text the word is mentioned.

Expected behaviour: When clicking on a highlighted excerpt, I am taken to the place in the document where it is mentioned.

**Comment by danicatalan** [comment]
@whyfrycek clicking on a highlighted excerpt should open the sidepanel with all the excerpts. On that panel, if you click on the number, you will open the doc on the page the excerpt is mentioned.

![image](https://user-images.githubusercontent.com/6364153/33422061-919c66fc-d5b4-11e7-89d9-88dfafab75fd.png)

It is not possible to open directly from the card because the common behavior when clicking cards in Uwazi is opening the panel (not directly the document). Also, for most of the documents the keywords will appear more than once, and we can't render all excerpts inside the card.

**Comment by whyfrycek** [comment]
Great to know that you can click on the number. Works well! We did see the overview on the left. Unfortunately, the user, @manush and me didn't realise, so it would not seem very obvious. Not sure, if it's clutter, but perhaps a button or another form of stronger highlight that you can jump right into the text?

**Comment by danicatalan** [comment]
That's a great idea, thanks for the feedback @whyfrycek!

**Comment by danicatalan** [comment]
- [ ] On sidepanel: make all the search result clickable.
- [ ] On sidepanel: highlight each result on mouseover (to emphasize its clickable).
- [ ] On document: by default, no search results are highlighted.
- [ ] On sidepanel and document: clicking on a search result highlights both the sidepanel and the document result.
