### ISSUE TITLE
Idea: Submission of documents (and other info) for non-authorised users

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1392]
So far, only authorised users can submit a document, including associated metadata.

Would it be possible to submit a document as a non-authorised user, adding metadata which would not necessarily be made public (information about submitter, including contact details) upon approval of document.

Use case: https://minorityforum.uwazi.io/en/page/l24m3lni1m8n4fz9gz80n3ik9

**Comment by RafaPolit** [comment]
We discussed this in the past: the idea was to allow anyone to upload documents and you would then have an editor that would approve your document.

This had some technical issues that had to be addressed and that I will list afterwards, as they weren't all that complex (albeit time consuming).  The main issue was:
- This could potentially create literally thousands of entries (even possible spam or abuse).  So the editor would have a tremendous amount of work to sort out the useful ones among the garbage.   So we kind of decided in favor of a new user role that is contributor, but that still requires some sort of authentication.  This also allowed a better track of who the submitter was.

The other approach technical difficulties included:
- We required a new type of user in which, being unregistered, has rights to write in the database.  The issue is that our process involves first uploading the document and then editing the metadata.  So if this is a non-registered user, how do you 'track' that he is the one that uploaded the document and is now ready to edit metadata?
- Once created and added metadata, can you edit your own document before it is approved?  If yes, again, how do we 'know' its the same contributor if he is not a registered user?
- How do we validate or record submitter data? Just with what the write? Do we verify email?
- Once approved by an editor, obviously you lose the rights to edit it.  But if someone else with editor or admin permissions edits the data, is this still a document you posted, even if the data could have been edited? Do we keep track then of changes?

It was not as straightforward, most issues developing from the fact that we have no info to work with with this 'anonymous user'.

Obviously, there are workarounds (such as using cookies, sessions or tokens to allow editing your own document) but they were time or session constrained.  You could not 'come back' to do a second edit.

Still, it was an interesting challenge.  Perhaps we could move it back to the 'thinking' table.

**Comment by danicatalan** [comment]
I'm still in favor of registered users if they want users to perform the whole cycle (uploading documents, edit metadata, create connections and request for publish). It will help the collection to grow in a more sustainable way and hopefully will create a compromise between those users and the administrators to work together. Some data models can be very complex, so I doubt random users uploading and fulfilling the metadata in a proper way.

For this scenario we will need:

- Allow users sign up in the instance: originally not just for publishing purposes, also for bookmarking documents or notifications of new documents with a specific property.
- Document ownership by users: whatever strategy we decide for ownership permissions should apply in this scenario too.

On the other hand, if an instance wants a way to let anonymous users to send a collection of documents (for example, a leak), a simple contact form will work. In this case, is not the anonymous users who works on the metadata. It should be the editor who reads the PDFs and uploads them to Uwazi, knowing the data model and discriminating which documents are worth to upload and which aren't.

**Comment by whyfrycek** [comment]
Thanks to both of you for the well-reasoned response! I appreciate it's a tricky balance, and particularly spam would be an issue.

I think a simple contact form could a great starting point; then we could study actual behaviour/needs following that, and decide on what is the best way forward or it's good enough.

I would not worry about unregistered users wanting to come back to make edits, though.

**Comment by kjantin** [comment]
This is something being requested by CLEEN also (https://cleen.uwazi.io):
> The idea is to allow anyone to upload court documents while we approve the documents if it is good.

**Comment by kjantin** [comment]
<h1>Proposed approach 1</h1>
Display the form:
1. Create an entity type called "Submission form" and add the properties that you want to display for anonymous users. 
2. Add a "form component" to a page and then call on this entity type to display there. 

Workflow when receiving information via the form:
1. When someone submits a "Submission form", it is saved as an "unpublished" entity. 
2. The admin can change the entity type from "Submission form" to whatever entity they want this information to be saved as in the database. The properties that are the same will be carried over, and then the admin can fill in the additional properties. 
3. The admin can publish the entity when it's ready. 

(Will include a Captcha to deter spam)

**Comment by bertver** [comment]
Input from Forum Asia:
"The form that we want to have is a simple one, basically just asking the user to share the case with us, as detailed as possible. Because FA will to the tagging on our own, for the sake of data consistency. What I am thinking is only to have the following:

Name:
Email (compulsory):
Case detail:
News link (if any):

*strong captcha*"

**Comment by bertver** [comment]
Input from SAIH Norway:
"My immediate feedback to how the online submission would work, I think there should be an option to display violations in the public website as “unverified”. I don’t know if you remember, but we mentioned https://iraq.ceasefire.org/index.php/main?l=en_GB as a reference when we started the conversations last year. I think that ceasefire is even more live than what I would be comfortable with, but we can make it function in a way where the editor can review and assess that the violation as likely, and then publish it as “unverified” until it is further investigated. “Verified” and “unverified” here works as a filter."

This would be an alternative to having submitted forms as a form in a particular template "forms submitted" which after review would be changed to another template.

**Comment by mylaa** [comment]
Input from me on this request: 

- Create a “Submit” form to allow users submit a document as an attachment through the database.

- **Send** Icon and function.

- A newly submitted document will be displayed on the database backend, in the section of Private documents.

- UI: A visual identification will help to recognize a new submission.

- UI Feedback: _Successfully submitted._ 

- Ability to customise 1+ submit forms within 1 instance

- Allow some fields to be **mandatory** and other **optional.** 

- Newly submitted documents will be added on the backend of Uwazi, in Private documents section. UI: Some kind of visual identification that there is a new document in the library (a red mark, for example).

**Comment by kjantin** [comment]
> Input from SAIH Norway:
> "My immediate feedback to how the online submission would work, I think there should be an option to display violations in the public website as “unverified”. I don’t know if you remember, but we mentioned https://iraq.ceasefire.org/index.php/main?l=en_GB as a reference when we started the conversations last year. I think that ceasefire is even more live than what I would be comfortable with, but we can make it function in a way where the editor can review and assess that the violation as likely, and then publish it as “unverified” until it is further investigated. “Verified” and “unverified” here works as a filter."
> 
> This would be an alternative to having submitted forms as a form in a particular template "forms submitted" which after review would be changed to another template.

I think we can address the need of marking something as "verified" by using a simple property.

**Comment by bertver** [comment]
thanks @kjantin my question was whether this simple property could replace the practice of changing the template.
