### ISSUE TITLE
Discussion: Usability on Card - when open document, when display metadata

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#1399]
User reports:

"When I click on the title I expect the read view to open and not the medadata card to appear, which is triply annoying as it hides the facets then I need to figure out how to close it again, and then I have to notice the card button actually opens the doc (this button should be an eye, more intuitive)..

What I propose instead is to to put an "i" button in the card to open the metadata card, which can be a toggle and have a different color when its open or closed. And next to it to put a document download button. And then to put an eye button to open the reader, for those who didn't figure out to click the title."

**Comment by txau** [comment]
This has been discussed and so far is the first user complain regarding this behaviour (other users may feel that way as well). We decided that the default behaviour is to open the side panel instead of the document because its cheap and quick. Opening the document takes a redirect and a lot of bandwidth to download and render the doc.

**Comment by danicatalan** [comment]
One thing we can improve here quickly is always showing the "Open document" button.

**Comment by whyfrycek** [comment]
I think it would be worth considering to make it more apparent what would open the document, so you now where to go when you have that expectation. I do agree that it may not always be useful to open right away, especially if users are browsing information without knowing which concrete document to open first. I like Dani's suggestion.

**Comment by danieldesposito** [comment]
I still think its counter-intuitive to show the metadata instead of displaying the document, even though it may be more convenient for you in terms of system resources.

Have a look at the screenshot from Academia, when I click the title it simply opens the doc. Thats what I expect.

Also the icon used to open the doc is not intuitive. I would put an open doc icon which has an eye on it, to signify a preview. I would also want a download button next to it, so I can download the doc without opening it. Have a look at the Acedemia text icons, I like them because they don't make me think.

![screen shot 2017-12-11 at 19 46 36](https://user-images.githubusercontent.com/4427138/33848104-073d65ae-dead-11e7-8ec8-d69ff378eb5c.png)

**Comment by danicatalan** [comment]
Some updates on this task:
- Always show button.
- Be explicit: change icon with text.
- Improve how to open a document on collapsed view.

**Comment by txau** [comment]
@danicatalan maybe a half-way solution is to always show a dim button that changes color on hover.
