### ISSUE TITLE
Users can't create connections if the docs are not published

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1431]

**Comment by konzz** [comment]
check with #1499

**Comment by RafaPolit** [comment]
This is not related to #1499 as it seemed in the beginning.

For #1499, you were able to create a connection from within an unpublished document to a published document. When you move into the published document, the unpublished one would be visible, even if you weren't logged in.  This has been addressed in a commit.

The problem here is that if you are creating the connection from the published document, you have no way of selecting the unpublished one: not via multiselects of new relationships, nor with the relationships search in the side panel.  They are simply not shown.

The fix for this is not as simple, I'm looking into it.

**Comment by RafaPolit** [comment]
This has been mostly fixed in https://github.com/huridocs/uwazi/commit/a21a5875d1425512a44d95d65c6c822a89b8a107 .

A logged user now has unpublished entities and documents as thesauris.  Since this means that not-logged users and logged users have different thesauris, the login process NEEDS to reload thesauris.

- [ ] Reload thesauris upon login to have unpublished entities and documents as thesauris.
