### ISSUE TITLE
Unpublished info being public in connections despite not being logged in

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1499]
Linking a document from uploads to a published entity or doc, makes it visible in the connections panel of the published doc even if you are not logged in.

![screen shot 2018-03-08 at 12 28 21](https://user-images.githubusercontent.com/489831/37148886-5142f35e-22cc-11e8-9fd7-a5b5c12c1bea.png)

**Comment by RafaPolit** [comment]
Should we address this only on the hubs update directly (assuming it is happening soon) or do you want it fixed on the current dev instances as well?

**Comment by txau** [comment]
@RafaPolit in the update only please!

**Comment by RafaPolit** [comment]
This has been resolved in https://github.com/huridocs/uwazi/commit/daa85f27bd590c602e915ec8ea081f43be89bfa4

**Comment by RafaPolit** [comment]
One missing aspect of this implementation is that relationships that have been assigned to the metadata are returning to client.  The value itself is not shown, because the thesauris don't have a match for that value.  However, the value is returning to client nonetheless, and if you inspect the result of the server request you can have access to unpublished entity's shared ids.

- [ ] Sanitize server response in metadata when an unpublished entity has been stored in a relationship field and is requested by a non-logged user.
- [ ] Ensure this procedure as well for elastic searches???

**Comment by RafaPolit** [comment]
ToDo's added to: #1530

**Comment by txau** [comment]
@RafaPolit for security reasons this should be addressed in server side.
