### ISSUE TITLE
Fix CSS for relationships tags

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1503]
![screen shot 2018-03-12 at 13 37 32](https://user-images.githubusercontent.com/489831/37284115-ac8be032-25fa-11e8-960d-832d96626cb6.png)

**Comment by danicatalan** [comment]
![1521123387](https://user-images.githubusercontent.com/6364153/37469067-c187b9cc-2864-11e8-85f5-db0267e4551d.jpg)

We need to double check this because the original branch doesn't have the latest updates from #1399.

In theory it should update with the new button because the Item component is isolated, but we should keep in mind this once the merge is done (anyway, if something fails it will be a quick fix).
