### ISSUE TITLE
Synchronize all metadata across languages on edit as option

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1511]
**How to replicate**

In a multilingual instance:
- Create a new entity with title and markdown.
- The entity is duplicated in all languages.
- Edit entity title and markdown in original language.
- The entity in other languages is not updated.

**Expected behavior**

In a multilingual instance:
- Create a new entity with title and markdown.
- The entity is duplicated in all languages.
- Edit entity title and markdown in original language.
- The entity in other languages is updated because it wasn't edited in the alternative languages.

**Comment by RafaPolit** [comment]
There is no concept of 'original language'. This is not how we address language fallback.

Our process should rather be called 'language on-creation fallback'.  That means that a document is created in all languages with the original data you entered (regardless of language).  After that, changes made to non-language-dependent  properties will occur on all languages (for example selects, or dates, etc.), and language-dependent properties (like title, text fields, etc.) will only get updated on the language you are in.

Maybe we need to change this approach, but what you are describing is not a bug, we have explained this before.

There is one exception to this rule: if you are working on the PDF and the same PDF is found on the other language versions (again, regardless of which is 'the original language', the rule is that they should match), then we extend TOC and Text References to all languages.

That's how it works.  If this needs changing, there is some further things to develop.  We haven't done this, because we agreed we should have a sort of medium ground between text-case fallback and full language separation for those instances that don't want fallback.

Maybe this has changed?

**Comment by txau** [comment]
@RafaPolit ok, i guess we need to discuss how we want it to work. Users expect to have a fallback language for all info, unless they want to translate it.

**Comment by txau** [comment]
@danicatalan @RafaPolit this is actually the exact same thing we have in attachments. Maybe, we should just add a "Add to all languages" check box?

**Comment by txau** [comment]
Another solution will be proposed to alleviate the burden of working in several languages.
