### ISSUE TITLE
Add a hint in metadata templates explaining that they already have title and date (anything else?)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#152]

**Comment by danicatalan** [comment]
- Title and upload date by default and stacked on the top.
- Add Icon/flag field support.

**Comment by danicatalan** [comment]
I've split properties in two different groups: default properties and custom properties. Both titles are rendered implicitly because maybe users get lost if they don't know why _Title_ or _Date added_ are there, but we can use a minimal approach with a thin divider between both groups and removing both titles.

![image](https://cloud.githubusercontent.com/assets/6364153/21776318/37d6ea58-d69a-11e6-9e31-1c7f6b605252.png)
![image](https://cloud.githubusercontent.com/assets/6364153/21776347/53abd5e0-d69a-11e6-9ae8-e7f541f33d85.png)

Default properties are not editable and sortable, so they are just plain HTML rendered above the custom properties. No need of any development phase to implement this.

We need to discuss how icon/flag is activated or not. I think the first approach we though (add a new property field) is wrong because each entity just have one icon or flag. Maybe we can add "active/inactive" support to default properties to manage that.

**Comment by txau** [comment]
- Icon/flag could be a property for the field title, since its always going to appear next to the title. We could add a special option to the title "Display and icon or flag with the title".
- I think we don't need to split properties in two groups. Just greying out the delete button should be enough.
- Default properties can be edited. The label can be changed.

**Comment by danicatalan** [comment]
All suggestions look good to me. This is related to #698, so we need to decide which goes first to avoid conflicts between issues.

**Comment by danicatalan** [comment]
![image](https://cloud.githubusercontent.com/assets/6364153/21897300/7c0d56d4-d8e9-11e6-9353-6dd1892b62c5.png)
