### ISSUE TITLE
Improvements to geolocation

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1614]
- On side panel and entity view, there is a weird glow icon behind the marker.
- Clicking on the "Map view" icon, should re-centre to default zoom and position.
- In wide screens, the map gets taller than the screen height. This creates some visual distress, I think this should fit in wide screens without scrolling. On the top of that, scrolling doesn't play well with maps (mouse wheel or two finger scroll zooms instead of scrolling). So lets try to avoid scrolling as much as possible.
- By default it loads without margin on the right, this margin reappears when resizing the window.
- The colors for the clusters are misleading. The information that they are representing (size of the cluster) is already represented by the size of the cluster. Since we are using a color code for representing the entities, its better to have the same color for all clusters.
-  I don't see how to fix the fact that many markers are placed at the exact same coordinates, there is no way of selecting different cases.
-  Not being able to click in a cluster to zoom in and split it into markers is counter intuitive.
-  The initial zoom should be bounding the existing markers.

**Comment by danicatalan** [comment]
### Points 3 and 4
Can we match the map styles from our design on AoT for all the Uwazi instances? Instead of having margins and relative sizes, make the map full screen: http://uwazi-design2.netlify.com/aot/projects

### Point 5: Agree. We should use a neutral color for clusters and the doc type color for single pins.

### Points 6 and 7: What do you think about click on a cluster shows all the items inside that cluster in the sidepanel? Same behaviour as multiselect in library. Also that interaction can be consistent in all zoom levels, don't need to implement a zoom-on-click and solve the problem when lot of pins are clustered in the same loc still on max zoom.

@txau @konzz

**Comment by txau** [comment]
@danicatalan @konzz that makes sense. Regarding points 6 and 7, the only problem is how to access the information of one particular case. Could we also modify the UI for multiple selection so that there is an option of expanding one of the matches?
