### ISSUE TITLE
judges/commissioners page on CEJIL not loading

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#1621]
Good peoples,
just noticed the judges/commissioners page on CEJIL instance, both on cejil.uwazi.io and sidh.cejil.org loads and flashes for a second and disappears...

**Comment by txau** [comment]
It loads correctly and then blanks out with this error.
![screenshot from 2018-05-09 08-00-47](https://user-images.githubusercontent.com/489831/39818855-23e6d452-535f-11e8-8650-3946a9199b72.png)

**Comment by RafaPolit** [comment]
This bug has been identified.

It was the introduction of the "missing" aggregations which created an error obtaining to which country belonged the "missing" value.

It is fixed in the PR.  The solution was to add the 'No Value' option to the countries as well.

There is an underlying problem that this issue has brought to light:  the Judges/Commissioners chart is, inherently, by country and by gender.  There are 15 judges / commissioners without country, and, of those, only one has gender.  So there appears only 1 commissioner with 'No Value' in the charts.

Cejil should add the country and gender to those judges missing for those charts to reflect the correct numbers.

**Comment by RafaPolit** [comment]
@txau please confirm that adding the 'No Value' as another country in the charts is the correct approach for this?  I think it helps expose the missing properties, but could add noise to the visual data.

**Comment by RafaPolit** [comment]
We are merging with the fix to prevent the page from breaking up.  If this solution is not ideal, we can find a better one down the road, but with the app up and running.

**Comment by txau** [comment]
@RafaPolit I think is a good solution, charts should reflect this kind of data to be faithful t reality. Let's wait for user feedback to see if we can improve this.
