### ISSUE TITLE
Review Vimeo margins on widescreen

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1686]

**Comment by txau** [comment]
On entity view, videos are rendered with unwanted vertical margins:

![screenshot from 2018-09-15 09-28-34](https://user-images.githubusercontent.com/489831/45583856-d1a52b00-b8c9-11e8-8701-9feb666fa305.png)

**Comment by RafaPolit** [comment]
This only happens for non 4:3 aspect ratio videos.  It appears the media plug-in is leaving a 4:3 space for every media.  In YouTube this is masked because YouTube adds black bars to top and bottom, but is also a problem.

I think this needs to be reported to them as a bug and, perhaps, try a PR with them and the video's native aspect ratio.

**Comment by txau** [comment]
Fixed:

![Screenshot from 2020-03-18 13-23-31](https://user-images.githubusercontent.com/489831/76999057-b3374a00-691b-11ea-97eb-344cfbaa1869.png)
