### ISSUE TITLE
protect uploaded files in private instances.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#1781]
all instances have /uploaded_documents path available, we should not allow this on private instances.

**Comment by RafaPolit** [comment]
This has been implemented in the PR.  There are some notes that are important to take into account:
- while uploaded_documents is configured as static within the server, it still goes through the middelwares, so it can be catched there for convenience (this has been implemented)

I am creating a new issue regarding the use of the route uploaded_documents: the original conception of this path is configurable through the UPLOADS_FOLDER process env.  Yet, the value is used as string throughout most of the app instead of the uploadDocumentsPath and attachmentsPath variables configured in app/api/config/paths.js.

See issue #1833
