### ISSUE TITLE
Improve how clear images are rendered in Custom Uploads

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1784]
If uploading a clear PNG:

![image](https://user-images.githubusercontent.com/6364153/42558457-973a0bb8-84f1-11e8-8a71-5c9184bbda4e.png)

Adding a hover effect will fix that (example: Windows interface)

![image](https://user-images.githubusercontent.com/6364153/42558536-d7abd3c0-84f1-11e8-9cb5-dfc4c7ab9798.png)

**Comment by simonfossom** [comment]
I wouldn't solve it like this. This is not really a solution in my opinion because when viewing (without interacting with a mouse - for example on a phone) this won't work. 

Good solution would be to check the color-scale and if it's on a lighter spectrum (not including transparent parts)put background black (or dark grey).
