### ISSUE TITLE
Connections are rendered differently depending on the language

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1791]
Observe the differences in these screenshots (the totals in the filters in the side panel). This may be related to https://github.com/huridocs/uwazi/issues/1747

![screenshot from 2018-07-13 16-51-47](https://user-images.githubusercontent.com/489831/43602088-39869aae-968f-11e8-8e77-2018d882808b.png)
![screenshot from 2018-07-13 16-51-37](https://user-images.githubusercontent.com/489831/42717273-2506697e-86bd-11e8-8b61-e65c1b5df442.png)
![screenshot from 2018-07-13 16-51-21](https://user-images.githubusercontent.com/489831/42717274-25236682-86bd-11e8-8b98-89c72e2183e8.png)

**Comment by RafaPolit** [comment]
The issue that produced this ghosts has been identified and described in #2055 .

A migration has been created that does the following:
- Deletes any relationship that has not a sharedId for each and every language in the DB.  This has changed to the discussed 'reconstruction' discussion, as it is now clear that inconsistencies are due to the fact that someone has deleted those relationships.
- Keeps TEXT references intact... it won't delete a reference that exists only on a single language.
- After this purge, it deletes all hubs that may have been rendered useless by the relationships migration.  Any hub that has a single entity connected in all its languages, gets deleted.  If, in some language, there are multiple entities in the hub (due to text references) it keeps the hub.
