### ISSUE TITLE
Admins should be able to configure the available languages from settings

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1846]
This probably needs supporting scripts to add/remove languages to the database, particularly when there is information already loaded.

**Comment by txau** [comment]
@vasyugan this issue is in sprint and will be merged soon fixing your problem. It provides an interface for configuring languages and its possible to add languages even if you already have some information. I hope we can finish and merge it either this week or next week.

**Comment by vasyugan** [comment]
@txau thanks. Where is it currently being configured? Because I don't recall being presented any language options during setup. Also where is the info stored? In mongodb or some other place?

**Comment by vasyugan** [comment]
Would really be cool, if it could be ready before the 24, because that's the day when we will have a workshop in Geneva with indigenous representatives from Asia and Latin America, where we should present a first prototype. Not far from the Huridocs office, btw.

**Comment by konzz** [comment]
Hi @vasyugan, I'm currently working in this feature, and yes it will be ready before the 24th. Right now the UI does not have a way to configure them but soon will be in the new section Settings>Languages. Since we have all the content in all the languages that an instance has configured, the process to add or remove languages is more complicated than just add them to the list in the database. Once we finish and deploy this feature will be as easy as clicking add in the desired language. I hope this answers your questions

**Comment by vasyugan** [comment]
@konzz Thanks, awesome. Just one question: Where or how is the initial language configuration supposed to take place in the current version? Because after running yarn run-production and yarn blank-state, when I start with an empty database, at no point am I prompted to choose languages. Or is it an undocumented parameter passed to yarn?

**Comment by konzz** [comment]
@vasyugan Right now is set to English with, and there is no way to configure it, at the moment, when an instance needed more languages we added them to the database "manually"

**Comment by konzz** [comment]
@vasyugan The feature is done, but it depends on another issue, we estimate that it will be finished in a couple of days, but if by thrusday is not done, I help you to configure a multilingual Uwazi

**Comment by konzz** [comment]
@vasyugan the new feature has been merged, please update your code and tell me if you have any problems. I'm closing the issue so you can just reopen it or create a new one with the issue.

**Comment by vasyugan** [comment]
Actually I just updated uwazi and ran yarn reindex. I can't find language settings anywhere. Where should they be? Do I need to track git master to get it?

**Comment by vasyugan** [comment]
> @vasyugan the new feature has been merged, please update your code and tell me if you have any problems. I'm closing the issue so you can just reopen it or create a new one with the issue.

What do you mean by "update the code" other than running "git pull", running yarn migrate and yarn reindex? Because after doing this, I can't seem to see anything new.

**Comment by konzz** [comment]
@vasyugan There should be a new section in settings "Languages"

**Comment by vasyugan** [comment]
Am Donnerstag, den 22.11.2018, 12:56 +0000 schrieb Alberto Casado
Torres:
> @vasyugan There should be a new section in settings "Languages"

For now, there is not.
Do I need to pull the code from a specific branch to get the
functionality?

**Comment by konzz** [comment]
I usually do, git checkout development and then git pull, also, it will be merged to master, but probably next week

**Comment by txau** [comment]
@vasyugan its merged to master as well

**Comment by vasyugan** [comment]
> @vasyugan its merged to master as well

Thanks, it turns out that the dockerfile I was using checked out the wrong branch.
Now the setting is there. 
What surprises me: When I add a new language and switch to it, the interface remains entirely in English. When I go to translations, I see that all languages contain just the English strings for everything. Does one have to translate everything from scratch? 

After all, there are some multilingual Uwazi installs out there. Aren't there locale files available somewhere?

**Comment by txau** [comment]
@vasyugan sorry about that, not yet there =)

**Comment by vasyugan** [comment]
> @vasyugan sorry about that, not yet there =)

OK, good to know I am not missing something. But are you working on that? After all, there are well established mechanisms for internationalisation, with GNU gettext and friends..
