### ISSUE TITLE
Fix Edge browser issues

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#1883]
While generally it works fine, there are a couple of bugs preventing Uwazi from being usable on Edge.

**Comment by RafaPolit** [comment]
Anything more specific?  I'm going to start browsing around, but it would be useful to know which actions or pages are not working as expected.

**Comment by RafaPolit** [comment]
This is an issue with variable scopes in the webpack / uglifier procedure.  It may get fixed with a version upgrade of webpack, but upgrading the uglifier version yielded errors still.

Unfortunately, any work around inside the code to this problem results in an infinite loop which also makes edge unresponsive.

This needs to be looked into at later stages when we are able to upgrade webpack.
