### ISSUE TITLE
Backup, restore, migration

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#1988]
Uwazi should either have a mechanism for backup and restore or there should be clear instruction on backup and restore. It is sufficient to generate / restore a database dump and take a copy of the uploaded documents directory?

**Comment by txau** [comment]
@vasyugan that is correct. With the db dump and the uploaded files contents youhave a full backup.

The only detail is running a "yarn reindex" after restoring the database. 

It's also convenient to run a "yarn migrate" before the reindex, since you may be restoring your data into a newer Uwazi with some data structure change.

I'm going to document this.

**Comment by txau** [comment]
https://github.com/huridocs/uwazi/wiki/Backup-and-restore
