### ISSUE TITLE
"No common filters" - Can't filter by propertes

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2022]
Whatever document type I click in the filter area, I always get the response "no common filter", even though documents are actually categorized by country, date etc. So I never get to filter along the individual properties that come with the document types.  And I get this "no common filters" response even when I click only a single document type. How can it be that a document type doesn't even have properties in common with itself?

**Comment by vasyugan** [comment]
We have more than 70 documents uploaded to our Uwazi install, most of them at least categorized by country.

**Comment by vasyugan** [comment]
misunterstood something..

**Comment by txau** [comment]
@vasyugan maybe this is yet another properly documented feature. The idea behind "Common filters" is to encourage admin users unify the naming for their filters and properties. So the criteria for Uwazi for filtering two different templates together (ie, because both have the property "Country") is:

- They both have the same property name
- They both have the same property type
- If its a thesauri based property, they both use the same thesaurus
- If its a relationship based property, they both use the same relationship type

**Comment by txau** [comment]
Here is an example on how it looks like (sorry Spanish):

![screenshot from 2018-10-17 15-09-07](https://user-images.githubusercontent.com/489831/47088901-dab64e80-d21f-11e8-960b-16d369aa22d6.png)
