### ISSUE TITLE
syncing log

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2110]
log all modifications into the database to be able to sync the data into another uwazi instance

- [x] sync thesauris
- [x] sync connections
- [x] sync translations
- [x] sync files (upload main file)
- [x]  only sync white listed.
- [x] migration of initial data
- [x] make user and password configurable from settings
- [x] Languages???? Settings in general have been excluded, what happens with this?
- [x] Discuss if partial updates throughout, or if on specific scenarios?
- [ ] What happens to the original blank state?  Since there is one, a default 'document' template is found, a single english thesauri that could be duplicated, etc.  This needs to be addressed.  Could be initially done by hand, deleting those two things, but in the long run it needs to be solved.

**Comment by RafaPolit** [comment]
- The "only sync whitelisted" is 'intelligent' and, if you whitelist templates... entities and connections are also included.  This could be changed to be more 'specific' and nothing 'derived', someone may not want connections, for instance.  Discuss this furhter!

**Comment by RafaPolit** [comment]
thesauris are now synced via the templates configuration:
if you configure to include a template and a property of that template which is a 'select' or 'multiselect', the 'Content' field of that property whitelists that particular thesauri.

The nice part is that this allow to include only thesauris that are 'whitelisted' through the template config, but if a property of another template uses the same thesauri yet belongs to a field you don't want included, the field is omitted.  Still, that thesauri does get synced.

This solves a lot of conflicts one could get by configuring the thesauris alone.

**Comment by RafaPolit** [comment]
Connections are synced through two configs:
- If you pass a relationtype ID, all the connections from that type will be included.
- If you whitelist a relationship property from a template, then there will be an attempt to include the relevant connections to secure that metadata information.

Still, due to the nature of connections, specially metadata created relationships, it is not possible to infer with complete certainty which were the connections created by the metadata if there have been manual modifications later.  So the template method is not 100% efficient.

The relationtype approach is more predictable, but there is a caveat:  every relationship is made up from two connections.  If you include only one type and fail to include the other, you will end up with single hub connections that will show nothing on to the viewer.

Connections are tricky and this is probably where most work should go in future iterations of syncing.

**Comment by RafaPolit** [comment]
Translations are fully automated through other configs, no specific translations config is needed for the translations to be synced.

**Comment by RafaPolit** [comment]
Languages are synced, this needs to be checked that some changes do not override others (confirm that we are doing partial updates)... but this brings the issue: what happens when we DON'T want partial updates?

**Comment by RafaPolit** [comment]
Migration is finished with a particular order defined.  Some database records and procedures require that others exist beforehand.  This wont be a problem during normal operation, but during the first sync it could be an issue.  Discuss this a bit further with @daneryl

**Comment by RafaPolit** [comment]
We have found several problems with deletions.  Perhaps a more thorough testing regarding this is required?  We have tested deleting entities, relationships and templates.  All these are now working.  Still, deleting thesauris or template properties should be tested.

@daneryl has talked about doing an automated e2e testing of this whole development.  It would help a lot in the long run.

**Comment by RafaPolit** [comment]
"username" and "password" are now accepted as sync keys to configure the username and password that are to log into the slave instance.
