### ISSUE TITLE
Allow sorting in thesauri

### ISSUE THREAD

**Issue by bertver** [huridocs/uwazi#2126]
in entities, I can sort items by drag and drop. This is not possible in thesauri but would often be helpful (for example, I want the list to be alphabetic but have "Other" and "Unknown" at the end of the list).

**Comment by txau** [comment]
Now thesauri support ordering the items via drag and drop. Next step to achieve this functionality would be displaying the user configured sorting in:

- Multiuselect and select in forms
- Filters in library

Please note that library filters have two modes, when folded they display the top categories and we should keep that. The user selected sorting should be only available when unfolded.

Also this may have a side effect since relationship fields options can't be sorted by users, so we should keep the default behavior (top categories when folded, alphabetical sorting when unfolded)

**Comment by habbes** [comment]
@txau clarification regarding the behaviour of when filters are folded. If it there are 5 items visible and 2 are selected, the selected ones should be displayed first (should they still be in alphabetical order?). The remaining 3 should be displayed after (should these be in alphabetical order as well?).

**Comment by txau** [comment]
@habbes not sure. What do you think? This is not for filters but for multiselect fields, right?

**Comment by habbes** [comment]
@txau yes, multiselect fields. I'm not sure which is more intuitive. I assume there's no reason for the user to expect the items to be sorted alphabetically when the field is folded. So maybe it makes more sense to keep user-defined sorting even when folded, while still hoisting the selected items at the top.

They are both equally easy to implement at this point.

**Comment by txau** [comment]
@habbes I agree. Go for it =)

**Comment by bertver** [comment]
@txau and @habbes has this already been deployed in all instances?

**Comment by txau** [comment]
@bertver it should be deployed now
