### ISSUE TITLE
Error when publishing an entity after I changed the coordinates

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2217]
I'm trying to create an "act" entity with a geo location on hr-reports.uwazi.io, but the coordinates I entered were not the right ones. When I tried to delete those coordinates, I was unable to publish the entity. I received this error:

![image](https://user-images.githubusercontent.com/354426/53960759-18275580-40b5-11e9-9159-96cfedd8ddd6.png)

Also, when I tried to type numbers into the first coordinates field, a white screen appeared and I couldn't do anything.

**Comment by habbes** [comment]
@kjantin I've not been able to reproduce the errors.
How did you attempt to delete the coordinates? Did you try to place a marker at a new location, or enter new values directly in the latitude/longitude fields or remove the values that were there before?

**Comment by habbes** [comment]
@kjantin I've been able to reproduce the errors by deleting the values in the latitude and longitude, leaving the fields empty, and then try to save. This results in an error because it doesn't delete the geolocation field, but tries to save it with empty lat and lon values, which is not allowed.

So I think the solution is to provide a way to remove the field.

**Comment by txau** [comment]
@habbes how does the field handle empty values on the first place? maybe we should convert empty strings to null or similar?
