### ISSUE TITLE
Thesauri validation error

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2222]
the error message attached pops up when I try to publish an incident. The error occurs for a Select field for which no value has been selected. When values have been selected for all Select fields the error does not occur.
![Screenshot_2019-03-11_at_13 57 11](https://user-images.githubusercontent.com/489831/54129432-80a46880-440e-11e9-9589-f499d85ce6c7.png)

**Comment by habbes** [comment]
Seems to be failing because sometimes when you publish/unpublish it tries to save the entity with `null` for the select fields without values, other times it uses empty strings, in which case no error occurs.

If I remember correctly, we should not allow `null` as field values, right? So I should not just allow `null` in the validation, correct?

**Comment by konzz** [comment]
@habbes I think an empty string is wrong for select values, the correct should be null when you don't select anything. Why do you think that we should not allow null when there is no value ?

**Comment by habbes** [comment]
@konzz, it must have been a misunderstanding from my part.
Indeed empty select fields have `null` as the value in the database. So the UI makes requests using empty strings, but the API stores `null` and returns `null`, but `null` was not allowed in the validation, so publishing/unpublishing a document returned from the API was causing the error.

**Comment by txau** [comment]
@habbes looks like this issue can be closed?

**Comment by habbes** [comment]
@txau yes. The PR was merged.
