### ISSUE TITLE
Insufficient document validation

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2224]
Uwazi does not sufficiently validate documents by their type and mimetype. In effect, Uwazi does not
restrict the type of documents that can be uploaded by a user with editor privileges. However, some
file content (such as HTML and JavaScript) is inherently dangerous because it may be rendered in the
user’s browser.

**Comment by habbes** [comment]
Instead of adding validation on the documents, we had decided to not provide the user direct access to the document's main file or its attachments. The user should not be aware of the internal filename used to store the files on disk.

**Comment by habbes** [comment]
Working on this, I've modified the document downloads endpoint to require the attachment id instead of its unique filename. Furthermore, I've also tried to prevent leaking the filename in results. I did this by setting the Entity schema to exclude filenames from results by default. And then I would selectively include the filenames in internal queries that need them, without letting them getting transmitted to the client.

**Comment by habbes** [comment]
However some issues have come about as a result of trying to protect the filenames:
- A lot of the code in the backend that required the filename has had to be adjusted. This may lead to potentially introducing new bugs in case I make the wrong adjustments or in case I don't make adjustments in cases where it was required. I've been relying on failing tests to know which areas to update. I think this requires a thorough review to ensure everything works correctly. I recommend that emphasis be placed on reviewing document uploads, downloads, updates, relationships as well as synchronization
- Because the filenames are not included in the entity sent to the client, when an entity is updated, the payload sent to the server also does not include the filename property. And because the updated version overwrites properties of the existing version in the database, it leads to the entity in the database losing the filename properties (both in the main file and attachments) and then downloads start failing after that. This happens when updating the entity metadata as well as renaming its files. I've patched this issues in some endpoints using the `entity.save` method by injecting the filename from the database into the payload before saving it. But still not patched it on the `entity.updateMultiple` method.
- I've found that relationships also leak filenames. So this has to be protected as well.

**Comment by habbes** [comment]
It seems like the approach requires more effort than required, can potentially introduce new bugs and also requires that we ensure entity filenames are never leaked in any API responses. So I just wanted to confirm whether this approach is the way to go.

**Comment by daneryl** [comment]
@txau, @habbes, at this point maybe we are better not allowing access to uploaded_documents/ and upload custom files into another folder ? as originaly thought ?
