### ISSUE TITLE
Some labels for entity type are not legible: White letters with white background

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2235]
When creating entity types, uwazi seems to randomly assign background colours to their labels, and one of them is white which ends me up with seemingly empty labels, with white text on whit background
![Screenshot_2019-03-14 Library • FPIC](https://user-images.githubusercontent.com/3313208/54370166-c9416900-463c-11e9-850d-5f14ea6e66e2.png)

**Comment by txau** [comment]
@vasyugan this is the first time it happens. I guess that means you have more than 18 templates. The plan is to let users set their own colors rather than from a predefined list. Meanwhile, since you are on a custom install, maybe you can define your own color as a short term solution: https://github.com/huridocs/uwazi/blob/development/app/react/App/scss/elements/_controls.scss

**Comment by vasyugan** [comment]
OK, thanks, will look into this.

**Comment by txau** [comment]
Same as: https://github.com/huridocs/uwazi/issues/1338
