### ISSUE TITLE
Items being duplicated in thesauri

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2240]
Playing around with groups/items in thesauris can eventually duplicate entries. In the screenshot, Item 2 got duplicated after a combination of moving items inside/outside of the group:

![Screenshot from 2019-03-15 11-09-26](https://user-images.githubusercontent.com/489831/54424275-d3359b80-4712-11e9-874d-82f62cdb33bf.png)

More over, the way the items are stored in the database is not consistent for _id, ObjectId:

![Screenshot from 2019-03-15 11-07-32](https://user-images.githubusercontent.com/489831/54424365-0710c100-4713-11e9-8914-2636e72fe160.png)

**Comment by habbes** [comment]
So I've noticed those issues occur when the group is the first item in the thesauri list. I think I've found the culprit code, and it's a quick-fix.

However, I've seen other issues as well:
- When you click the check icon of an item inside a group, it's not highlighted even though the item becomes selected
- There seems to be issues when deleting items inside a group. Sometimes they don't get deleted and it's items outside the group that get deleted. I'm not sure whether this bug is related to the first

**Comment by txau** [comment]
@habbes great. Please see these things fixed. Make an automated test when possible.

**Comment by habbes** [comment]
I've fixed the issues and added tests in this PR #2258

**Comment by txau** [comment]
I added a few comments con the PR. I guess the main bug is fixed with this PR, but there is another but when moving empty items to groups. Also I think we should switch the UX to grad and drop.
