### ISSUE TITLE
A weird icon appeared after the RTL merge

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2242]
![Screenshot from 2019-03-15 15-07-35](https://user-images.githubusercontent.com/489831/54437088-28ce7000-4734-11e9-8bc6-385de6d081d0.png)
![Screenshot from 2019-03-15 15-07-12](https://user-images.githubusercontent.com/489831/54437091-29670680-4734-11e9-94ae-2614f660e70b.png)

**Comment by RafaPolit** [comment]
To whomever fixes this: this appears to be an issue with the rw-widgets.woff and CORS policy
```
Access to font at 'http://localhost:8080/fonts/rw-widgets.woff?v=4.1.0' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8080/fonts/rw-widgets.woff?v=4.1.0:1 GET http://localhost:8080/fonts/rw-widgets.woff?v=4.1.0 net::ERR_FAILED
?q=(order:desc,sort:creationDate,treatAs:number):1 Access to font at 'http://localhost:8080/fonts/rw-widgets.ttf?v=4.1.0' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8080/fonts/rw-widgets.ttf?v=4.1.0:1 GET http://localhost:8080/fonts/rw-widgets.ttf?v=4.1.0 net::ERR_FAILED
index.es.js?942a:269 Could not find icon {prefix: "fas", iconName: "square"}
```

**Comment by habbes** [comment]
I have not had success with this yet:

@RafaPolit I think the fonts that cause the CORS error come from the react-widgets package.

On the local dev server, they're fetched from `localhost:8080` for some reason, instead of `localhost:3000` which causes the CORS error.

However, on the production server, they are fetched from the same domain as the server. But they still return a 404. Example: `https://zorlakaytest.uwazi.io/fonts/rw-widgets.woff?v=4.1.0`

I think the inconsistent behaviour on the dev server is due to the webpack hot reload server, it seems configured to listen on port `8080`. But I don't know why the font requests from react widgets are routed there.

The [react widgets docs]() advise adding the following snippet in your sass in order to help webpack find the image and font folders.

```
$font-path: '~react-widgets/lib/fonts';
$img-path: '~react-widgets/lib/img';

@import '~react-widgets/lib/scss/react-widgets';
```

I tried adding that to the `styles.scss` file and reran `yarn hot`. That caused the server to crash on a segmentation fault:

```
webpack building...
/var/folders/ww/ks7kzcd117g8l08qpf_vqs4m0000gn/T/yarn--1556875419863-0.9630521583826381/node: line 3: 58785 Segmentation fault: 11  "/Users/habbes/.nvm/versions/node/v8.14.0/bin/node" "$@"
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! Uwazi@1.4.1 webpack-server: `node ./webpack/webpack.server.js`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the Uwazi@1.4.1 webpack-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/habbes/.npm/_logs/2019-05-03T09_27_33_956Z-debug.log
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by habbes** [comment]
I've added a simple middleware to the webpack.server to fix the CORS error:

```
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  next();
});
```
The strange thing is that it seems the `webpack-dev-middleware` is configure to set this header, but for some reason it's not.

Anyway, the CORS error is now gone, but still getting a 404 cause the font can't be found at `http://localhost:8080/fonts/rw-widgets.woff?v=4.1.0` .

**Comment by txau** [comment]
Regading the CORS issue in development env, since the HMR is an express app, I fixed it by adding the cors module since this does not pose a security concern in dev env:
```
const express = require('express');
const app = express();

var cors = require('cors');
app.use(cors());
```
The actual bug is due to the inability of MiniCssExtractPlugin to process certain URLs. After trying several potential fixes that didn't work, I propose a workaround for these particularities by using the plugin CopyWebpackPlugin:
```
new CopyWebpackPlugin([
        // {from: 'node_modules/react-flags/vendor/flags', to: 'flag-images'},
        {from: 'node_modules/react-widgets/lib/fonts', to: 'fonts'},
      ]),
```

**Comment by txau** [comment]
Fixed
