### ISSUE TITLE
Text extracted from PDF without spaces

### ISSUE THREAD

**Issue by vasyugan** [huridocs/uwazi#2257]
For some documents, referencing paragraphs gives unexpected results, the resulting quotes contain no spaces and is therefore very hard to read.

![Screenshot_2019-03-20 Assertion of rights in relation to natural resources • FPIC](https://user-images.githubusercontent.com/3313208/54680007-0314e280-4b09-11e9-9487-ea93298998e1.png)

**Comment by txau** [comment]
@vasyugan yes. This is a recurring issue. I think we are going to invest a whole development cycle in improving text tools, since as you said, its one of the main focus points of Uwazi.

This was already reported here as well: https://github.com/huridocs/uwazi/issues/1645

The solution is tricky, it has more to do with how the PDFs are created than Uwazi it self. Still, I think we need to take conduct a deep research and see how we can mitigate this issue.

**Comment by vorburger** [comment]
Assuming they are public, would you be able to post links to a few example problematic PDFs here?

**Comment by txau** [comment]
@vasyugan this has been stale for a while. I'm going to close ti for now while leaving you the decision to reopen. It would be great if you can test it by trying to copy paste that same text from the PDF directly with your regular PDF editor and check if it has the same results.

From my own experience, this is more related to how the PDF was encoded. Also, some readers already implement strategies to mitigate this, so the results may be different depending on the readir you are testing.

Alternatively, point us to some public link were we can download the file for testing.

Thanks!

**Comment by vasyugan** [comment]
Sorry, I saw your responses too late. So I have tested it now, and 

[60050046-Ki-Protocols v2.pdf](https://github.com/huridocs/uwazi/files/4374903/60050046-Ki-Protocols.v2.pdf)

Here is what the reference in Uwazi looks like:

![grafik](https://user-images.githubusercontent.com/3313208/77420222-f08f5200-6dc9-11ea-95d9-13cdc6080633.png)

This is how the text extracted by Adobe Acrobat looks like: 

The Parties direct that if the members of the Consultation Committee agree that a
facilitator would be helpful in their efforts to reach consensus on their
recommendations, a facilitator agreeable to all will be engaged and paid for by
Ontario and/or the Proponent.

@txau I have no option of re-opening this. Probably reserved to members of he organisation

**Comment by txau** [comment]
@vasyugan thanks so much. I'll take a look to the file.

**Comment by txau** [comment]
@vasyugan I've been running a lot of tests with your file and while I can't provide a detailed explanation of the source of the problem, I have a solution.

The problem seems to be how each PDF reader interprets fonts and spacing. Normally this is done via internal heuristics and sometimes you can control word break spacing, sometimes you can't. In the case of PDF.js this is not possible. That is also the case for ghostscript, so a conversion to text with `gs -sDEVICE=txtwrite -dBATCH -dNOPAUSE -sPageList=2  -sOutputFile=output.txt bla.pdf` (only page 2 of your file with GS 9.50) tosses something like this:
```
  INTRODUCTION
       Thefollowingobjectiveshavebeenadoptedindesigningtheseprotocols:
       TheprotocolsareconsistentwithexpressedKitchenuhmaykoosibInninuwug
       values, goals, and vision for the homeland.
       Theprocessforconductingmeetingsanddevelopingresponseswithin
       KitchenuhmaykoosibInninuwugshouldbesystematicandproduceconsistent
       responsesovertimeforsimilarapplications.
       Responsesshouldbebaseduponallrelevantandreliableinformationconcerning
       theapplication and its environment setting, including traditional knowledge and
       ecological knowledge.
       Theprocessshouldbeefficientandeasytoimplement.
       Responsesshouldbeproducedinatimelymanner.
       Positions taken in the responses should be transparent (i.e. supported by facts
       andanalysis).
```
On the other hand Poppler seems to handle this properly, so `pdftohtml -f 2 -l 2 -xml -wbt 20  bla.pdf bla.xml` outputs:
```
<text top="376" left="108" width="654" height="21" font="2">The protocols are consistent with expressed Kitchenuhmaykoosib Inninuwug</text>
<text top="405" left="108" width="363" height="21" font="2">values, goals, and vision for the homeland.</text>
<text top="450" left="108" width="599" height="21" font="2">The process for conducting meetings and developing responses within</text>
<text top="479" left="108" width="662" height="21" font="2">Kitchenuhmaykoosib Inninuwug should be systematic and produce consistent</text>
```

Which is desirable, whereas tweaking the -wbt param (word break threshold) can also yield wrong results, ie `pdftohtml -f 2 -l 2 -xml -wbt 26  bla.pdf bla.xml`:
```
<text top="376" left="108" width="654" height="21" font="2">TheprotocolsareconsistentwithexpressedKitchenuhmaykoosibInninuwug</text>
<text top="405" left="108" width="363" height="21" font="2">values,goals,andvisionforthehomeland.</text>
<text top="450" left="108" width="599" height="21" font="2">Theprocessforconductingmeetingsanddevelopingresponseswithin</text>
<text top="479" left="108" width="662" height="21" font="2">KitchenuhmaykoosibInninuwugshouldbesystematicandproduceconsistent</text>
<text top="509" left="108" width="377" height="21" font="2">responsesovertimeforsimilarapplications.</text>
<text top="553" left="108" width="693" height="21" font="2">Responsesshouldbebaseduponallrelevantandreliableinformationconcerning</text>
```
After many rounds of library testing and parameter tweaking I found a formula that actually fixes the PDF so it works properly both in ghostscript and PDF.js.

First sanizite and compress the file with [mutools' convert](https://mupdf.com/docs/manual-mutool-convert.html) with `mutool convert  -O garbage -O sanitize -O compress -o bla_clean.pdf bla.pdf`

This generates a file that already works nicely with PDF.js [bla_clean.pdf](https://github.com/huridocs/uwazi/files/6697992/bla_clean.pdf)

As an additional step, you can also optimize the file for web, which not only reduces the size but also reorders the PDF contents so it will load faster; with GS this time:

`gs -sDEVICE=pdfwrite -dBATCH -dNOPAUSE  -sColorConversionStrategy=UseDeviceIndependentColor -dEmbedAllFonts=true -dPDFA=2 -sProcessColorModel=DeviceRGB -dPDFACompatibilityPolicy=1 -dFastWebView=true -sOutputFile=output.pdf bla_clean.pdf` 

which reduced your file from 3.8MB to 264KB [output.pdf](https://github.com/huridocs/uwazi/files/6697997/output.pdf) and it is linearized (optimized for web).

Please note that if you have interest in preserving the original file intact (for archiving or chain of custody reasons) these steps create a new file with a completely new structure, so it is convenient to keep a copy of the old one. You can ie. leave the old one as a supporting file in Uwazi and use this one as the main file for online consumption.

On a side note, I'm not super familiar with all the GS options (-dPDFA=2, -dPDFACompatibilityPolicy=1) but I tried to make your file PDF/A compliant without luck so far (all text gets removed), so this requires further resarch. For the record I'm also looking into [VeraPDF](https://github.com/veraPDF/veraPDF-library) for accessibility and standards validation.

Sorry about the long answer, I'm using this thread as a log so maybe we can implement this as an Uwazi integrated feature so you and other users don't have to manually process the files. This of course requires more testing since this solution may be only working for your particular file.

I'm also trying to fix https://github.com/huridocs/uwazi/issues/1645 at the same time but it seems to be a different issue. We are also working on OCR integrated into Uwazi, which may help in some of these cases.

(I'll leave this issue open for team discussion).

**Comment by txau** [comment]
Fixed with the newest version of PDF.js, to be deployed soon.
