### ISSUE TITLE
super slow instance: tchrd.uwazi.io

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2265]

**Comment by daneryl** [comment]
@txau @RafaPolit @konzz 

this code is executed every time we query the translations from db to transform them,
https://github.com/huridocs/uwazi/blob/95e935a6bd51bab96fddd7b880feaee13fcbb841/app/api/i18n/translations.js#L5-L11

it takes in the case of tchrd 2.5 seconds, thats one of the bottlenecks we have, for searches particularly.
 options i can think of:

1- store in the database that same structure ? how will this affect everiting related to translations?

2- cache the translations on get and only reset the cache when they are updated so we have instant translations in the search process ?

3- try to make the code faster ? do not think is a good option, even on double the speed its still a lot for any search.

**Comment by txau** [comment]
@daneryl upfront option 2 sounds like a better solution, although I don't seem to see the difference with option 1.

**Comment by txau** [comment]
@daneryl also, is this affecting all instances? why is it that it only feels slow in tchrd?

**Comment by daneryl** [comment]
@txau it is affecting all instances, in this case its more relevant because the translation objects grow with templates and thesauri, they have here a 2k values thesauri, that is why in this case this process is more than 2 seconds, in the majority of instances its probably a lot less time, this is for all queries to search, including server side rendering of the home.

option 1 requires more work probably, but im not sure, instead of cache the result we will change the way translations are stored to the same structure they get transformed when requested from db, do not know if that is possible, was more a question to @RafaPolit and @konzz.

**Comment by konzz** [comment]
It would be great to implement 1. I think translations have undetected bugs since we have many reports of missing translations or similar but then we can never reproduce it, so I assume there are bugs for very specific steps. 

But option 2 has the same or even better results and is far more easy and fast to implement, and even if in the future we change the structure, have the translations cached is always good.
