### ISSUE TITLE
Relationship field shows unpublished entities.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2324]
The relationship field shows relationships with unpublished entities, and since it renders a link to those entities you can see all the info.

Inheriting information is based on this field, so anything related to inheriting would have this problem too.

related #2313

**Comment by habbes** [comment]
@konzz Which of the two approaches is ideal:
- Stop displaying unpublished entities in relationships when creating/updating an entity? or
- Remove unpublished entities from relationship fields when fetching entities using an unauthenticated account

The first approach is definitely easier to fix (one line of code it seems), but it won't address existing instances that already have documents with relationship fields to unpublished entities. Also, when the client requests thesauri lists, it includes unpublished entities only if the request is made from a logged in user. This seems to be done intentionally. But I don't know why. Which is why I have doubts about using this solution.

The second approach seems harder and messier. I have not tried it yet. But I think it could also lead to incorrect aggregation counts.

**Comment by konzz** [comment]
The second one, remove them from the data that the server sends is the way to go since not displaying them is not enough because anyone can see the unpublished data in the request.

Obviously is harder, and not sure if it will affect the aggregations, since if you show a filter of that prop, the aggregation that could be "wrong" is the aggregation of the unpublished entity, and it won't be in the filter.

Go with the second option, and update me with any problems.

**Comment by habbes** [comment]
@konzz alright, let me try the second one and see how it goes. Thanks.

**Comment by habbes** [comment]
@konzz I think I phrased my question incorrectly. In both cases I was referring to the data sent by the server.

When the client fetches the thesauri lists, the server includes entities from each template. It includes unpublished entities only if the request comes from an authenticated user. The first approach I proposed to remove the unpublished entities from the results regardless of whether the user is authenticated or not.

What I meant by the second approach was to modify server methods that return entities, search as the `search` endpoint, and for each entity, I'd check all its relationship fields and remove any listed unpublished entities if any. (I'd have to make db requests to find out whether or not they're published).

Now that I re-read your comment, I believe my poor phrasing led to a misunderstanding. Given this new clarification, should I still go with the second option? Or did you mean the first option.

**Comment by habbes** [comment]
@konzz also, to prevent new entities being created with relationships fields to unpublished entities, I can add validation at the server level to endpoints that create entities. This is in case a script creates entities via the REST API directly, without having to go through the UI form.

**Comment by konzz** [comment]
I think we should discuss this problem with the whole team. Can you bring this in the next tech call? Because it's more complex than it seems.

**Comment by habbes** [comment]
@konzz I've created a PR [2419](https://github.com/huridocs/uwazi/pull/2419) implementing the first approach.

But you are right, discussing the issues with the whole team is a better idea.

**Comment by habbes** [comment]
@konzz @RafaPolit I have explored the side effects of unpublished entities in relationship fields and this is what I found:

Assuming an entity P has a relation field containing entity U as the value. P is published and U is unpublished.

## authenticated user
- U is listed in the P's metadata in the library sidebar when selected
- U is also listed P's metadata when P is viewed in its own page

## unauthenticated user
- U is not listed in P's metadata either in the library sidebar or in P's own viewer page
However, U's shared id is included in the JSON payload sent over the network when P is fetched. This may or may not be a problem. @txau suggested it shouldn't be a problem worth headaches.

So far this seems to work as intended, the unpublished entity is inaccessible to the public/unauthenticated user

## geolocation fields and property inheritance
If U has a geolocation field and P inherits that property, then there are a couple of issues that occur when the user is not logged in:

- U's location will appear on the inherited property's map when viewing P's page
- In the library map view, there will be a pin for U on the map. When you hover over the pin, the app will crash, presumably because it could not access the entity's metadata since it's not public. I think this is related to this issue: #2313
-

**Comment by habbes** [comment]
@RafaPolit I have also explored the case where the an unpublished entity has a relationship to a published entity, where the unpublished entity has a geolocation field inherited from the published entity.

There does not seem to be anything out of the ordinary. When the user is unauthenticated, the published entity is visible on the map and the unpublished entity is not. Furthermore, the unpublished entity is not displayed in the published entity's relationships. I believe this is the intended behaviour.

**Comment by RafaPolit** [comment]
Please then prevent geolocations to be shown for unpublished entities, in a way that users cannot see the geolocations by exploring the network requests in client.
