### ISSUE TITLE
Detect mimetype and whitelist allowed files

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2338]
Since we prevented direct access to uploaded files in order to avoid malicious content being opened directly in the browser, now self-hosted videos and audio won't be displayed in media fields.

In order to fix this issue without reopening the vulnerability, we could implement server side mimetype assignment along with whitelisting this kind of file so they can be embedded again.

**Comment by habbes** [comment]
@jaume I have a question regarding this.

At which point should we add mime type whitelisting? custom uploads or attachments?

Furthermore, I've tried to upload videos, both via document attachments and via custom uploads. In both cases, I've been able to add them to media fields and play them. So I'm not sure what the issue is.

**Comment by habbes** [comment]
@jaume I believe what we did was prevent direct access to the documents and attachment files, but custom uploads are still directly accessible. Attachments are also accessible through their own urls. When you enter these urls in media fields, it seems to work.

**Comment by txau** [comment]
This should be affecting only the uploaded documents (so we can leave custom uploads outside of this discussion). I test it by:

1. Add a video as an attachment.
2. Set the url to the video as the value for a media field.

This didn't work for me, it could be for several reasons:

1. The browser version ( I was on firefox if I recall correctly)
2. SInce you just updated the media library, maybe that fixed it.

Please note that is sort of worrisome if the videos are actually being embedded in the media field with the current setup. Remember that we patched the access to the uploaded documents to force download so they would never be directly opened in the context of Uwazi (to prevent XSS etc).

So make sure that the security vulnerability is still patched while embedding the video works for every browser. If that is the case, we don't need to do anything. Otherwise, we need to detect the mimetype and whitelist videos and pictures.

**Comment by habbes** [comment]
@txau seems to work on Firefox as well, maybe the particular issue about media fields not playing was fixed by https://github.com/huridocs/uwazi/pull/2346

When you open the link directly, the browser downloads it or, in the case of firefox, asks whether you want to open it with an external program or save it. However, when it's passed to the react media player component, it's loaded as a video (or audio, depending on the file type).

**Comment by txau** [comment]
@habbes good to know. So I guess we don't need to fix this. Thanks.
