### ISSUE TITLE
Improved image and media fields

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2366]
Currently users need to upload the image or media to attachments and manually paste the link in the field. It would be a great improvement to the UX adding an "Upload" button that is going to simplify these two steps while getting the same result.

**Comment by simonfossom** [comment]
Here's the [prototype](https://www.figma.com/proto/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=1359%3A3100&viewport=788%2C955%2C0.064594566822052&scaling=min-zoom) of a possible solution.

- links are 'attached' to attachments section 
- image/media in image/media fields can be selected from the dropdown from images/media that are attached
- on media fields timestamp+caption are exposed as UI.

**Comment by txau** [comment]
@simonfossom IMO this s not solving the most frequent use case that is uploading an attachment directly to the media field. WIth the approach you are presenting the user still needs to first add the attachment, then look it up on the select. Moreover, previously they had a quicker workflow when adding a URL, they just had to paste it on the field, now it is a multi-step process as well.

**Comment by simonfossom** [comment]
Sorry for the late reply. Thought we would talk about it on Wednesday.

I've designed that approach also but it turns out that it has a problem.
- user is not aware that the attachment is in the section at the end of the entity so he cannot remove it or edit it from that field
- user can accidentally delete an attachment that is used in some image/media field (still an issue)
- adding upload and link buttons clutters UI a lot. (not too big of an issue, but let's try to avoid it)

In this design user knows that upload/linking is always in attachments. This makes it more coherent and consistent: all attachments are in one place. And we keep minimal UI on the image/meida field: just one select.

This is not my first choice either, but with given constraints, I would recommend this one.

**Comment by simonfossom** [comment]
https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=1513%3A22

**Comment by RafaPolit** [comment]
Steps required:
-----------------------------------

- Rename Attachments to Supporting files?

-----------------------------------

- Attachments should be able to accept external URLs and know the difference between self hosted files and external references (they should render in the attachments pane correctly)
- Create the upload / external resource modal with only those two tabs

-----------------------------------------

- Upgrade the media property to only use entity's supporting files
- migrating existing media fields to supporting files and assign that id into the media field
- create the "select from files" tab to the selecting modal

-----------------------------------------

- Create the "upload and select" and "add resource" flow from the media field

----------------------------------------

- Create the upload supporting files flow to entity creation / editing

----------------------------------------

**Comment by txau** [comment]
Already done here #4071
