### ISSUE TITLE
Allow passing an arbitrary list of properties to charts

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2434]
Sometimes users want to display arbitrary properties, ie, for comparison, instead of top categories or all of them.

**Comment by RafaPolit** [comment]
The implementation of this feature is about to be implemented for the `BarChart` component.

The attribute is called `pluckCategories` and it takes a valid JSON array of category names or labels.
```
<BarChart ... pluckCategories='["UN", "NATO", "WHO"]' />
```

This allows to hand-pick which columns to display.  For example, if you have years on the X axis, you may be interested in seeing the progress in each decade change, instead of every year.  For this, you can ask for just `pluckCategories='["1990", "2000", "2010", "2020"]' `.  This will omit all the values in between.

It is possible to force a particular order of columns instead of sorting them by one of the other available methods (by label or by result).  To accomplish this, just put the plucked categories in the order you want them to appear and combine with the attribute `sort='{ "by": "none"}'` as described in #2839.
