### ISSUE TITLE
Highlighting is too faint 

### ISSUE THREAD

**Issue by OzrenMuic** [huridocs/uwazi#2486]
Reference highlights are too faint.

This is how it looks like now:
![image](https://user-images.githubusercontent.com/8134850/63433099-cd12bc00-c422-11e9-903f-42189e054fee.png)

This is how it should look:
![image](https://user-images.githubusercontent.com/8134850/63433151-eae02100-c422-11e9-8238-40cab511102f.png)

Not sure how this highlighting is implemented now, but if we use CSS, it might be best to use _blend mode darken_.

Here are some links explaining this in more detail:
- https://alligator.io/css/exploring-blend-modes/
- https://css-tricks.com/methods-contrasting-text-backgrounds/

**Comment by RafaPolit** [comment]
Precisely, the problem was that this highlight is composed on top of the text.  So the denser the background gets, the more faint the text will look.  If there is options to do complex blending like described above, that would solve a good amount of our problems! Great find!

We are, obviously, assuming text is always black on white.  If someone has "designed" PDFs, there are use cases where this probably wouldn't be ideal.  But it's a good compromise.

Any idea how this fallback on browsers that won't necessarily support this? Still, great to have blending modes as an option!

**Comment by OzrenMuic** [comment]
I'm not sure how our user group keeps up to date with modern browsers, but I think this just might be a good fit:
![image](https://user-images.githubusercontent.com/8134850/63446861-40c0c300-c43b-11e9-825b-7af573366827.png)
([Source](https://caniuse.com/#feat=css-backgroundblendmode))

**Comment by MatelSow** [comment]
@OzrenMuic IHRDA has signaled this issue to us as well. Highlights are barely noticeable:

![Screen Shot 2019-11-05 at 11 36 29 AM](https://user-images.githubusercontent.com/56391759/68218063-06030b80-ffe4-11e9-9f65-2edcb4306562.png)

**Comment by OzrenMuic** [comment]
I've proposed solution to this.
@RafaPolit what can we do here?
