### ISSUE TITLE
Proposal for relationships icon 

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2519]
Currently `Link` and `Relationships` have the same icon. It's important to change this because, when user enters title, he can't tell the difference between these two types of metadata. 

![image](https://user-images.githubusercontent.com/8134850/64640575-910fbd00-d40a-11e9-828b-cd69f3c044a7.png)

To distinguish better between them, here are proposals for different icon:

<img width="773" alt="Screenshot 2019-09-10 at 20 22 29" src="https://user-images.githubusercontent.com/8134850/64640417-370ef780-d40a-11e9-9acc-4db3f4c37423.png">

**Comment by txau** [comment]
@OzrenMuic are this from font awesome?

**Comment by OzrenMuic** [comment]
No, I've drawn all of them.

I guess I've nailed same rounded corners as they have. :)

**Comment by kjantin** [comment]
I think it makes perfect sense to use that middle one, because it's also what we use for the "Connections" tab .
![image](https://user-images.githubusercontent.com/354426/64676728-7f63ff00-d476-11e9-80b9-8fbcc0da49ea.png)

I also like the third icon - to me it represents the concept of the "relationship hub". So maybe when we figure out how to improve the UI around the hubs, this will come in handy.

**Comment by txau** [comment]
@OzrenMuic so far we have been sticking to font-awesome's icons for the sake of simplicity, but I don't mind breaking that tradition. @RafaPolit @daneryl do you think that is going to be a problem?

**Comment by OzrenMuic** [comment]
We can use this one:
https://fontawesome.com/icons/exchange-alt?style=regular 
it's close enough to the middle example.

❤️ Font Awesome ❤️
