### ISSUE TITLE
Move Uwazi user guide to ReadtheDocs

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2601]
The Uwazi user guide currently lives on the wiki of its github repo https://github.com/huridocs/uwazi/wiki. A big reason for this change is to allow users to easily download the guide for offline use. 

From ReadtheDocs site:

>Of course we build and host your docs for the web, but they are also vieweable as PDFs, as single page HTML, and for eReaders. No additional configuration is required. 

https://readthedocs.org/

**Comment by MatelSow** [comment]
Another good use of the download option would be for translations of the wiki. it's much to easier on 1 document than to copy/paste sections from Github.

**Comment by whyfrycek** [comment]
Another option could be to use something like Gitbooks to generate things off the wiki: https://www.gitbook.com/

**Comment by fnocetti** [comment]
I have a Read the docs set up working on a branch. The account is associated to my GitHub account. Can give access to whoever needs it.

I included the docs from the uwazi wiki which are working but need to be updated and have their structure adapted.

cc: @kjantin @txau

**Comment by kjantin** [comment]
Hi @fnocetti is it possible to work towards our documentation to look like this https://docs.mattermost.com/ (they are using readthedocs with another theme).

**Comment by fnocetti** [comment]
@kjantin we should be able to implement something similar, but it will require some dev work (that I cannot estimate right away).
They're actually using the default theme with customizations on top.
I think that if we want to go with something really customized on our docs instead of just migrating our docs to the default RTD setup we should plan dev resources to get something ready.
Let's discuss it offline.

**Comment by kjantin** [comment]
We have made the decision to use ReadtheDocs because:

1. It will allow users to download the guide in different ways (PDF, .pub, etc), with little effort from our side. 
2. It will allow us to manage translations of the user guide. 
3. It will allow us to manage revisions. 
4. It will live on readthedocs.org so that others can easily find and access, along with many other FOSS tools

**Comment by fnocetti** [comment]
For this first stage we delivered a Sphinx setup already configured in Read the Docs including it's design, the sources hosted in its own dedicated repository and the first draft version of the Administrator's guide already migrated.
There's still some things that need to be taken care of but their related more to the documentation itself than to the Sphinx/RTD setup.
Here are some resources for reference:

- Documentation sources repository: https://github.com/huridocs/uwazi-documentation
- Documentation: https://uwazi.readthedocs.io
- WIP version of the documentation: https://uwazi.readthedocs.io/en/initial-setup/

Any further work needed on this topic should be tracked in the documentation repository's issue manager, I think.
So, I think this is ready to be closed :)

**Comment by txau** [comment]
Closing =)

**Comment by kjantin** [comment]
Regarding:

>Documentation: https://uwazi.readthedocs.io

There's nothing there that I can see. But I can access the guide by going to https://uwazi.readthedocs.io/en/initial-setup/admin-docs/index.html

**Comment by fnocetti** [comment]
@kjantin that's because the default documentation version is "latest" (which should relate to the development branch) but we don't have docs for that version yet as the contents are still work in progress (you'll see that the initial-setup version still needs some work on the contents).
Maybe we can instead have an "Under construction" message and tell our users to refer to the wiki while we get the docs ready.
