### ISSUE TITLE
Scrolling the PDF should replace the URL instead of pushing a new URL to the stack

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2610]
When you scroll the PDF, the URL gets pushed to each new page as you scroll.

So, your start a page 1, then the url changes to page 2, etc.  

The problem is that, now the back button will scroll you back page by page, instead of taking you to your previous 'actual' navigated page.

This is even more critical if you have changed into the relationships panel, because since that point is not a 'url stop' (which we should also implement), you navigate back in pages that you are not seeing, so you click the back button 3, 4 times without any change in the screen.

I believe that scrolling should replace the current URL stack instead of pushing new addresses.

**Comment by Zasa-san** [comment]
We have a new pagination component that renders react router Link component, the url will get pushed into the browser history like the issue describes. Fortunately, react router allows to change that very simply https://reactrouter.com/en/main/components/link#replace

We can have this a as prop of the new pagination component, so that all the links it renders use the replace method instead of push. This chance can be implemented quite quickly. Probably the replace method makes a lot of sense in how the pagination component will be used in the new IX suggestions UI to paginate the suggestions table.

What do you think @konzz @RafaPolit ?
