### ISSUE TITLE
inherited metadata is not showing on cards.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2661]

**Comment by konzz** [comment]
@daneryl @RafaPolit It's not showing because in the list view we don't have all the connections of each entity, so the formater can't render the inherited values. We knew this when we moved forward with the idea of "client-side inheritance".

Not sure if close this issue because I understand we would like to have that feature, but dont think we can with the approach of client-side inheritance, also this will be solved if we finish the metadata-object.
