### ISSUE TITLE
Create connection gets bugged when clicking on the "create connection" button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#272]
1. Go to a document
2. Select text
3. Mouse over the "create connection" button.
4. Click directly on the create connection button (green button) without selecting one of the to options (to doc or to paragraph).

The UI becomes retarded.

**Comment by RafaPolit** [comment]
There is another bug on the create button, perhaps related?

1. Go to a document
2. Select text (create buton spins and becomes a "+" symbol)
3. Deselect text

The button remains a plus text and if you hover over the button your previous selection becomes green (which otherwise never happens in source mode, at least to my understanding).
