### ISSUE TITLE
Thesauri editing does not always save and seems wrongly displayed, then 502

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#274]
On test instance, I edited the test thesauri, renamed it and added values. I saved this and it worked.

Then, I tried to edit it again, but is not displaying the name of the thesauri, nor the values. If I add new ones, it does not save.

If I add another thesauri, it also does not save.

Then, refreshed in the browser and got a 502 Bad Gateway error. Checked other instances, they seem to be up.

**Comment by friedhelmweinberg** [comment]
After you redeployed, bug does not show up like this.

What I do get is that when I edit an existing thesauri and add a new term, it does not save and briefly displays that a thesauri under that name already exists.

**Comment by txau** [comment]
I tested it out and the bug is confirmed:

1. Go to thesauris
2. Edit an existing one.
3. Change the name and add an item
4. Save
5. Edit that same again
6. Hit the "Add item", then it will wrongly display a "Duplicated name" error message
7. Add a new item and try to save. It does not save nor provides any feedback message.

**Comment by txau** [comment]
Fixed
