### ISSUE TITLE
When upload of many documents fails, deleted them one by one is tedious

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#276]
1) I uploaded some 20 documents
2) my connection was unstable, so for a good number the upload failed
3) I had to delete them one by one from the list and found it tedious - can I do this in bulk (or should I?) or can I try to reupload?

**Comment by whyfrycek** [comment]
Also, would it make sense to add a "try to upload again" function?

**Comment by txau** [comment]
1. Actually uploading multiple documents its not fully supported. We didn't want to limit the functionality because it still works for small batches of documents. We will add full support for bulk upload at some point =)

2. We don't have support for bulk actions yet. This is also planned.

3. We decided not to expend time on this yet since it can be achieved by reuploading. Its a great usability improvement, but it will consume scarce dev time.

**Comment by whyfrycek** [comment]
Thanks, Jau! Maybe limit the supported then to small batches? I think I broke stuff again by uploading a real bulk :)
