### ISSUE TITLE
Should there be thesauri fields where I can add new values while working on a document?

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#277]
When working on documents, I am trying to add the "source", but I don't know all the "sources" when I define my metadata scheme. Should there be a field type, where I can add new sources on the spot?

For example, in Kanboard, I have categories that are defined in advance and tags where I can choose from previously used ones, but also add new ones on the spot.

**Comment by txau** [comment]
Definitely. Is a burden having to first define your dictionaries. This has been around for a while now, we will come to a nice solution sometime. 

Related to #154 .

/cc @danicatalan

**Comment by danicatalan** [comment]
@txau @whyfrycek I am developing a concept to add values to a dictionary from the sidepanel that require some feedback, please take a look the next mockups and tell me what you think about it.

The **first case** is when a property has a thesauri assigned but that thesauri doesn't have any value. As soon as the user selects the new value, it will be save into the thesauri.

![add-value-empty-dictionary](https://cloud.githubusercontent.com/assets/6364153/23415434/7ad34a56-fddf-11e6-995a-aded4ed43640.gif)

The **second case** is when the thesauri already has values, but we want to add a new one. I find this solution quite intuitive because if you find for a property that doesn't exist, you can create it on the fly.

![add-new-value](https://cloud.githubusercontent.com/assets/6364153/23415493/a1b6b5d6-fddf-11e6-8a8f-2422eaad1925.gif)

The **third case** is when the we just select an existing thesauri, our current functionality and works like a charm :)

![add-existing-value](https://cloud.githubusercontent.com/assets/6364153/23415522/b873d8bc-fddf-11e6-8e40-ed408ab3641c.gif)

I've been thinking about the + icon too. First attempt was without any special icon (just another checkbox) and it feels like magic, but maybe it's confusing for the user. In these examples I specified the + icon to tell the user it's a new value, but other ideas are welcome.

**Comment by RafaPolit** [comment]
We had a quick change of heart regarding the approach to this issue:
- It would be a modal opened by an "add value" text underneath the property name
- it would open a modal saying: "Add thesaurus value", list the name of the Thesaurus (not an non-editable input as in the designs)
- It would present a FORM with two inputs:
- The first one is a "Group" dropdown selector with `<root>` as the default, and will list all the groups of the thesaurus... this way you can select where to "nest" the value you are adding
- The second one is a text input for the Thesaurus name
- Ideally, typing thigs here would say "duplicate value found" if you already have that value at that nesting level, and, as a nice to have, if identical or similar values are found in other groups.
- This only requires a save-cancel combo, no need to delete anything
- This flow doesn't allow to create new groups, at MVP at least

**Comment by nwyu** [comment]
Link to the [Figma design](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=565%3A5349), though kindly take note to implement as it is described above!
