### ISSUE TITLE
Properties of type 'select' are not recognising translated list/thesaurus items

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#2770]
The list/thesaurus on this Uwazi instance has been translated into AR:
![image](https://user-images.githubusercontent.com/354426/74581497-db223f00-4f64-11ea-851f-3e2a79b731aa.png)

...but when you are in the AR interface, the items are in English:

![image](https://user-images.githubusercontent.com/354426/74581647-694af500-4f66-11ea-9fb0-a1d87160edbf.png)

...but the properties of type "multiselect" seems to pulling in the translated list items, as expected.

**Comment by kjantin** [comment]
Another partner has reported the same problem on their Uwazi instance that uses AR translations.

**Comment by gabriel-piles** [comment]
The problems with the translations were there due to two things:

* Sometimes the context id was not passed properly to the translations module
* The translations module accepts void context ids without throwing any exceptions

The code is going to be changed to throw exceptions when a translation is requested without context id. 

This happened in two places in the code, in the metadataformfield the context id was template._id and as this object is an immutable the correct way to get the field is with template.get('_id').

The second bad translation occurred when multiple entities from different templates were selected, no context id existed to process the translations.

**Comment by gabriel-piles** [comment]
A separate issue about the missing translation when multiple items with different templates are edited was opened #2820 , and it is not going to be solved in this fix.

**Comment by kjantin** [comment]
Hi @konzz and @gabriel-piles - was this issue supposed to have been fixed and deployed with this latest deployment today? Unfortunately, the original issue of the properties of type "select" (and I think also "multiselect" now) are still not displaying the proper translated values.

**Comment by txau** [comment]
@gabriel-piles  select translations are not working for me either. Multi-selects are working though. @kjantin can you provide an example of multi-selects not being translated?

**Comment by kjantin** [comment]
>@kjantin can you provide an example of multi-selects not being translated?

Yes, I have shared an example privately.

**Comment by gabriel-piles** [comment]
Hi @kjantin, the changes about the Select translations have not been deployed yet, but the functionality is implemented and working in the code for the next deploy.

**Comment by txau** [comment]
Fixed.
