### ISSUE TITLE
When a file is not found the server tosses a 500 instead of a 404

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2786]
More over instead of having an instant response, it takes some unnecessary time.

**Comment by daneryl** [comment]
@txau the returning a 404 instead of a 500 its solved on #2754, the performance issue im not able to replicate, in my case the response time its between 15 - 50 miliseconds. 

Is this time measurement reloading the page on the pdf viewer or navigating from within the application ? if it is reloading and with an instance with a lot of data the long response times are probably not because of the file request that happens after the page is loaded but by the loading the application itself.

**Comment by txau** [comment]
It may be that.
