### ISSUE TITLE
Unique ID Field

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2792]
Create a new form Field that it's automatically filled with an autogenerated friendly ID.

- IDs should be numbers in sequential order + the year like 107-2020 or 23-2020 or 1018-2020
- The filter for this field should be a text input where users can type the exact ID: "107-2020"
- The field should be disabled so users can't edit it.

**Comment by kjantin** [comment]
Is this issue closed because it is being deployed? 🤞

**Comment by konzz** [comment]
No, it's been merged with the custom public form

**Comment by txau** [comment]
@kjantin this has been discussed as a particularity of the project, rather than a general feature for everyone. The reasons being:
- The format of this id can vary from a use case to another.
- The read-only conditions is arbitrary for this project. We provide audit instead.

If there are other uses cases for this particular feature, it would be great to know about them.

**Comment by kjantin** [comment]
@txau yes there are a number of projects that have requested this - it has been documented here and I thought this was already known by the team https://github.com/huridocs/uwazi/issues/1173
