### ISSUE TITLE
Duplicate entity functionality.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#2793]
Add a button (to be decided where, probably next to edit, publish, delete etc..)  that opens the metadata form, but removing id and sharedId so it will create a copy of the entity with all the information.

Relationships, documents, and attachments should not be copied.

**Comment by txau** [comment]
> Relationships, documents, and attachments should not be copied.

Why not?

**Comment by konzz** [comment]
Because that is what I understood that the partner needed, and the complexity time from just copying the metadata, to also copy relationships, documents, and attachments, is a lot more.

**Comment by txau** [comment]
@konzz Ok. I guess we should take the time to think how other users are going to benefit from this functionality and decide whether relationships, documents and attachments should be also dupped or not.

**Comment by simonfossom** [comment]
@konzz I don't understand this part about sharedid and id. Do you mean duplicate entity within the same template but without attachments and documents attached? Can you explain this a bit? Also why not copy relationship tree?

Solution could be very easy but what's the user story?

**Comment by txau** [comment]
@simonfossom when users need to reuse some metadata that has already been filled in, so essentially you want to copy and paste one of the entities and modify only part of the metadata.

**Comment by RafaPolit** [comment]
This is further reason why I believe that 'import metadata from' is the way to go.

As Konz points out: what is "duplicate entity to template" mean?  Should it copy the documents and attachments? Obviously metadata-driven relationships would be created, but how about actual existing relationships that are not in the metadata? Should they be copied?

If it has a document and the document has text relationships, do you want them copied as well? TOC probably is clearer that you will probably want to copy.

So, there are so many "IF"s here, that I think it's not useful to build something that can ask such a million questions on duplicating.

Importing seems like a much 'cleaner' approach to me:
- Import metadata from entity
- Import attachments from entity
- Import document from entity (single question: keep text relationships?)
- Import relationships from entity

It's much cleaner, you are much more in control, you can predict the results much better.  I'm really having a hard time seeing this 'duplicate' approach, and more so how it's not that clear to others that it is probably a bad idea.

I'm, as always, happy to be convinced otherwise.

**Comment by RafaPolit** [comment]
It has been decided that we will go for the "import from" flow, instead of "duplicate".

It is much simpler in terms of understanding what is actually being done, specially in terms of connections, references, etc.

Closing in favor of #2946
