### ISSUE TITLE
Missleading dual magnifiying glass

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2807]
On mobile, the filtering sidebar is opened by clicking a magnifying glass icon, which is the same as the "search" action for the search bar. This can confuse users and has an easy fix if we just use another icon for the filters.

![Screenshot from 2020-03-07 09-42-21](https://user-images.githubusercontent.com/489831/76146393-ffe76f00-6057-11ea-8273-163a28977bd0.png)

**Comment by nwyu** [comment]
The magnifying glass on the right top corner on mobile has been replaced with a filter icon. This (show) filter icon on mobile has also been moved off the main navigation bar so that the design is consistent across cards and table view. This is currently fixed in staging and will be deployed to production next Monday.
