### ISSUE TITLE
Better error reporting when the amount of data allowed for a field is exceeded

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2840]
If a user tries to insert in a text field more data than allowed by ES restrictions (: bytes can be at most 32766), Uwazi throws an error simply saying "An error has occurred". These users have no way of knowing why this is happening so they can approach their data loading in a different way.

On the top of that, the error is only triggered when they exceed the request pay load, but not so much during the indexing error:
```
2020-03-25T17:22:46.466Z [localhost] ERROR Failed to index document 5e7b9353df968d20b9c4dbf1: {
 "type": "illegal_argument_exception",
 "reason": "Document contains at least one immense term in field=\"metadata.resumen.value.raw\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[72, 85, 82, 73, 68, 79, 67, 83, 32, 115, 101, 101, 107, 105, 110, 103, 32, 83, 111, 102, 116, 119, 97, 114, 101, 32, 68, 101, 118, 101]...', original message: bytes can be at most 32766 in length; got 491349",
 "caused_by": {
  "type": "max_bytes_length_exceeded_exception",
  "reason": "bytes can be at most 32766 in length; got 491349"
 }
}
2020-03-25T17:23:06.597Z [localhost] 
url: /api/entities
PayloadTooLargeError: request entity too large
```

So it is failing silently when the error is on ES indexation, but tossing an error when the error is due to browser payload. 

I haven't checked whether the content does not get updated or it gets truncated.

**Comment by RafaPolit** [comment]
As the error report, this causes the document not to be indexed in  ES, but it will remain in the Mongo DB, so every time a reindex is requested, this error will appear.  Also, the user is 'unaware' that the DB contains a document that is not displayed on the library (because the library uses ES to display it's results).

The problem is that, if ever we carry mixed queries from ES and Mongo, there will be a discrepancy here.  Or errors fetching the document in ES from Mongo. 

This inconsistencies are hard to deal with, and we should aim to better this perhaps with regular 'sanity' scripts that report: 'inconsistencies between Mongo and ES' or similar diagnosing tools.

**Comment by RafaPolit** [comment]
Related to #845

**Comment by RafaPolit** [comment]
For the time being, just address the error bubble-up and better client feedback.

The 'ghost' database document that is not reflected in Elastic is a much more complex development.

**Comment by RafaPolit** [comment]
During sprint planning we have decided to:
- Keep a "generic" bubble up of errors from Elastic to the user when indexing fails, so that the user at least is aware that there was a problem.  This still doesn't solve the "ghost" entries on the Database, but at least improves the feedback a bit.
- For this particular error, implement an AJV route-level validation rejecting POST structure with more than X size on fields.

**Comment by mfacar** [comment]
@RafaPolit after the validation, the control at the moment of indexation of entity became unreachable code. Given that the validation error is not showing the detail of the errors, the user will not be able to know the reason that is firing the error, I will review the message handling in order to give the user this information.

**Comment by mfacar** [comment]
I reviewed the implementation and effectively the API is returning a specific error with the validations that were not satisfied but the final message is losing this detail and only is showing a general "validation failed" message, handled as a NonUsualApiError. Maybe is it pending to handle the response with this kind of validation errors?

**Comment by RafaPolit** [comment]
Can you please coordinate with @daneryl a call to discuss this and what is the best approach?  Thanks.

**Comment by mfacar** [comment]
After validated with @konzz there it's pending a parse of the validations errors at the client-side.
I've included a little generic method that takes and notifies the validations messages. 
In the scope of this issue, we could have two different error messages:
- When the payload is giant:
   The request has too large data. Please review any long value property.
- When the field value of an entity exceeds Lucene bite-size limit  
   validation failed: .metadata['resumen'] field is longer than the max supported
