### ISSUE TITLE
Custom Page JS is executed always twice when navigating to a different page (8 points)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2864]
A custom page's JS is executed twice:
- upon entering the page
- upon entering a DIFFERENT page before the custom JS for that page gets loaded

## To Reproduce

- Create a page with a simple JS console.log
- Create a second page
- Create menu entries for both pages
- Navigate to page one, confirm that the console.log is rendered
- Move to page 2, see that the console.log is called on once more

If you navigate to a third page, the page's JS is already 'clean' and will not get executed again, so this may be an issue with the page status and when is the custom JS executed.

**Comment by Zasa-san** [comment]
The issue is no longer persisting.

**Comment by Zasa-san** [comment]
During review of #3733 this issue was reproduced. The condition is that one of the pages needs to be a custom home page.

Steps to reproduce: 
- Create two pages, each with a console.log of a identifiable string.
- Assign one page as the Custom home page, and another page to a menu item.
- Go to the home page, open the console, and switch between it and the page in the menu item.

![report](https://user-images.githubusercontent.com/71732018/121250823-8d79c600-c87c-11eb-889a-0d764e7cef28.gif)
