### ISSUE TITLE
"Preview" property should not appear if no file uploaded.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2884]
Preview property renders a preview of the uploaded PDF.  Previously, a template was either entity or document, and preview could only be assigned to document templates.  Furthermore, the only way to 'start' a document entity was to upload a PDF, so preview was available always.  Still, I remember there was a 'no preview' file for those scenarios.

Since now any entity can be either just entity or document, and any template can hold a preview, there is a bug that Entities that have no PDF uploaded are rendering an 'undefined' preview.

If no PDF has been uploaded, just like other metadata properties, this should not show the preview label and value neither in the side panel nor in the cards.

Optionally, we could make it point to the previous 'no preview' IMG which was a route that catched this errors, perhaps that got broken somehow.

**Comment by RafaPolit** [comment]
Please check:
- [ ] A template that has no preview and an entity loaded a PDF from before, what happens if you add a preview (after having created the entity and uploaded the file)
- [ ] What happens if a template HAS the preview property but the entity does NOT have a PDF uploaded: is it showing the "no preview" placeholder image, is it not showing the property at all?  Discuss what we want as an outcome
- [ ] That preview is showing correctly when a PDF is uploaded (this I have already checked and it is)

**Comment by fnocetti** [comment]
After checking the cases:

- If you add a preview property to an already existing template, the preview is not generated for the entities that were created before the template change.
- If a template T has a preview property, the entities of type T not having a PDF associated will show the preview field with a broken image (because the image does not exist in the server).
- All this applies to both card view and sidebar view.

This suggest the following:
- When a template contains a preview property, the application always assumes it exists (have a value) for the entity and try to load it from the server into the UI.
- The preview is only generated for newly created entities for templates that contain a preview field at the moment of creation.

We will need to decide:
- Should the application batch generate the previews for all involved entities when adding a preview field to the template?
- In case a template T has a preview property and an entity (of type T) does not have a preview generated (because of a bug, failure or because it was created before T had a preview and we decided not to batch generate) should the application:
  - Show a "no preview available" placeholder, or
  - Do not show the field at all (this is the behavior for the rest of the fields), or
  - Continue to show the broken image (which could be the sign of an application failure if we assume there should always exist a preview if the template has the property)

**Comment by RafaPolit** [comment]
> * If you add a preview property to an already existing template, the preview is not generated for the entities that were created before the template change.

Really?  This probably isn't right.  Is there any code section that would check if there is a preview field in the template before generating the preview? I don't think so, something doesn't add up.

Did you try doing the same AFTER adding the property? Can you see the previews of documents added after adding the property?

**Comment by RafaPolit** [comment]
> * Should the application batch generate the previews for all involved entities when adding a preview field to the template?

No, the application generates a Thumbnail of the PDF at the moment of creation, no matter what configs are present in the templates.  Something is not right here.

**Comment by fnocetti** [comment]
You are right! My apologies, I was testing with inconsistent data. The thumbnails are being generated just fine in every case.
The following continues to be valid:
- When a template T has a preview field but an entity E of type T does NOT HAVE AN ASSOCIATED PDF it will show a broken image. In fact, it is trying to locate /api/files/undefined.jpg on the server.

We can fix it to use the "no preview available" placeholder really quickly. Not showing the field at all can be a bit more complex, but still simple anyway.

**Comment by RafaPolit** [comment]
This property should follow the logic that rules all other template properties:
- if the entity is missing that field (or the data to populate that field) we do not show the property

This means, that if entity E of type T has no file, the Preview property should not attempt to render. 
 Neither it's label nor it's content, just like every other property in the system.
