### ISSUE TITLE
"View" button from relationship tree view doesn't work

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2890]
<img width="1328" alt="Screen Shot 2020-04-28 at 14 50 19" src="https://user-images.githubusercontent.com/8134850/80489272-e0860780-895f-11ea-9c0b-cef347052aac.png">

**Comment by kjantin** [comment]
Is this related to https://github.com/huridocs/uwazi/issues/2205?

**Comment by simonfossom** [comment]
I would say not. It connected to the larger problem of navigation and hierarchy.

**Comment by RafaPolit** [comment]
Just to clarify: the button is working, the problem is that you are trying to 'view' the same entity where you are already AT, so you are navigating to the same location.  It is the equivalent of saying "I click on Contact Us, and then I click again on Contact Us and nothing happens'.  Yes, you are on the same page.

I agree we could not show the view button when you are already in that entity, we find a better language to express that that is the current entity, but the button is not malfunctioning.
