### ISSUE TITLE
Library Pagination

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2892]
We need to have pagination on the library to avoid reloading and rerendering the previous cards that are already loaded.

This is also need for: #2708 and #958

**Comment by RafaPolit** [comment]
For the purposes of sever side rendering, and also for copy-pasting the URL, we need to 'split' the page URL with the internal requests because:
- The url needs to read limit=600
- But the internal request needs to ask for limit=300, offset=300 (or whatever the exact wording is for the elastic pagination)

**Comment by konzz** [comment]
The library search works by updating the URL whenever you do a change in the filters, update the limit, or introduce a search term, then the Library route detects this change in the URL, processes it, and requests the new documents.

If you have a 300 limit, and 100 documents, there is no way to tell if the new request is happening because you updated the limit, or changed a filter, in the former you have to send an offset of 100 but in the later you have to send an offset of 0.

The solution will be to: 
- Include the offset in the URL
- Whenever a filter is changed reset the offset to 0
- If you don't have documents in the state (rendering from server) the request should be made with offset 0
