### ISSUE TITLE
mobile filters cannot close. there's no 'X'

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2899]
![demo uwazi io_(Galaxy S5)](https://user-images.githubusercontent.com/8134850/80983931-78d32f00-8e2d-11ea-9537-197f7175958c.png)

**Comment by txau** [comment]
To add a little bit more weirdness:
- Finding the filters took me a while until I realized it is the magnifying glass icon on the top. I assumed that was just for searching.
![image](https://user-images.githubusercontent.com/489831/94217504-6a021d00-fe9f-11ea-84a7-267eda184108.png)
- In table view mode, we have another icon to display the filters.
![image](https://user-images.githubusercontent.com/489831/94217384-1a235600-fe9f-11ea-974d-2e6eab2bde0e.png)
- When filters are displayed from table view mode in mobile, they actually have a close button.
![image](https://user-images.githubusercontent.com/489831/94217536-7edeb080-fe9f-11ea-8d16-980c37289475.png)

@simonfossom I think we could use a better close button for side panels (https://github.com/huridocs/uwazi/issues/1855) and maybe unify the filtering icon so is not the same as search (https://github.com/huridocs/uwazi/issues/2807)?

Also the "search tips" link could be placed as a small help icon (?) besides or inside the box since that link is messing with the alignment of the whole UI.

**Comment by simonfossom** [comment]
Yes, I did it in tableview, but it wasn't implemented the way it was designed. Only minimal UI changes were made. This has some shortcomings as you can see.

Here's a [proposal to fix mobile-view](https://www.figma.com/file/xjsz7r65epN4B0b96zilac/UWAZI-redesigns?node-id=941%3A1811) until we can do complete implementation of table-view:

**Comment by RafaPolit** [comment]
There is a closing arrow for the sidepanel which is only visible if you rotate the screen.

**Comment by mfacar** [comment]
@simonfossom I have some doubts about the proposal, could you please solve them?
- The changes in the mobile view, like moving the search bar inside the filters panel and relocating buttons, do they apply to both higher resolutions and card view?
- In the mobile view, the close button is in the header, and the filter pane fills the entire screen, what is expected with a higher resolution?
- Should we consider the closing button suggested in #1855?

**Comment by simonfossom** [comment]
Proposed changes are for all view - but just for the mobile (under 1024px width).

**Comment by txau** [comment]
![image](https://user-images.githubusercontent.com/489831/95339219-10bbc580-0871-11eb-893c-d6919b5e8475.png)
@simonfossom In this screen keep in mind that users can translate these strings to their own. This layout may break if the translations are longer than the English verison.

![image](https://user-images.githubusercontent.com/489831/95339385-3ea10a00-0871-11eb-9822-f46b215b2ca0.png)
Are we moving the search bar to the side panel only on mobile or also for desktop? If it is only for mobile it may be a tricky implementation. It can be done but definitely more work. 

Also the search tips link is missing. I don't know if it is being used a lot, but I know it is being used by some users.

**Comment by mfacar** [comment]
@simonfossom it could be super useful if you include the desktop view in the prototype, please could you add it?

**Comment by simonfossom** [comment]
Well, the thing is, the desktop is not supposed to change. Just mobile should change.

**Comment by RafaPolit** [comment]
@mfacar While we fine tune the different solutions, we need this solved with as simple a solution as possible.

So, for now, this development includes ONLY an "X" to close the filters side panel, at the very top right of the filters side panel (aligned right at the same height of the `Filters` header).

So, just this:
![image](https://user-images.githubusercontent.com/489831/94217536-7edeb080-fe9f-11ea-8d16-980c37289475.png)

**Comment by mfacar** [comment]
The solution for iOS merged in #3239 broke the scrolling at the library views,  #3339 fixed the scroll problem.
I'm reopening this issue because with the scroll fix the problem with the closing button on iOS remains.
