### ISSUE TITLE
Opening a newly uploaded file in a new tab tosses a server side error

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#2926]
Moreover, this prevents the initial processing of the file so it is no longer loadable unless it is visited via the client side app.

Steps:
1. Upload a file.
2. After processing, open the "view" link in new tab.
3. File contents won't load.

A temporal workaround is opening the file in the same app window (no new tab), then the initial processing will be triggered and everything will work normally, including opening in new tab.

**Comment by RafaPolit** [comment]
Didn't we address this on a previous PR already?

This is probably due to the PDF data extraction that needs to happen in client.  In this case, it is first happening during server side rendering (which should NOT attempt this procedure) and then returning to client which should actually start the procedure.

I know we visited this issue once before, perhaps something else broke it again.  We need e2e for these conditions.

**Comment by mfacar** [comment]
In general, the cause of this issue is the same in two parts of the code, it is the loss of data of settings and request among the changes of state while the page is loading. I addressed these two specific parts but it could be good to take it into account if there are new dependencies in the future.
