### ISSUE TITLE
Entity view design

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#294]
- Create route for entities
- Load metadata in the view

**Comment by danicatalan** [comment]
![screenshot 2016-08-20 00 37 00](https://cloud.githubusercontent.com/assets/6364153/17826160/524d6070-666e-11e6-903c-e33c5bb37f8e.png)

Esta es la estructura básica en HTML para realizar la presentación de los datos en las entidades. Tengo que trabajar sobre los estilos bastante, pero no he profundizado porque el creador de entidades no me funciona ni en development ni en local. De momento he exportado la estructura del viewer de documentos para salir del paso.

@txau @konzz podeis echarle un vistazo al error para ver de que se puede tratar?

![screenshot 2016-08-20 00 40 46](https://cloud.githubusercontent.com/assets/6364153/17826216/c5a2a710-666e-11e6-81ce-913dc9f7b6db.png)

**Comment by danicatalan** [comment]
Test with bigger entity title and less info in sidebar cards for balancing font weights:

![screenshot 2016-08-20 01 25 12](https://cloud.githubusercontent.com/assets/6364153/17826831/fc0c8392-6674-11e6-9bb3-c7c01d8f0826.png)

**Comment by danicatalan** [comment]
I create this other iteration for the design with white background for metadata because UI consistency (library background is grey), and I think this will look cleaner with entities with a lot of metadata.

I started to review the "edit" metadata mode, there's a lot of work to do and I prefer to validate the idea before start working on this.

![screenshot 2016-08-21 17 37 13](https://cloud.githubusercontent.com/assets/6364153/17838157/f9aa21e8-67c5-11e6-8c0d-843bdf9e156c.png)

**Comment by danicatalan** [comment]
Updated on https://github.com/huridocs/uwazi/tree/294-entity.

All the HTML is on `EntityViewer.js`. @konzz I tried to create a dummy array but I couldn't, so I let the connections space empty with the `.item-group` ready to inject the connections component.

I created a scss files under modules, too.

**Comment by txau** [comment]
Closed in #343
