### ISSUE TITLE
Template property name checker is using Label and not Name to check for duplicates

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2988]
Related to: #2971

Our template creation process prevents duplication of property names.

The CRITICAL problem is that it checks for label and not the sanitized name.  

# To reproduce

- Create an empty template, give it a name: "TempA"
- Create a text property named "país"
- Create a date property named "pa_s"

Save the template.

Both properties, internally, are named "pa_s".

This causes innumerable issues on filters, on metadata structure, on elastic indexing, etc., etc., etc.

**Comment by daneryl** [comment]
@RafaPolit name was actually being validated on the template validator, the main problem is that the validation is being called before the name being generated from the label 😅

https://github.com/huridocs/uwazi/blob/75726b07e09223c45dd4ec029ad294a61162bcc1/app/api/templates/templates.js#L62-L66

i have fixed this on the PR, i have also improved error messages returned from the validator for duplicated properties validation, the validator is now validating id and name instead of id, name and label.
