### ISSUE TITLE
Better filtering / naming on selects for Inherited properties 

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#2990]
As an admin, if I have configured a property to be inherited from a property other than title, I want to be able to filter, search and/or select by the inherited property and not necessarily by the title.

Specific use case:
- I have cases that have their title, but also a 'unique identifier' because certain naming are ambiguous
- I have a "unique identifier" that disambiguates the name
- I have "sources" that are related to a case, inheriting the unique identifier (relationship property configured as inherit)

When creating the source, when I go to select the case, I want to be able to filter by case number and see the numbers, not only the case titles.

Also, it makes sense since it is the inherited property the value that will show.

For example, lets assume a different scenario:
- I have a victim and age at time of victimization in one template
- I have an act template and I want to index all the ages at time of victimization to be filterable, so I create a template property named "Victim's ages"

When I create the act, when it is time to fill the "Victim's ages" property, I am presented with victims names.  It's weird to fill a value named "ages" with "names".  But it is important to also know that this will inherit that value.

So we need a better flow for selecting values of inherited properties.

cc @simonfossom @txau

**Comment by simonfossom** [comment]
I'm trying to follow your scenario...
I'm assuming that you want to link an entity's property in another entity?

**Comment by txau** [comment]
We've been discussing this and while we still do not have a clear solution it may require that inherited properties adapt their behavior to the kind of data they are inheriting. So a geolocation data type will behave differently than a text data type and so on so forth.

The reason for this is because when you inherit a geolocation type, more often than not, you want to use it as a label instead of lat/long you want to use it/see it as "Spain" or whatever label that lat/long is pointing to. But if you inherit a if you inherit a text such as "country code", you want to use it/see it as the actual text, ie "SP" instead of "Spain" (or eventually a combination of both "SP (Spain)".

**Comment by simonfossom** [comment]
I agree. We need to display the value. 
I would display value and title in select. I think it is needed for context. 
Maybe 

![image](https://user-images.githubusercontent.com/8134850/85415213-54fab280-b56d-11ea-9a52-4e489df0868e.png)

**Comment by txau** [comment]
This is being worked in other issues.
