### ISSUE TITLE
Allow groupings on CSV Import of thesauri

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3046]
Since we allow grouping or 'nesting' of thesaurus values, we should implement a way to achieve that structure via CSV Import.

**Comment by fnocetti** [comment]
I could think about the following 3 approaches:


1.
![Image](https://user-images.githubusercontent.com/11740873/179065171-470d869d-8938-4425-a421-0b0575876f15.png)

This has the advantage of being the simplest to the human eye and that it is future proof in terms of nesting depth (in the sense that if in the future we allow nesting levels greater than 1, we can append extra `-` to the following levels.
The disadvantage is that it is positional in terms that the rows cannot be freely re-arranged, and that it requires consistency between languages. We can either validate, or tolerate inconsistencies.


2.
![Image](https://user-images.githubusercontent.com/11740873/179065837-f34c37df-17d8-4875-bcd7-bac7ce866f78.png)

This one is not as graphic as the first one but still keeps the shape somehow.
The advantage is that it is also future proof by incrementing the nest_level value, and that there's no redundancy for expressing nesting compared to the previous.
Shares the disadvantage in that it is positional, since rows are nested to the `previous` one with lesser nest_level.


3.
![Image](https://user-images.githubusercontent.com/11740873/179066587-97340abc-cbbd-4a00-a212-d713308a792a.png)

This one is not positional but would be harder to implement given possible circular references and "use before declaration" problems. Also, it seems unlikely that a user won't organize the CSV in a non-positional way.


My personal opinion is to go with approach 1, validating that the nesting levels (`-`) are consistent, and returning a useful validation error otherwise.

I like the idea of optionally allowing the approach 2 as well, although it's more work.

What do you guys think?
cc @RafaPolit @txau @nwyu @LaszloKecskes 


EDIT: When I say future-proof I mean the syntax, not the implementation.

**Comment by LaszloKecskes** [comment]
Out of these I like the first one the most. 

How about an option for a "connector" character, like we do for multiselect in the entity csv import? Just for example, with double underscore: parent__child. On the upside:
- this is also very visual
- not location bound
- you do not have to have the entry for the parent in the csv explicitly (i.e. if the parent already exists)
- translates well to the entity csv import case if we want to extend to that later

On the downside:
- a lot of extra typing to repeat the parent
- ...which also makes more room for error (e.g.. the user enters 10 values, makes a typo in one parent, etc.)

**Comment by txau** [comment]
@fnocetti @LaszloKecskes I am trying to picture how would these 3 options work for partial imports. So if a thesaurus already exists but the user wants to add more options to it:

- Is that possible with Uwazi at the moment?
- In that case, how would it work to add new items to a parent? Are partial imports conditioning the selection of the format?

Also I prefer options 1 or 3. Option 2 seems little bit fuzzier for the end user. For option 3, in which language is the user specifying the parent? is it any language or it has to be the default language?

**Comment by fnocetti** [comment]
Uwazi currently supports partial imports. It works in an upsert basis. We could follow the same approach here.
I think option 1 is still better than option 2 because for that language question you raised.
As an example, if you wanted to ad a fourth color to the primary group, and also white to the root, you would import this:
```
English, French, Spanish
Primary, Primaire, Primario
- Other, - Autre, - Otro
White, Blanc, Blanco
```

**Comment by txau** [comment]
@fnocetti I am ok with that solution. The only drawback is having to repeat the groups with the translations for the upsert, but I guess it is very situational and not a big problem.

Is there a language that controls the duplication. So if for example I change one of the translations in your example:
```
English, French, Spanish
Primary, SOMETHING, Primario
- Other, - Autre, - Otro
White, Blanc, Blanco
```
What would the import do in this case?

**Comment by fnocetti** [comment]
@txau yes, the language of the request controls the import.

**Comment by txau** [comment]
> @txau yes, the language of the request controls the import.

I think that is not obvious for the end user, I wonder if we should make it explicit. We can rely merely on documentation for this or add some UI explanation.

**Comment by hyebin-bina** [comment]
Hello all,

Thank you for developing this new feature - this has been needed!

I tested importing grouped thesauri in multiple languages, and I noticed it imports only one language at a time. 

When I import a CSV file that contains thesauri in English and French (as below) under the English setting,
<img width="323" alt="Screen Shot 2022-08-10 at 7 23 21 PM" src="https://user-images.githubusercontent.com/85096417/183879528-74418019-9d73-40b3-b8d0-45cf9ede119b.png">

it only imports English thesaurus. When I switch the instance's language to French, 
instead of showing me the French thesaurus, it only shows the English thesaurus. 
<img width="1201" alt="Screen Shot 2022-08-10 at 7 29 34 PM" src="https://user-images.githubusercontent.com/85096417/183880049-30409d11-0bee-4e2b-8a76-213471be5214.png">

Do we not support multiple language imports for grouped thesauri?
Thank you!

**Comment by fnocetti** [comment]
Hi,
Technically speaking, the thesauri definition is always in one language (which most of the times happens to be English), so when editing the definition of your thesauri, you'll see it in the language you defined it no matter in which language you are using the ui at the moment.
On top of that, translations system will handle the translated values in each language for your thesauri. To check that they were correctly imported you should go to `Translations > Color`.
Also, you should be able to see your thesauri values correctly translated when you are viewing or editing an entity that uses that thesauri in a Select or Multiselect field, as well as when displaying such a field on the cards in the library.
Just in case, I just tested the functionality and it seems to work as expected.
Please, kindly check that your translations were correctly imported and you can use them, and let me know if this is still an issue :)

**Comment by hyebin-bina** [comment]
Hi Federico,

Thank you for your explanation; I also went ahead and checked following the routes you wrote and could confirm that the thesaurus was indeed imported into different languages. Thank you!

<img width="217" alt="Screen Shot 2022-08-11 at 4 46 23 PM" src="https://user-images.githubusercontent.com/85096417/184087569-da7682bf-3492-471b-8b46-2e6a8d31b26a.png">

<img width="261" alt="Screen Shot 2022-08-11 at 4 46 02 PM" src="https://user-images.githubusercontent.com/85096417/184087555-67af396d-e4cd-4856-82b3-f5f3693e1dd8.png">

**Comment by nwyu** [comment]
Thanks for the explanation, @fnocetti, and for testing this, @hyebin-bina!
