### ISSUE TITLE
Geolocation import csv

### ISSUE THREAD

**Issue by Ilyes-Chiha** [huridocs/uwazi#3071]
Hello
I am working on two instances of which I have the same table structure in both. an instance is fed with data so i wanted to feed the other instance of the same contained then i imported csv from one and exported the same csv file without any change to
 the other. the export ended well without filling in the geolocation field how can I do it

**Comment by txau** [comment]
Sounds like a good question for @fnocetti

**Comment by fnocetti** [comment]
@Ilyes-Chiha @txau I'll take a look

**Comment by fnocetti** [comment]
@Ilyes-Chiha I'll ask you some questions to check if I understood correctly and gather more information:

- You are facing this issue while exporting a csv file. Is that right?
- You exported a csv file but the geolocation fields are not exported. Right?
- If that's the case, NO geolocation fields were exported or some of them were exported correctly?
- Do your instances have templates with more than one geolocation field per template? It is totally fine to have more than one geolocation field per template. I'm asking because CSV export can be having issues (that need to be fixed) in that scenario.

On the other hand, please be aware that the CSV Export functionality was not designed to output files ready to be imported in another instance, but for data analysis with external tools. You might find formatting issues during the import phase when doing so, that will need your intervention on the CSV file.

**Comment by Ilyes-Chiha** [comment]
@fnocetti firstly, thank you for your reply. In fact you have understood my problem. but, at the beginning I wanted to fill in a template which I named city and which includes city_name and geolocation but the import was successful for the city_name
but not for geolocation.

As it didn't work, I assume that I have not found the required geolocation format that can be imported from a csv file to uwazi, Can you help me with this? Thank you again.

**Comment by nwyu** [comment]
@Ilyes-Chiha To import geolocation, the coordinates data should be included in one column (e.g. latitude|longitude). There should be no space on either side of the pipe symbol. In the csv file, this column should be named geolocation_geolocation.

**Comment by fnocetti** [comment]
Hello @Ilyes-Chiha ! Do you have any updates on this? Were you able to work the problem out?
Thank you!

**Comment by Ilyes-Chiha** [comment]
hello @fnocetti  I am sorry for the delay of my answer I followed  directive of @nwyu  to import coordinates of geolocation via an excel file but it did not work I had to fill the data of the geolocation of the cities one by one.

**Comment by fnocetti** [comment]
@Ilyes-Chiha sorry to know you had to do it manually, but glad you could work it around!
I'll close this issue know, and bring your input to the team, it's really useful! Thanks!
