### ISSUE TITLE
Download no longer respecting original filename

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3092]
The Download of the main PDF file has changed behaviors.  It now acts very much like what is being requested in #2068 (for which approach I don't agree, but that is besides the point here).

Upon hitting the download button, there is a new window opened with the file (instead of a Download dialog), but the name of the file is our serialized PDF name and not the original filename of the uploaded document.

Losing the original filename is not expected, and the resulting name is completely useless in terms of semantics and storing procedures.

Even if we are keeping this route of opening a new tab instead of having the download button actually download!, the original name should be kept.

cc @txau

**Comment by txau** [comment]
Regarding the default behavior it was changed to open in new window instead of download since it gives more freedom to user to decide what to do with the file. Forcing the download won't let them just visualize the raw file while opening in new window let's them save the file when loaded (if they want to) or just right click on the download button and choose "save file".

The file naming should be fixed.

**Comment by RafaPolit** [comment]
Ok. But then should the button say something different to download?

But yes, the key aspect of the issue is the naming problem.

**Comment by txau** [comment]
@RafaPolit it depends because keep in mind that the behavior of the button is controlled by your browser. If your browser can handle the mimetype it will display the document, if not, it will force the download.
