### ISSUE TITLE
Upload in demo instances

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#310]
Uploading of a PDF document does not seems to work in Firefox. Works on Chrome... ?

**Comment by txau** [comment]
@YolandaCHR Thanks for reporting.

I've been debugging this and rather than a browser issue, seems to be a server misconfiguration causing an intermittent malfunction in uploads. This is only happening in our demo server and not in other instances.

I'm notifying the administrators so they can take a look.

@daneryl @nestorsalceda 

I get this error sometimes when I navigate to the uploads section, not sure if its related:

![screen shot 2016-08-23 at 11 54 54](https://cloud.githubusercontent.com/assets/489831/17887926/e4ba6388-6928-11e6-91c6-3616f7810883.png)

**Comment by nestorsalceda** [comment]
It looks a misconfiguration with proxy and websockets. Going to fix!

Thanks for reporting!

**Comment by nestorsalceda** [comment]
Fixed!

**Comment by txau** [comment]
@YolandaCHR we've improved our infrastructure configuration and should have solved many of these issues. Lets assume its fixed for now =)
