### ISSUE TITLE
Ensure table view shows all fields correctly

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3197]
Some fields like Rich Text are not showing correctly in the table view.

Please ensure correct display of all types of fields, creating a dummy template with all possible options.

This should be a release stabilization development, please fork from Release.

**Comment by fnocetti** [comment]
It was agreed with @simonfossom that Richtext fields are not to be shown while we figure out a way to display non-plain fields in a consistent way. So probably the fix is to ensure they're not shown. We implemented it but something must have slipped through the cracks.

**Comment by RafaPolit** [comment]
So many decisions made "on meetings".  This probably need to be documented / transmitted better.

I think we could go with a 'strip tags' approach and display rich fields as text-only?  But I agree it can be tricky.

Still, as you mention, at least put a placeholder on those rows saying "click for content" that would show the side panel or something?  Not sure if just excluding the column is the right approach.  Perhaps grey it out so that you know it's there but not selectable?

cc @txau

**Comment by simonfossom** [comment]
@RafaPolit it would be helpful to list what doesn't display right.

On the product call, we agreed on what to show and what not to show. It's all in PRD:
![image](https://user-images.githubusercontent.com/8134850/94011621-f3cebf00-fda7-11ea-8f43-0d98006dcc3a.png)

I thought it would be helpful to drop rich-text field from MVP because it requires 'show more' link and transaction while it by itself is not useful in tableview.

We have all documented in PRD. When I get some time I can mark what still needs to be done.
