### ISSUE TITLE
Unable to import relationships for entities within the same template 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3254]
Partner has reported that if they try to import relationships between entities of the same template, it does not come in. For example, If I try to import a relationship between Victim A and Victim B via csv import, it does not come in despite having the correct columns for the relationship label and linked entities in the CSV file.

**Comment by RafaPolit** [comment]
The problem is that there is no template configuration that would allow this.  Current template relationship properties only allow a different template to be the target for metadata relationships.

Also, since the CSV import can create entities not present on the system for assigning relationships, this would result in entity B being created twice: once because it is relationship of entity B, and another once the CSV reaches the entry line for entity B.

So, even if we allowed same-template relationships on the template, you would need to split the import on batches that don't overlap one another.

This scenario requires a lot of improvement from our side, this won't be possible for quite some time.

**Comment by txau** [comment]
@RafaPolit @natasha-todi I guess this scenario requires some scripting and using the API

**Comment by natasha-todi** [comment]
@RafaPolit @txau thanks for the info!!
