### ISSUE TITLE
"Copy From" presents a blank page if entity has no metadata

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3288]
When accessing the `copy from` functionality, if the entity has no metadata, you are presented with a blank screen, with no information that it has no metadata, no information of the title of the entity you are copying from, and no feedback that all went well, but you just have no metadata.

We should have a blank state, and, given this fact, I believe we should find a UX way of presenting the title, and signaling that it is there for informational purposes, but that we are not going to copy it.  But avoiding the title altogether is confusing.

cc @simonfossom @txau

**Comment by simonfossom** [comment]
Yes, I agree. But that how it is by [design](https://www.figma.com/file/Zw9JkOl11WCgdFfIKugCGy/Uwazi-connections?node-id=406%3A0). I don't know when this change happened. Certainly wasn't there when I was testing it last time. 🤔

By design, you would see all the metadata when you view the entity. That means at least title and template.

There is no blank state. Title and other metadata should be there. We just highlight metadata that will be copied. Were there decisions to change behavior afterward?

![Frame 1148](https://user-images.githubusercontent.com/8134850/98551119-3e939000-229d-11eb-947f-68981bd917ce.png)

**Comment by RafaPolit** [comment]
I think the decisions could or could have not been intended.  I remember conversations regarding how to signal that the title will NOT get copied.

Still, even with title and template shown (which would help a lot), maybe we can put a: “entity has no metadata” or something similar so that it is directly clear that you are not missing info or that you are not waiting for anything to load.

**Comment by simonfossom** [comment]
When user is copying metadata, he's in edit mode. Right panel should show all metadata (filled and empty), same as in left panel. User should knows what is common to both entities. In other words, although we are displaying metadata as view-only, all metadata should be visible - even if empty.
When copying, if some metadata is empty, it should overwrite metadata in left entity as empty. (Unless we want different behavior, but we should discuss this more then.) As far as I see it, user wants to copy metadata as is the other entity. If some are empty, that is what is copied. 
![image](https://user-images.githubusercontent.com/8134850/104456254-b2f1f480-55a8-11eb-8eb3-43c2c5344b29.png)

@RafaPolit @txau @nwyu - Let me know what you think

**Comment by Zasa-san** [comment]
We will now show the entity title. So when there is metadata it will look like this:
![image](https://github.com/huridocs/uwazi/assets/71732018/d0a66333-0645-4dd4-af87-91e74646f6ac)

And when there's NO metadata:
![image](https://github.com/huridocs/uwazi/assets/71732018/3446de55-e904-4a7c-acee-e5bae6bf8bbd)
