### ISSUE TITLE
ability to inherent entity as a select/multi-select list to another entity 

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazi#3305]
**Suggesting** to add the ability to choose template as list in select and multi-select properties without creating relations, to use it for filtering only purposes.

**Comment by txau** [comment]
@agsabbagh you can do that and Uwazi will create the relations for you automatically. These can be used as filters. 

What is the purpose of not creating relationships?

**Comment by agsabbagh** [comment]
No, I want to choose entities of a template as a list in  "select or multi-select" properties instead of Thesauri list. 
The reason is that i have templates related to each other with different types of relations (one to one , one to many , etc) and when creating relations and I want to present on kind of the relations in the relations window and Inherit the others only as filters.

**Comment by txau** [comment]
@agsabbagh in order to use relationships as filters you need to define a new property of the type "relationship" in one (or more) template. This fields allows you to choose the "type of relationship" and optionally the target template. If you configure this property as "use as filter" you should get the result you expect, the resulting filtering interface is the same as selects/multi-selects.

Configuring these fields can be tricky since relationships can have one, two or zero labels defined. So ie. a country can be related to a continent:
- Country --> [belongs to] --> <-- [contains] <-- Continent (two labels are defined)
- Country --> [belongs to] --> <-- [no label] <-- Continent (left side label is defined, but not right side)
- Country --> [no label] --> <-- [contains] <-- Continent (right side defined)
- Country --> [no label] --> <-- [no label] <-- Continent (both labels are not defined)

So you have to be careful when configuring your relationships and fields/filters to make sure the labels match to obtain the desired results.

**Comment by agsabbagh** [comment]
Thank you Jaume for your replay. I know all of this. what I need is ability to choose a template property (title for example) as selects/multi-selects list instead of a thesauri list, or to disable a relation from appearing in the relation window.
This will help me to make basic relations between templates without appearing in the relation window, and preserve the relation property to the advanced ones only.  
I hope you got my idea : )

**Comment by txau** [comment]
@agsabbagh if I am understanding correctly, you want to use template properties in selects and multi-selects instead of relationship fields with the sole purpose of them not appearing in the relationship view.

So part of the problem description would be: I want the relationship view no to show certain relationships that will be displayed only in the metadata.

i don't think we are addressing this approach soon, but we are currently working in a new relationship model that allows user to better configure what will appear in the relationship window, but this is scheduled for sometime in 2021.

**Comment by txau** [comment]
Closing (stale)
