### ISSUE TITLE
Error: Conversion failed in demo instance

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#333]
I have uploaded a scanned case that has been expertly converted by our Library to a very good OCR format. BUT whenI try to upload it I get the error: Conversion failed
![conversion_failed](https://cloud.githubusercontent.com/assets/21119783/17888519/a0bb8d6c-692b-11e6-99b5-4d68ab616575.jpg)

**Comment by txau** [comment]
@YolandaCHR 

We haven't found many documents that fail to convert. Is this a PDF document? Could you share it so we can run our own tests?

Thanks!

**Comment by txau** [comment]
@YolandaCHR I'm sending the doc to our devs for further debugging.

**Comment by YolandaCHR** [comment]
@txau Thank you Jaume - for sure - for ease of future reference, please find it below.
[Onyango_Judgment.pdf](https://github.com/huridocs/uwazi/files/432318/Onyango_Judgment.pdf)

**Comment by txau** [comment]
@YolandaCHR this has been fixed in the next release (which is already deployed in the demo instances).

The source of the problem was wrongly treating a warning message as an error message and prematurely aborting the conversion process. So there was no actual error in the conversion.

On a side note, we have a bug currently affecting OCRed documents: https://github.com/huridocs/uwazi/issues/349

Please let us know if you experience any other issues.

**Comment by YolandaCHR** [comment]
Thanks so much @txau 
I have uploaded it and it is there! 
How do I now delete the ones that says 'conversion failed' - it seems impossible to delete them as it just hangs when I try to open them to be able to delete them?

**Comment by txau** [comment]
@YolandaCHR we are currently working on a better version of uploads that will make the delete option more accesible (we had a bad design idea previously =).

You don't need to open the document in order to delete it, just select the card in the uploads section and mouse over the green floating action button. A "delete" option will appear.

Please let me know if its working.

**Comment by YolandaCHR** [comment]
@txau Apologies - did not see that functionality - still learning the system. It worked! Much obliged!
