### ISSUE TITLE
puppeteer e2e is failing consistently on ci.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3410]
its not failing locally for me but 5 out of 5 runs on ci, and almost all PR are blocked by this.

**Comment by txau** [comment]
@daneryl I'm working on this issue and it is fixed, I was thinking about committing it as a hotfix. 

This was triggered by introducing a change in the e2e fixtures. This is difficult to catch at CI because since the fixtures are a git submodule it can happen that a dev changes the fixtures and commits it to the submodule without committing the needed changes for the e2e test to pass in the Uwazi repo.

It makes me think we should move the e2e tests to another repo along with the fixtures.

**Comment by daneryl** [comment]
> This was triggered by introducing a change in the e2e fixtures. This is difficult to catch at CI because since the fixtures are a git submodule it can happen that a dev changes the fixtures and commits it to the submodule without committing the needed changes for the e2e test to pass in the Uwazi repo.

i was thinking about that, if this happens, then the test should fail on the PR ci right, also the changes are clearly visible on git status, why its easy to forget to commit ?

**Comment by txau** [comment]
> why its easy to forget to commit ?

Because they are two different repos?

**Comment by daneryl** [comment]
> Because they are two different repos?

fixtures is a submodule of uwazi, it means it is versioned with the main repo with a specific commit, a specific pull request should have the specific fixtures version for that PR. when there is changes on the fixutes repo, git status will properly show that there is a change.

if there is new fixtures that a specific PR needs and we forgot to commit the changes then the PR ci should fail, is there any other scenario im missing ?

**Comment by daneryl** [comment]
the problem appears to be that we are not using the versioned submodule of the fixtures on the github action.
https://github.com/huridocs/uwazi/blob/d63ff5b340c13dea18ac97f39eac647c40e16a66/.github/workflows/ci_e2e_puppeteer.yml#L54-L58
