### ISSUE TITLE
Changing property type while reusing title fails

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3418]
Reproduce:
- blank-state
- add a text property (titled text) to default template and save
- edit default template, delete the text property
- create a numeric property and title it "text"
- elastic mapping error appears

**Comment by RafaPolit** [comment]
While the mapping error is unexpected, the actual flow that this process should fail is expected (with the correct error, obviously).

This is due to the fact that entities can already have data for the "text" property, and it should be deleted before having the option to have that property free again for use with a different type.  We could always catch the change internally and address it on the fly, but until that is implemented, the fail should happen.
