### ISSUE TITLE
The date field is saving the incorrect date 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazi#3451]
Partner has reported that when they save dates, the calendar selects their chosen date but the saved date that appears is a completely different one. 
![Screenshot 1_calandar](https://user-images.githubusercontent.com/60774708/105963598-49461000-60a9-11eb-8e59-d9d2d1c31b16.png)
![Screenshot 2_result](https://user-images.githubusercontent.com/60774708/105963603-4b0fd380-60a9-11eb-9707-cbda14e88dc6.png)

**Comment by RafaPolit** [comment]
Well, it's not really a "completely different one", it's the day before.  This could be due to the timezone configuration on the client's machine.  Can you please confirm that the client has the correct date and time and, most importantly, timezone configured in his computer?

Thanks.

**Comment by natasha-todi** [comment]
@RafaPolit yes you're correct, in the one example attached above, it seems its just the day before. As suggested the partner has checked their timezone and has reported back that it is correctly set. Attaching further screenshots (from their public instance) sent by the partner with the comment that this issue is not happening on only one or two entities but on many entities as the date is entered. 

![Uploading Screenshot_20210201_134802.png…]()
![Uploading Screenshot_20210201_134903.png…]()

**Comment by daneryl** [comment]
Our date-picker calculates the timestamp by adding a  UTC offset using ```moment().utcOffset()``` this gives you the current offset, but in another dates the offset can be different, in this particular case for Korea timezone the offset between years 1948 - 1951 on summer (between may and September) was 1 hour more, this makes our date-picker to return the timestamp wrongly, in some cases being a different UTC date.

This is true for any timezone that changed at some point, but not on all cases we see this in the UI because the day does not change necessarily.

this is fixed in this PR #3698, but the timestamps already in the DB which are from this specific dates will be wrong.
