### ISSUE TITLE
Set the base URL for the API

### ISSUE THREAD

**Issue by N07070** [huridocs/uwazi#3455]
Hello,

I'm trying to configure the API access to our UWAZI instance. The current configuration looks like this ; 
 
![Screenshot from 2021-02-02 15-52-53](https://user-images.githubusercontent.com/2259999/106617329-d0dec380-656e-11eb-9135-66809b12f194.png)

We have a domain name in the form `data.example.com`. I would like for the base URL of said API to be something like this ;

![Screenshot from 2021-02-02 15-54-50](https://user-images.githubusercontent.com/2259999/106617516-01266200-656f-11eb-845a-8823268f502b.png)
( Edited with dev tools for the screenshot )

I'm also trying to access an entity that has, in the GUI, such url : `https://data.example.com/en/entity/dtabkjrurnp`

When I try to get it with via CURL, with the following command , `curl -X GET "https://data.example.com/api/entities?_id=dtabkjrurnp" -H  "accept: application/json"`, it fails with such error ;

```
{"error":"CastError: Cast to ObjectId failed for value \"dtabkjrurnp\" at path \"_id\" for model \"entities\"\n    at model.Query.exec (/srv/uwazi/uwazi/node_modules/mongoose/lib/query.js:4351:21)\n    at model.Query.Query.then (/srv/uwazi/uwazi/node_modules/mongoose/lib/query.js:4443:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","prettyMessage":"\nurl: /api/entities?_id=dtabkjrurnp\nquery: {\n \"_id\": \"dtabkjrurnp\"\n}\nCastError: Cast to ObjectId failed for value \"dtabkjrurnp\" at path \"_id\" for model \"entities\"\n    at model.Query.exec (/srv/uwazi/uwazi/node_modules/mongoose/lib/query.js:4351:21)\n    at model.Query.Query.then (/srv/uwazi/uwazi/node_modules/mongoose/lib/query.js:4443:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}%  
```

Is the error linked to the API missconfiguration, or should I be looking somewhere else ? 

Thank you for your help.

----

Technical details ;

OS : Debian Linux

Started with Supervisord ;
```
[program:uwazi]
command=/home/uwazi/.nvm/versions/node/v14.6.0/bin/node /srv/uwazi/uwazi/server.js
directory=/srv/uwazi/uwazi
environment=
    NODE_ENV=production,
    DATABASE_NAME=uwazi_development,
    INDEX_NAME=uwazi,
    LOGS_DIR=/var/log/uwazi,
    LOCALHOST_ONLY=true,                                                                                                                                                                      
    UPLOADS_FOLDER=/srv/uwazi/uploaded_documents
user=uwazi
redirect_stderr=true
autostart=true
autorestart=true
```

**Comment by kjantin** [comment]
Hi! I'm not sure if this will address your question, but we have some documentation on using the API here https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html#how-to-access-the-api-for-your-instance

**Comment by N07070** [comment]
I've looked at the link you provided, but it doesn't seems to change anything. On the other hand, it seems that settings the `LOCALHOST_ONLY=false` env variable lets me do some requests, like the search request, but only via command line and after editing the base url to the real one ( and not with localhost:3000 ).

Also, it sadly fails on using the API via the web interface, as seen below : 

![Screenshot from 2021-02-02 18-36-46](https://user-images.githubusercontent.com/2259999/106639913-bfed7c80-6585-11eb-885b-79a56fe32a3c.png)

**Comment by RafaPolit** [comment]
Good afternoon.

Let's try to break this into two separate issues:
- custom domain name
- API calls

## API Calls

I'll start with the second one, as I think it is the easier one.  Our swagger for the API documentation is, unfortunately, outdated.  I apologize for that.

We have made several changes and are looking into making the API more standard, but, for the time being, I suggest using the client to navigate to your desired data and inspect (as you have done with the devtools to change the value) the network calls.

In this case, if you navigate to `https://data.example.com/en/entity/dtabkjrurnp` as in your example, you will see that among the first calls, you have the call to the `entities` API endpoint with the following form:

`http://localhost:4040/api/entities?sharedId=dtabkjrurnp`

So, the value that you see in the URL is the entiy's `sharedId`, not the entity's `_id` (sharedId is common for all languages of the UI, while _id is language specific).

So, just changing `_id` for `sharedId` on the API call should do the trick in this case.

## Custom Domain

As for the custom domain, what we recommend (and do ourselves) is to configure the service to run on your server as localhost:XXXX (you can define PORT, database name, elastic index name, etc. as per the readme) and then put an NGINX or similar in front configured to redirect calls to `data.example.com` to localhost:XXXX .

If you are familiar configuring NGINX or another load balancer, this should be straightforward.  If you are unfamiliar, we could provide a simple configuration example so that you can build from that.

Let me know if this helps.

Best regards,
Rafa.

**Comment by N07070** [comment]
Hello, and thank you for your answer.

For the custom domain, we are already using Nginx, and configured as you suggested. The question was more about how to make the api page use that domain instead of the localhost address.

As for the API call, I understand better. It wasn't clear what and where to find the `_id` or `shareId`. I would suggest to add a way to get all the information usable by the API for the entities, when possible.

cheers

**Comment by RafaPolit** [comment]
Thanks for the feedback. Yes, we are looking into options and how to correctly document the API.  We are mostly leaning to creating a new v2 API that adheres to a specific standard (JSON API or OData, not sure yet) and that will be correctly maintained and documented.

For the time being, there is no way to replace the localhost with the actual domain in order to properly use the swagger API shortcuts.  The problem is that this swagger definition is so outdated, that even if we fixed the `localhost` issue, most of the endpoints will not work, so not sure if the effort to fix that will have the impact desired.

I'll report and see what can be done, but the immediate answer, I'm sorry to say, is that it is not currently possible to do that, we need to implement the change.

**Comment by N07070** [comment]
Thank you for your answer !
