### ISSUE TITLE
Share with public group (14pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3492]
- Add the public option to the "share with" list of options in the share modal. (Only Admins and Editors will have this option)
- Remove the Publish button from all the context menus.
- This option will use the already existing publish flow, and wont be in the permissions array.

<img width="413" alt="Screenshot 2021-03-02 at 18 19 00" src="https://user-images.githubusercontent.com/948117/109688056-274a1c80-7b84-11eb-9bcb-9c181c4928a5.png">

**Comment by fnocetti** [comment]
This development should include a notice on the modal when the user changes the publishing status (publishing/unpublishing).
I intentionally left it out because the structure behind the current error notice is to be removed in #3570 so it would imply a double work.
I'm updating that issue accordingly, so the notice is included in it.
