### ISSUE TITLE
Card shows property that doesn't exist in the template (demo instance)

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#3501]
Card displays property saying: "Item does not have this property".

![image](https://user-images.githubusercontent.com/8134850/110231931-e7d05700-7f1a-11eb-8c33-aaf518c10f18.png)

**Comment by RafaPolit** [comment]
If you intentionally sort the cards by a custom property, cards that don't have that value will actually say so, so you know that card (or template) doesn't have the property.  This happens only if you have more than one template type selected, and therefore have the option to sort by properties that may not be present on all templates.

This is expected behavior.
