### ISSUE TITLE
Diagnose performance problems on entity save (4 days) (5pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3600]
Some users have experienced that saving an entity takes exponential time based on the amount of relationships it has.
Some processes that save multiple entities (like updating a template) result in an out of memory error for some instances.

We dont know the problem nor the solution so we want to spend some time investigating the issue.

**Comment by RafaPolit** [comment]
Probably related:
#2276
#3378

**Comment by daneryl** [comment]
https://github.com/huridocs/uwazi/blob/32f33ec5e9f167df88bedf664e285c4ca14f0a55/app/api/entities/entities.js#L323
always query/returns all relationship/documents when saving an entity, possible solutions:
- make this optional and do not return by default ? (removing this produces 0 red tests, this suggests that this data is not usually needed when saving an entity)
- do not return realationships and whoever is using this needs to ask for relationships in another way if needed ?

https://github.com/huridocs/uwazi/blob/32f33ec5e9f167df88bedf664e285c4ca14f0a55/app/api/entities/entities.js#L325
- this is called even when there is no need, (no relationship metadata has been changed/send)
- this is still very slow when needed to perform and needs to be remade in order to be efficient and performant ( is it needed to have all relationship/hub loaded in order to perform this process ? )

**the lines above are the main Bottlenecks, both processes end up using **relationships.getByDocument()** which is pretty expensive and loads everything into memory (all relationships of the document), if we have OOM errors during this process, this is the most likely cause**

https://github.com/huridocs/uwazi/blob/32f33ec5e9f167df88bedf664e285c4ca14f0a55/app/api/entities/entities.js#L127
- this changes the label of all the entities that have the saved entity as a relationship
- this is only called when title or icon have changed.
- for entities with a lot of relationships this is slow because after the name change all affected entities have to be indexed

https://github.com/huridocs/uwazi/blob/32f33ec5e9f167df88bedf664e285c4ca14f0a55/app/api/entities/entities.js#L131
- metadata denormalization happens once every entity to sync (once per language configured), the denormalization part of the data
should be identical i think ?, we should be able to reuse it.

## https://github.com/huridocs/uwazi/blob/32f33ec5e9f167df88bedf664e285c4ca14f0a55/app/api/entities/entities.js#L328
- we are reindexing the entity including full text on every save, i think the fullText should not be needed as it can not change by saving an entity itself (needs check)

**Comment by konzz** [comment]
For now we will be tackling only the two first points and we will evaluate the need to further improve performance on entity save. GG

**Comment by daneryl** [comment]
after the introduction of https://github.com/huridocs/uwazi/pull/3602 we have now an even bigger bottleneck here, which actually crashes OOM the server with relatively small entities, this is critical i think and should be solved quickly.

**Comment by konzz** [comment]
Closed in favour of #3702
