### ISSUE TITLE
Render thesauri category when showing metadata (13 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3641]
Thesaurus can have the values grouped in categories, as users we want the category rendered with the values so there is more context for those values.

<img width="392" alt="Screenshot 2021-05-03 at 10 26 50" src="https://user-images.githubusercontent.com/948117/116855736-2c662f00-abfa-11eb-81f1-28c602ef9d31.png">
<img width="395" alt="Screenshot 2021-05-03 at 10 26 58" src="https://user-images.githubusercontent.com/948117/116855741-2f611f80-abfa-11eb-93b1-075f10c8aa9e.png">

⚠️ 
Right now we are denormalising the labels of the values selected, categories will require to be denormalised too

```
[
{value: dj28djh, label: 'Art1', parent: {value: 344sd, label: Laws Chapter 2}},
{value: d2as8d, label: 'Art2', parent: {value: 321sf, label: Laws Chapter 1}},
{value: d2as8d, label: 'Art3', parent: null}
]
```

Updating the thesauri should update the denormalised value, actions like:
- Rename a group

**Comment by RafaPolit** [comment]
@txau @nwyu  After a long discussion, the team is locked into two approaches.  Approach "client", and approach "server".

Most members are inclined to do this in client.  I will briefly describe what we get with each approach and it's (perceived) drawbacks.

## Client

We keep the database structure as is, and use the information already in client to display the parent thesaurus.

This solution meets the requirement described in the issue and is probably faster to develop (there are some of us that believe its not that much faster or even at all to the other option I will describe later).

This approach treats the parent thesaurus as a "presentational value" only.  You will see it on the cards and entity views and side panels as expected, yet, if you search for "chapter 1" as a text search, for example, you will get 0 hits, as that information is not stored on the database or elastic index.  It is just populated on client for display purposes.

This approach does not even modify the reply from the server, so every place that consumes this information will require this client's process to populate the data.  External uses of this data via the API will also require extra requests to get the full picture of the data.

This meets the described issue fully.  With some disagreement, this is faster to develop.

## Server

This means storing the parent data of the thesaurus together with the entity metadata.  This is probably more complex, still some members believe that since we already have this flow working for child values, it shouldn't be too hard to extend the functionality.  Others believe this could, again, open Pandora's box. It has happened before, it WILL happen again!

This process has the advantage including all the data in the reply, so the client needs to just iterate over the values and present them as desired.  It has to do no extra calculation.

This implementation is the only way to actually text-search by the parent label, but this DOES NOT mean that it will just work and that ElasticSearch will magically look into this value.  If that is something we want in the future, it needs to be purposely built to work like that.  It is just that with the first approach this won't even be a possibility.

Other users of the API response will benefit from having the extra data and not having to do extra calls to get the thesauri values.

The real problem is that, as with all denormalized value approaches, if you change the label of a thesaurus, it will need to update all the entities pointing to it, making this process long, hard to implement and, even, error prone if something stops mid-process, etc.  Denormalizing is powerful, but has strong drawbacks.

--------------------------

The team is locked into this discussion.  Some see that, as it is explained in this issue, there is no need to do anything else than the first approach.  It is actually the minimum effort that satisfices the requirements.  Others more prone to over-thinking and over-engineering see more value in doing the second approach. 

We need someone to tell us: "yes, client solution is enough, let's do what is needed to fix this as soon as possible, we will look into the other options at a later date", or "please, do the backend solution even if it could take longer if that risks less chance of having to do this all over again if we, at any point, want to be able to search those values or if there are other API users that could benefit from that info".

I hope I was objective enough to capture everyone's view on this.  If I wasn't, you are free to put on your own views here.
cc. @konzz @daneryl @fnocetti @mfacar @Zasa-san @grafitto @gabriel-piles

**Comment by txau** [comment]
@RafaPolit et all, thanks for synthesizing the problem in such as succinct manner, it is indeed a difficult call. More a wild guess than a strong opinion but I think we should denormalize and send it already cooked from server side:
- It goes in line with our paradigm of denormalization and even if we can't see plenty of advantages on the short term it may come handy downstream (ie. when inheriting thesauri with nested values).
- It can serve as the base for also allowing grouping of relationship fields. We have some of these cases already.
- It definitely allows for eventual handling of these features when searching and filtering.

**Comment by nwyu** [comment]
Thanks for the healthy debate and thorough explanation! I am inclined towards the server approach, for the following reasons:
- Here is a common example of how our partners use nested thesauri. The subcategory only fully makes sense when the main group/label also appears. This text should be searchable.
![1 level grouping](https://user-images.githubusercontent.com/56067374/117613066-8d47b700-b166-11eb-9b19-b4d421e8c4d1.jpg)
- Filter and aggregates work as intended. However, the main group/label is not displayed on the side panel or in entity view, confusing particularly end users.
![Display of grouped thesauri](https://user-images.githubusercontent.com/56067374/117617186-7906b880-b16c-11eb-971b-4fd22b6aefe1.jpg)
- Lastly, even HURIDOCS [events standard format](https://huridocs.org/resource-library/monitoring-and-documenting-human-rights-violations/microthesauri/) includes hierarchical lists of thesauri -- that, too, up to 5 levels of nesting! Several partners have requested further groupings, however for now, the scope of work is limited to the display of the 1 level that we currently offer.
