### ISSUE TITLE
Reset Filter Text Looks Disjointed

### ISSUE THREAD

**Issue by UjoNyawara** [huridocs/uwazi#366]
Probably not crucial, but the section was previously fine. Screenshot attached.

![filters-reset-looks-disjointed](https://cloud.githubusercontent.com/assets/1784894/18021400/d3fa5246-6bef-11e6-8f1e-379069571fbc.jpg)

**Comment by danicatalan** [comment]
This is fixed in the next release, related to #321 card.

We moved the reset button next to the search button, as you can see in this design:

![screenshot 2016-08-27 11 28 29](https://cloud.githubusercontent.com/assets/6364153/18026513/7251991e-6c49-11e6-8616-053a7e63b891.png)

I let this card open until we deploy the next release. In that moment, we can check if it's all right and close the issue.

Thanks!

**Comment by txau** [comment]
@danicatalan I think we can close it since its being addressed in another issue.
