### ISSUE TITLE
Uncaught TypeError: e.selectionRectangles[0] is undefined (1 day timebox)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3754]
When adding entries to TOC, some combinations of document/segment toss the error `Uncaught TypeError: e.selectionRectangles[0] is undefined`.

Ie. in the attached sample document, try to add the title "0.1    Representing word-meaning in vector spaces".

[paper3.pdf](https://github.com/huridocs/uwazi/files/6682279/paper3.pdf)

**Comment by daneryl** [comment]
related https://github.com/huridocs/uwazi/issues/3634

i do actually have PR on the works for that on our text selection library.

**Comment by daneryl** [comment]
> When adding entries to TOC, some combinations of document/segment toss the error `Uncaught TypeError: e.selectionRectangles[0] is undefined`.
> 
> Ie. in the attached sample document, try to add the title "0.1 Representing word-meaning in vector spaces".
> 
> [paper3.pdf](https://github.com/huridocs/uwazi/files/6682279/paper3.pdf)

Im not able to replicate this, i have tried several different ways of selecting the text and everything works properly. i have tried in chrome and firefox.
the only error i can get is a different one if by mistake i select more text including the next page and that is the same error mentioned in the previous comment issue.

**Comment by txau** [comment]
Ok, I don't know how to reproduce exactly, but it is still happening. I've been selecting text here and there and eventually it gets triggered. I think it is related to not only adding entries by drag-selecting text, but also by selecting text with double and triple click, eventually leaves the app in an unstable state.

![image](https://user-images.githubusercontent.com/489831/123977134-f6d08e80-d97b-11eb-8060-e2a282fc720e.png)

**Comment by daneryl** [comment]
apparently i can replicate only on Firefox

**Comment by daneryl** [comment]
> related #3634
> 
> i do actually have PR on the works for that on our text selection library.

it is actually related, in this scenario the "elementTagsToAvoid filter" filters out the elements selected, this filter uses document getElementFromPoint to get the element that contains the text selected, this sometimes returns the containing page element (a div) which is filtered because its on the elementsTagsToAvoid list.

the proposed solution (incomplete) on the mentioned [PR](https://github.com/huridocs/react-pdf-renderer/pull/4) does not filter elements in this way, instead it parses the range document object and returns only text node rectangles, which seems to work in every scenario.
