### ISSUE TITLE
CSV import of nested thesaurus values fails (8 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3764]
If you CSV import an entity with a select or multiselect with the value of a nested thesaurus item, the value appears on cards (denormalized?) but when you edit the entity, it doesn't show on the selectors.

**Comment by txau** [comment]
@RafaPolit do you mean when you are importing a value that is configured inside a group in the thesauri? I mean, that is a pre-existing value.

**Comment by daneryl** [comment]
> @RafaPolit It was my understanding that we never supported the import for nested thesauri items (#3046)?

this is actually not the same case, we do not support creating nested thesauri via csv import, but we should support importing nested thesauri values on the entity import csv.

**Comment by RafaPolit** [comment]
What we are looking for here is the following:
- traverse correctly the root and nested thesaurus values in order to find the match
- the first occurrence that matches, you pick that value, don't worry about possible duplicates or disambiguation... if the user has put two values with the same label, CSV is maybe not the way to go

**Comment by mfacar** [comment]
@RafaPolit I can't reproduce the description of the issue. I'm getting a validation error given that the property with a nested value is passed as null. Is there any consideration to reproduce the problem?

**Comment by LaszloKecskes** [comment]
I've tested something quickly this morning. Since this issue existed before the pre-flight was implemented, we have decided to not  handle nested values in that. The side effect I'm seeing now is that if you have a thesauri like this:
```
value
group
----childvalue
```
then try to import an entity with 'childvalue', the pre-flight does not notice the nested value, picks it up as a new one, and inserts it as a root value, and you end up with a thesauri as:
```
value
childvalue
group
----childvalue
```
This is probably the first thing that needs to be fixed.
