### ISSUE TITLE
Couple of tweaks in filter side bar

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#384]
1. [x] Remove "Document type" label
2. [x] Replace all text under the arrow with (bold) "Select to start filtering"
3. [x] Remove all text under the cross with (bold) "No common filters"
4. [x] Add border-top to the first property. Remove it border-bottom from the last property.
5. [x] Delete **Common filter** title.
6. [x] Fix toggle (https://github.com/huridocs/uwazi/issues/381)

We had some ideas here: https://github.com/huridocs/uwazi/issues/237

-----
![screen shot 2016-08-30 at 15 08 01](https://cloud.githubusercontent.com/assets/489831/18090142/9f2c15fa-6ec3-11e6-8de4-4b92ca83a39a.png)

**Comment by danicatalan** [comment]
All the tweaks are fixed and the facet browsing has been improved (first approach).

![screenshot 2016-09-06 20 33 26](https://cloud.githubusercontent.com/assets/6364153/18286023/37cf85c8-7471-11e6-85d4-15245dc32ee7.png)

@txau I will not close #237 because we can merge #403 to close this card now - but we can still improve more the facet browsing in other iterations.

**Comment by txau** [comment]
Closed in #403
