### ISSUE TITLE
Include all text fields into full text search

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#385]
Full text search is currently only acting on document contents and titles. We should automatically add all text fields to elastic.

**Comment by danicatalan** [comment]
I have some questions I want to discuss with the team about this. Maybe we should split it in two or three issues, but lets see how the conversation evolves before next steps.

This is our current implementation for **full text search**. The app search through documents matching the text with the queries and showing the first snippet. Other snippets can be found on the right panel. All the keywords that appear in those snippets are highlighted in yellow.

![highlight-fulltext](https://user-images.githubusercontent.com/6364153/31330770-ff789c66-acdf-11e7-86ef-50b4e6d11e07.png)

As we are searching inside the document, we are not able to reach entities unless the keywords are on the **titles**. This brings the first issue, we are not highlighting titles. This can be trivial, but if we are going to start searching on properties I think is worth discussing if we want to highlight titles for consistency. We need to think if highlights also affects sidepanels.

![highlight-title](https://user-images.githubusercontent.com/6364153/31330899-84c2c360-ace0-11e7-978e-9762d4820e49.png)

And now, the problem we want to solve in this specific task is those entities outside the scope of query searchs because the keywords are not inside the title but maybe in Texts or Rich texts fields.

Here we have again some points to discuss:

- If the property is marked as "Show in cards", there's no problem: the matching text will be highlighted on the property.
- If the property is not marked as "Show in cards", there are some options:
  - a) Do nothing but showing the card (without feedback for the user).
  - b) Showing the card with a character limit (this is tricky if the keywords are repeated different times on the field).
  - c) Showing the card with the full property displayed.
- Like titles - should the keywords being highlighted on sidepanel? I think this is not necessary if we choose the option c, but it's mandatory on options a and b to provide feedback to the users.

![highlight-title-richtext](https://user-images.githubusercontent.com/6364153/31331315-167dc29a-ace2-11e7-8e02-f81e39159e03.png)

**Comment by RafaPolit** [comment]
Here are my thoughts:
- I would avoid highlighting in the side panel for the time being.  Maybe later on, not now.
- I'm in favor of highlighting the titles on the cards for consistency
- I think that we can split the highlighting of other properties into: rich text and the other text fields.  For text fields, show the entire field.  For rich text we use the same 'snippet' approach and show ... text ... people will know its a fragment of the text.
