### ISSUE TITLE
public form does not work properly on a private instance. [Timebox]

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#3852]
to replicate:
- set up two private instance.
- ? sync them
- set up a remote public form one to another.
- use the form.
- session is lost.

the bug is that the session is lost every time you send the form, the form is sent succesfully.

**Comment by salvalacruz** [comment]
Apparently, this problem does not exist when using forms in private instances, if this instance is not synchronized.
If anyone want to try , I can test it with him/her.

**Comment by daneryl** [comment]
@konzz did you try this on an nginx/multitenant environment ? i think you mentioned this.

**Comment by mfacar** [comment]
The issue is reproducible in a multitenant environment, although the session is not deleted, it's being updated without the userId, this is because when the tenant is different than the existing in the cookie, we are deserializing the user as 'false'; given that the session Id belongs to the source tenant, this is updated as part of the passport management.
cc. @daneryl, @konzz
