### ISSUE TITLE
Diagnose entity deletion flow [Timebox 1 day]

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#3882]
Currently, deleting entities can still result in:
- an entity being deleted from DB
- the process stopped somehow in the middle of the process and further transactions are not carried out: deleting relationships, reindexing ES
- This leaves relationships to missing entities which throws endless notifications of errors

We need to, at least, replicate the error by throwing within the entity deletion flow so that we can reproduce the problem, and them, from that, revert the flow and, as a first approach, first delete relationships and then delete the entity.

This could also be that it is failing in the middle of deleting relationships and some are left there, so this requires some research into.

**Comment by txau** [comment]
Are these related? https://github.com/huridocs/uwazi/issues/3358 https://github.com/huridocs/uwazi/issues/3354

**Comment by mfacar** [comment]
It wasn't possible to replicate the error without forcing an exception in the middle of the process.

Throwing an exception between the `entity delete` and `relationships delete`, replicates the error at select or viewing the target entity of the relationship. However, in a bulk deletion, the error doesn't affect several entities because the process stops at a first error. 

#3905 was created to address the order in the deletion flow
#3906 was created to remove the orphaned connections coming from the error at the deletion process

**Comment by mfacar** [comment]
Closing in favor of #3905
