### ISSUE TITLE
Upload image on entity edit /creation. (20 pts)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#3899]
Depends on: #3901
To improve the entity  edit / creation workflow, the users should be able to upload images from their computer and be saved as suportig files. On the issue [Image and Media Field revamp (30pts) #3494](https://github.com/huridocs/uwazi/issues/3494) we left out this part.

<img width="1149" alt="Screenshot 2021-09-07 at 10 09 22" src="https://user-images.githubusercontent.com/948117/132310015-831294fe-ad73-4c73-8741-6e3c659365ea.png">

Identified tasks:
- Update entities endpoint to be able to receive attachments
- Update entities metadata form to handle these attachments

Designs:
https://www.figma.com/file/xjsz7r65epN4B0b96zilac/0-uwazi-redesigns?node-id=1335%3A6

**Comment by Zasa-san** [comment]
I've reached an impasse on this issue while implementing the identified tasks. 
The possibility to add attachments during edit or creation of an entity has a few difficulties that stem from the normal workflows for supporting files. Users could add files, rename them, removed them, and even change existing ones if editing the entity. This means that this actions don't immediately save the supporting files, but all of them happen after the users clicks the 'Save' button en the entity edit/creation form. Is it expected that users can do all of this actions during edit/creation? 
The complexity of the development may vary based on this. There is also a complication if users should be able to use those supporting files that they add during edit/creation to fill image fields, since the files are not yet saved but are somewhat provisional until the users effectively hits the 'Save' button.
@RafaPolit @nwyu @txau

**Comment by txau** [comment]
@Zasa-san It seems to me that we need to cover all of these scenarios. The most important one is adding a new file and using it in a media field. After reflecting on it I think the way forward is to keep a client side state of the files collections that gets persisted one the entity is saved.
