### ISSUE TITLE
Uwazi Set Up

### ISSUE THREAD

**Issue by blesskn** [huridocs/uwazi#4046]
Good day. I have installed all the dependencies for Uwazi. What is the next step. I kindly want assistance for the process.

Best regards

**Comment by txau** [comment]
Hello @blesskn , did you follow the instructions in the readme? https://github.com/huridocs/uwazi#installupgrade-procedure

**Comment by blesskn** [comment]
Thank you for your response. Yes, I followed the instructions but i'm failing to understand the process. Is there a video to make me understand all the steps. I wanted to work on my local server (my computer) but Is it ok if I send my domain cpanel details then from your end install the program in the system then I work online. I look forward to hearing from you.

**Comment by txau** [comment]
Dear @blesskn in order to install Uwazi on your servers you need some minimal system administration skills. The instructions we provide are sufficient for technical users to perform on their on.

If you need personalized technical support, please get in touch at support@uwazi.io and one of our project managers will help you. 

If you just one to try out Uwazi and have it hosted somewhere, I suggest you request an instance on our servers via the contact form at the bottom of https://www.uwazi.io . That way you will get rid of the technicalities of installation and also benefit from high availability infrastructure, automated backups, hardened security, SSL, etc.

**Comment by blesskn** [comment]
Thank you
