### ISSUE TITLE
Query help

### ISSUE THREAD

**Issue by justinbalaguer** [huridocs/uwazi#4077]
`https://<domain-here>.uwazi.io/en/library/?order=desc&q=(allAggregations:!f,from:0,includeUnpublished:!t,limit:30,order:desc,sort:creationDate,types:!(%2761b19a8406d25349e12241d1%27),unpublished:!f)&search%3Flimit=10&sort=creationDate`

heres the link when I try to search want I want to get in the library. how can I query them put it in url in the `<Query />` component?

**Comment by RafaPolit** [comment]
You will find most of what you need here:
https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html#query-component

The problem here is that you are pasting here a URL for presenting a web page, yet you need the API call that returns the results.  We should provide a "copy this API call's URL", but, for the time being, you would need to a small "reverse engineering" to learn what API call to the `/search` endpoint you need to pass to the `Query` component.

- Open Uwazi to the URL you pasted using Chrome (you could do this with Firefox, but instructions would differ a bit) 
- Open the Developer Tools by pressing `F12` on your keyboard
- On the top section of the dev tools (the menus), click on `Network`
- Click on a new filter checkbox item (you will remove this later this is just temporary to trigger a new request)
- Clear anything that may be there by clicking on the `Clear` icon on the second row of items (the "do not" icon next to the red circle)
- You should see a blank area with no network requests
- Now un-check the "extra" filter you selected, returning you to your original query
- In the dev-tools area, you will get two, three or more requests, find the one that starts with `search?` and click on it
- The right section will now show you the values for the request.  We want to go into the `Headers` tab (should be selected), then into the `General` section (first one from the top) and you want the `Request URL` value.  It will look something very similar to what you posted, but with a slightly different syntax.  Something like: `https://<domain-here>.uwazi.io/api/search?allAggregations=false&from=0&includeUnpublished=false&limit=30&order=desc&sort=creationDate&unpublished=false&include=["permissions"]`.  It will have a few different values depending on the filters you have selected.

That gives you the value you are looking for.  You can omit the first part of the URL and start with the `search?...` section.

It's not pretty, but once you get used to it, it's more or less straightforward.  Hope this helps.

**Comment by RafaPolit** [comment]
If this does not work or you have further questions, please reopen the issue.

**Comment by justinbalaguer** [comment]
sweet that solves it thanks a lot.
