### ISSUE TITLE
i18n =)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#415]

**Comment by danicatalan** [comment]
New view on settings where the user can check and manage interface languages and metadata translations.

![screenshot 2016-10-01 12 07 46](https://cloud.githubusercontent.com/assets/6364153/19013390/b0242134-87cf-11e6-9b64-997416341a9b.png)

When the user clicks on Translate button, a new view is opened with translation form (I'm working on that right now). I added a % of translation in that button, so users can check the status of every item. I think a percentage of Total inputs / Empty inputs will be enough, but we can skip this right now and focus on other parts of i18n.

**Comment by danicatalan** [comment]
This is the translation interface. I think this need to be as similar as possible to the metadata editor, so we need to maintain some items (as icons for every property) if we can.

![screenshot 2016-10-01 16 19 31](https://cloud.githubusercontent.com/assets/6364153/19014716/d5506768-87f4-11e6-98b1-a0a36339b43e.png)

I also think it's not good to let users change the source text inside languages. It's better to force users go to the proper section to change it. That way we keep Languages and all the translation system decoupled from the rest of the app.

We can add some alerts or notifications inside the other sections as a feedback for the users to now that they may need to perform some translations in this section.

**Comment by txau** [comment]
@danicatalan great. I thinks this covers everything we discussed. Some annotations though:
- Remove the % translate thing. We will revisit that idea sometime.
- Don't forget to add the translations for the interface as well.

**Comment by danicatalan** [comment]
I have serious doubts about this approach for the System translations. I can't imagine a new user creating a new language and translating every string without seeing the interface context.

It think it can be good to edit strings in some cases (for example, if we provide a Spanish translations where _Connections_ is translated as _Conexiones_ and someone wants to change it for _Relaciones_ because it has more sense in other background) but it's dangerous to let the user change every string. Maybe we are adding more noise to the system, and not giving enough value.

However I think it's not a huge pain because we must keep all the translations encapsulated in one section. That way we remove a lot of noise in other settings pages and the admin keep focus on creating useful content (and translation of content can be delegated to a translator allowing access to that section).

![languages-page](https://cloud.githubusercontent.com/assets/6364153/19160349/d6de9bb4-8bef-11e6-9dd4-7cabb9a8b146.png)
![languages-interface](https://cloud.githubusercontent.com/assets/6364153/19160348/d6db66ec-8bef-11e6-8dd9-39708200aa5f.png)
![languages-metadata](https://cloud.githubusercontent.com/assets/6364153/19160350/d6df0f36-8bef-11e6-9e46-8d0b92eaeda0.png)

**Comment by RafaPolit** [comment]
@txau @konzz @daneryl :

Server tests are failing in **app/api/templates/specs/templates.spec.js:140:46**.

The file **app/api/templates/templates.js** has an orphan function named **updateTranslation** which is what the test is expecting to have been called, yet it is not used anywhere.

The branch has been rebased with development, please delete local branch and pull new branch to avoid conflicts.
