### ISSUE TITLE
Inability to edit the public instance

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazi#4213]
1. I edit the text of pages in the frontend and in the preview everything works well, but all the edits are not reflected on the interface (the public instance) as shown in the attachments below.
![Frontend](https://user-images.githubusercontent.com/95572565/151948737-177d6226-96fe-471a-a9bd-241b9f016e38.png)
![Backend](https://user-images.githubusercontent.com/95572565/151948744-9dc47731-520a-45ba-abe8-342fcb298f12.png)

2. The error message shown in the attachments is still display on many devices connected to different networks, so it seems to be an error in the public instance.

**Comment by txau** [comment]
@AhmadQadi1 regarding point 1, do you hit the "Save" button at the bottom of the page? Does it give any error?

Point 2 is just a message indicating that in that particular moment the server is not reachable. This happens when there are connectivity problem but also when we restart the service to release new versions of Uwazi. Normally you don't need to worry about that message unless when it is too frequent.

**Comment by AhmadQadi1** [comment]
1. When I save, it's saved successfully, but still nothing changes in the public instance.
2. The message mostly exists all the time.

**Comment by txau** [comment]
@AhmadQadi1 I logged into your instance and successfully edit that page and the connection message is not appearing. The fact that these two symptoms are happening together makes me think that this is a connectivity issue on your end. 

Apart from the connection quality, it could well be that you are connecting from an unusual setup such as load balancing via different providers or some circumvention measure such as VPN with dynamic routing.

Another possibility could be that you were performing the page edition while we were deploying a new version of Uwazi, which may have caused some friction.

> When I save, it's saved successfully, but still nothing changes in the public instance.

Make sure you refresh to discard any possible browser cache or similar. Keep in mind that when the browser is not able to connect it is more likely to received a cached version of the page. The preview works locally so it makes sense that you see the change when previewing but then the browser was not able to commit the changes to the server.

> The message mostly exists all the time.

This message appears when you browser app cannot reach the Uwazi server. It can be because the server is not available at that moment or because you connection is flickering. It also automatically detects when the connection has been reestablished and the message goes away automatically.

Is the problem still persisting or was this a one time thing?

**Comment by txau** [comment]
Closing for now. Let me know if the problem persists.
