### ISSUE TITLE
Sort by inherited property

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4225]
Inherited properties do not appear as sorting option.

**Comment by txau** [comment]
Same as https://github.com/huridocs/uwazi/issues/4065

**Comment by RafaPolit** [comment]
We almost implemented this in V2, but where unclear on certain scenarios:
- Do we enforce that, if you select to sort by a property that is being inherited, you are sorting by its label?
- The above question is relevant because you, as an API user, could want to sort by the inherited entity label, or id, or by the inherited property label or value.  So, forcing ONE of those, from an API perspective, was not clear.  Which brings us to the next point:
- From the client perspective, probably yes, we want that sorting.  But our option was to do something like `sortBy: 'metadata.inheritedProperty.inhertiedValue'`.  And this was coupling to our current data structure, which we know are prone to change.

So, we need to find a way to signal out which part of the property we want to sort by, without coupling to our current structure.  It was not clear how to proceed.  Further discussion is needed.
