### ISSUE TITLE
Be able to condition page templates to a particular value of the entity (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#4231]
This would allow to use different templates depending on the actual content and a more fine grained control over custom pages for templates.

Another approach that could be even better is to have conditional blocks as page tags. Something like:
```
<renderIf property="some property name" has-value="some expected value">
  Other code and elements here
</renderIf>

**Comment by RafaPolit** [comment]
We use "sift" in Sync, which would be a great fit here.  https://www.npmjs.com/package/sift

The string could be ideal, as it would allow to "filter" out based on several properties, different values, absence of values, and any other complex scenario that you could think of.

I think the most versatile solution would be to have a single page per template, and then configure that page with conditional sections instead of allowing different pages according to conditionals.

We could have a `<Section>` markdown that has a `showIf` property using a sift string on the entity: `<Section showIf="{title: "%pass%}>`

In that way you could have two or more completely different pages based on whatever the entity contains.

This also allows to show or hide entire sections based on conditionals: only show `place of burial` is `status is dead`.  For example.
