### ISSUE TITLE
URLs appending of page/page/page....

### ISSUE THREAD

**Issue by YolandaCHR** [huridocs/uwazi#428]
Thanks for the adding of pages and menus. Not sure if they were there before but glad that is up!

I just noticed that the url generated is not a very friendly url and was wondering if that is something that can be looked at?

Also when clicking the one link after the other, it appends the url in the navbar like so below:
(with each click on the menu item, another '/page' is added in the url)

**https://pretoria.uwazi.io/page/page/page/page/page/page/page/page/page/4db5883ef6e4fc7cdbcdf8f715041f23**

**Comment by txau** [comment]
1. Regarding the friendly URL issue check my comment in https://github.com/huridocs/uwazi/issues/435

2. Right now, this can easily be fixed by adding a "/" at the beginning of the URL. So instead of "pages/something", make it "/pages/something". We known we need to improve several aspects of how URLs work across all the application. We hope to have some time to change this soon.

**Comment by YolandaCHR** [comment]
Great thanks @txau - understood.
Adding the '/' works with the appending of page.

**Comment by txau** [comment]
@YolandaCHR reopening. I'm actually going to keep this one on the backlog so we fix these issues soon =)

**Comment by YolandaCHR** [comment]
100%
Thought #435 would suffice. No worries!

**Comment by RafaPolit** [comment]
Closing in favor of #435
