### ISSUE TITLE
Duplicate label warning messes up view on Template Creation

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#446]
Duplicate label warning messes up view on Template Creation:
![screenshot from 2016-09-22 10-20-15](https://cloud.githubusercontent.com/assets/4309019/18754430/410d3d30-80ae-11e6-8b6c-8afd23473af2.png)

**Comment by txau** [comment]
Duplicated https://github.com/huridocs/uwazi/issues/292

**Comment by danicatalan** [comment]
I checked the label position and now it doesn't overlap with other content:

![screenshot 2016-11-02 16 16 42](https://cloud.githubusercontent.com/assets/6364153/19934657/bc44a09a-a117-11e6-8c37-65802304e6d6.png)

**Comment by danicatalan** [comment]
We are thinking about getting a new approach to this with the duplicated label feedback next to the title.

![screenshot 2016-11-03 13 45 31](https://cloud.githubusercontent.com/assets/6364153/19966390/df1ac590-a1cb-11e6-9e67-f87111e3d49f.png)

The problem is this feedback element is inside the component who renders that metadata form. This would need to be placed on other component (I think is MetadataProperty) to render the feedback properly next to the title and both properties.
