### ISSUE TITLE
Refresh a little bit uploads' CSS

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#510]

**Comment by danicatalan** [comment]
I think this is the first step we need to achieve in order to clean uploads.

![screenshot 2016-10-25 18 08 17](https://cloud.githubusercontent.com/assets/6364153/19694446/a5fbcf22-9adf-11e6-8ff8-d774b04ab263.png)

This will only need a developer for connect the item-type tag. I've change the item-type-0 (default state) to render with empty background and grey border because I think it's a good hint for the user to let it know that they need to fill this field.

This changes are on branch https://github.com/huridocs/uwazi/tree/510-uplodas-v3.

After this step, I suggest to improve the cards action button to something like this:

![screenshot 2016-10-25 18 25 12](https://cloud.githubusercontent.com/assets/6364153/19694694/ab0d354a-9ae0-11e6-99f3-c7e08b69e109.png)

It's cleaner and works because now it's redundant to see the same status message in every card. All the user needs to know is that there are three possible states: red (error), yellow (warning) and green (success). When the user clicks the button, the modal still opens, so the feedback it's pretty good for him. However I think we need to add a note on the sidepanel with the upload status message, maybe below the title.

And by the way, I'm going to upgrade the sidepanel with footer and header like we talk in our last meeting, but I will made this changes in other branch because they can be fixed in separate paths and it will be easier to track changes with different branches.

**Comment by txau** [comment]
@danicatalan ok. Looks great. I'm assigning finishing this one to a @konzz
