### ISSUE TITLE
Show all languages in the language selector. Fold if mobile.

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#511]

**Comment by danicatalan** [comment]
@txau this was throwing 3 test errors because of a change on functionality.

![image](https://cloud.githubusercontent.com/assets/6364153/19646797/6be731bc-99fb-11e6-837f-ba320c7816aa.png)

I've updated the specs (https://github.com/huridocs/uwazi/pull/520/commits/aa17ae0744bf6f4d5e7b71978620dc79a8ea3bbd) to match the new markup and pass all the tests.
