### ISSUE TITLE
Improve "unpublished" visuals

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#532]
![screen shot 2016-10-25 at 00 36 34](https://cloud.githubusercontent.com/assets/489831/19666778/ec69ca7e-9a4c-11e6-98d9-4acc1901c2ac.png)

**Comment by danicatalan** [comment]
I worked on a simple solution that I think it works pretty well: just add a "private" icon next to the title.

![image](https://cloud.githubusercontent.com/assets/6364153/20764277/cd1e6bc2-b72d-11e6-925b-0915f6fa4a05.png)

We can use this icon inside our uploads section without adding noise to the UI. Besides reinforces the sensation that this section is private, because you see the lock in all the cards - I think is silly and a great improvement in this section.

![image](https://cloud.githubusercontent.com/assets/6364153/20764661/835054c2-b72f-11e6-85c6-b3db170865b5.png)

I've made a little improvement to clean more this section. The "Ready to publish" label was very redundant, so now this label is a button - like other actions.

![image](https://cloud.githubusercontent.com/assets/6364153/20764315/f66cd5cc-b72d-11e6-877c-ee644356c3d8.png)

We can improve dangers, warnings and processing feedbacks in a new issue to continue improving this section.
