### ISSUE TITLE
Improve connections panel

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#582]
- [x] Improve expand/collapse connections.
- [x] Allow user to order by property.
- [x] Show metadata (like library).

**Comment by danicatalan** [comment]
@RafaPolit is going to create a component to render the cards on library and sidepanel because now is not reusable and things like inject metadata on the connections panel is not possible until this is done.

**Comment by RafaPolit** [comment]
The basic functionality of the isolated component is now finished.

There is one particular issue which is critical (library is NOT afected by this issue):

When fetching references, the metadata is NOT sent by the server to avoid high bandwidth usage.  I have implemented a solution that makes one request to the server for each reference in order to populate the metadata on the cards.

A further problem with this approach is that, for documents, the entire FullText property is also being sent FOR ALL THE DOCUMENT REFERENCES, so this will result in very long loads with unnecessary bandwidth usage.

We either need to include the info on the references, or make a new view on the server which only sends the most basic info to avoid problems.  If every place that shows references will show the metadata, it would make more sense to implement the first approach.

I would like to discuss this with @daneryl to choose the best course of action.
- [ ] Talk to @daneryl 
- [ ] Implement best course of action
- [ ] Test abstracted component once the action is defined

**Comment by RafaPolit** [comment]
Resolved as part of #590
