### ISSUE TITLE
Opening a document is not so obvious

### ISSUE THREAD

**Issue by whyfrycek** [huridocs/uwazi#599]
When accessing a document, there is only a download button on the right panel, but no way to open the document. Maybe this would be helpful?

**Comment by danicatalan** [comment]
Thanks for the feedback @whyfrycek.

It seems a great idea for guest users, maybe for admins its more annoying because they have a lot of buttons on that menu when ther are logged.

I will discuss this with the team and I will notify you for possible changes.

Thanks!

**Comment by txau** [comment]
@danicatalan we've mentioned this in the past. I think we should add that button.

**Comment by whyfrycek** [comment]
Yeeeessss! Give me the button :)

**Comment by whyfrycek** [comment]
Thanks guys for taking this on, re

**Comment by danicatalan** [comment]
I have placed this icon on **MetadataFormButtons.js|18**, but we need to modify some things in order to deploy this into development:

- [ ] Include URL to open document/entity when user clicks the button.
- [ ] Hide button if user is on document/entity viewer.
- [ ] _Nice to have_: I think we need to create a new task to get attachments tab on library. When the user is logged, there are 5 buttons on this menu: open document, edit document, download document, reupload document, delete document. If we include attachments we will be able to move download/reupload document out this menu. That would be awesome from UX perspective.

**Comment by txau** [comment]
Isn't the attachments task already created and you are working on it? https://github.com/huridocs/uwazi/issues/598

**Comment by danicatalan** [comment]
I've added that feature into the issue's scope. Thanks!
