### ISSUE TITLE
Improve "Open document" icon in cards

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#638]
Some user have reported the functionality is not easily intuited by the UI design.

**Comment by danicatalan** [comment]
Related to #580

**Comment by danicatalan** [comment]
Can we trigger this action with a double click?

**Comment by txau** [comment]
We could. Anyway I think we need to change the icon. Maybe a document icon?

**Comment by danicatalan** [comment]
I worked on three states: **default**, **hover** and **selected**. The open document button remains displayed when users hover cards or open the metadata panel.

![screenshot 2016-11-22 17 35 21](https://cloud.githubusercontent.com/assets/6364153/20532417/2fe0109e-b0da-11e6-8b22-e64d02b12427.png)

I decided to try on white because the default primary color (blue background) was very distracting when the user navigates through the app. In our clean UI, that colour change gets to much distraction. However I think is a good idea in this case to keep the action colour (blue, red, green...) when the user hover its, reducing distraction and focusing on the main action.

![screenshot 2016-11-22 17 35 34](https://cloud.githubusercontent.com/assets/6364153/20532416/2fbe3e9c-b0da-11e6-9c3a-8bf45d2ace0c.png)
