### ISSUE TITLE
Glitch in tooltip rendering

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#650]
As you can see it gets partially covered by the right content.

![screen shot 2016-11-22 at 00 42 55](https://cloud.githubusercontent.com/assets/489831/20505373/b0cf01da-b04c-11e6-82f0-77f59f39cb13.png)

**Comment by danicatalan** [comment]
I've checked this and there's no way to solve this just on CSS because of `overflow` behaviour. As soon as you put the scrollbar on the sidepanel, everything that goes outside its area acts as `overflow: hidden`, so the tooltips can't be rendered outside the sidepanel.

I think JS to solve tooltips position it's a bad idea. Maybe the smarter solution is to get mobile styles on the sidepanel, because the behaviour is similar in both cases (just one column, card after card, almost the same width...).

![image](https://cloud.githubusercontent.com/assets/6364153/20675504/d81c732c-b58c-11e6-8b10-eed2c399a85d.png)

We can spend time improving the title position and render in both cases (mobile and sidepanel).

**Comment by danicatalan** [comment]
I've created a new tooltip that doesn't go outside the sidepanel:

![image](https://cloud.githubusercontent.com/assets/6364153/20706991/252f3134-b62a-11e6-8c0c-ee4cac1bb539.png)
