### ISSUE TITLE
Users need to configure default order and sorting of the connections panel

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#698]
Users want to be able to select which connections will appear first and what the sorting will be for this panel. Lets discuss this story soon.

![screen shot 2016-12-06 at 14 33 15](https://cloud.githubusercontent.com/assets/489831/20927267/0bb00728-bbc1-11e6-8d67-a593b55be4c6.png)

**Comment by danicatalan** [comment]
This issue is more complex than we discussed, but I'm trying to break in pieces to understand how we can improve the settings workflow.

First thing I studied is how we let users set a property as sortable. Now is well integrated on _Settings > Metadata_, but it's quite difficult to see how many properties are capable to be use as Sortable. This also affects to Filtrable properties, so I think the best approach is to remove both of them from this and move it everyone on a proper page.

![screenshot 2016-12-13 18 52 38](https://cloud.githubusercontent.com/assets/6364153/21152170/8657b152-c165-11e6-943d-ce059f39e5ff.png)

For Filtrable results, we have a **Filters** section on settings. My approach is to set all properties as filtrable by default, until the admin sets the configuration here. Once he starts dragging types, all properties that match are shown below, on Filtrable properties. As soon as he drags another type, this lists is updated with new properties and show the matches, similar as we show now on Metadata section (I didn't work on styles right now).

I think this approach is helpful for advanced datasets. We asume that little datasets (with just a few document and entity types) doesn't need this tool and all properties can be filtrable. We can modify this section with a blank state (so if the user doesn't have any type selected, all properties are shown in the bottom box).

![screenshot 2016-12-13 18 37 12](https://cloud.githubusercontent.com/assets/6364153/21152168/8656ba9a-c165-11e6-96a5-257c2bec130f.png)

![screenshot 2016-12-13 18 36 35](https://cloud.githubusercontent.com/assets/6364153/21152167/86541902-c165-11e6-9069-93ba8f1927cd.png)

With this approach to Filtrable types, the **Sortable types** comes easy with this section.

All properties that can be sortable (I think text based and date based ones) appears here. The admin can view in just one page all the properties, so it's easier to manage that when he needs to review document by document how many properties they have, and also its very easy to set a property has default on library and connections.

I didn't design a flow to select default properties to every document/entity because I think we need an easier approach in this step, but if we need to go onto this, I can extend this view to another more complex.

![screenshot 2016-12-13 18 50 26](https://cloud.githubusercontent.com/assets/6364153/21152169/86572e8a-c165-11e6-9d7c-17c997c839c7.png)

**Comment by txau** [comment]
- Remove "Sortable" from metadata configuration.
- If the property is marked as "Use as filter" then is automatically sortable.
- If is marked as "Use as filter", then unblock an additional option to make it "Default sorting".
- Only one filtrable property per entity/doc can be marked as "Default sorting".
- Both in library and connections panel, properties compete to impose their sorting criteria. The more entities/docs have the same common filtrable property marked as default sorting, the more weight they have to impose their sorting criteria.

**Comment by danicatalan** [comment]
What do you think about this approach? We use descriptions to explain each configuration and seems more understandable.

![screenshot 2016-12-21 17 48 54](https://cloud.githubusercontent.com/assets/6364153/21397934/df36f9a4-c7a5-11e6-87a5-19e3b8f04d8f.png)

The suggester will work better with thesauris too.

![screenshot 2016-12-21 17 49 25](https://cloud.githubusercontent.com/assets/6364153/21397933/df36922a-c7a5-11e6-969b-0eff6f63e392.png)

**Comment by txau** [comment]
- Label is "Priority sorting" instead of "Default sorting"

**Comment by danicatalan** [comment]
- [ ] Check abled / disabled **Set as priority sorting** styles.
- [ ] Review table styles (example: when two properties has the same name but different type, it must paint it red).

**Comment by danicatalan** [comment]
@RafaPolit keep in mind that this issue is related with the above one (152) so we need to discuss which order we are going to follow before start resolving them.

**Comment by danicatalan** [comment]
I just talked with @RafaPolit about priority sorting and we decided to not restrict admins to select one priority sorting property. When multiple properties of the same document are prioritised, the first one is the winner (we can improve this in further stories). When there are more than one document, all properties start fighting and the system starts to get more intelligent.
