### ISSUE TITLE
Rethink side panel icons

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#699]
Particularly the connections one is the standard for sharing. This is misleading:

![screen shot 2016-12-06 at 14 42 29](https://cloud.githubusercontent.com/assets/489831/20927526/594cd582-bbc2-11e6-9246-648c931efb93.png)

**Comment by txau** [comment]
@danicatalan use the same icon for table of contents you used for the document viewer:

![image](https://cloud.githubusercontent.com/assets/489831/21936671/621f1392-d9b2-11e6-9bd9-c629cfe7349c.png)

**Comment by danicatalan** [comment]
I changed the icons on #425 but we can keep the discussion here.

- [ ] For TOC, I think the P icon is not very representative, so I decided to change it with an **A** to show that this tabs is the most related to the text. Also, we are going to use TOC as default tab for de document, so it's logic to use it as our primary tab for reading the text (and not just as "Table of Content").
- [ ] For connections, there is no perfect icon to reflect a connection, but I think this one is quite interesting, because it reflects multiple arrows in different directions, as our connections.

![document-toc](https://cloud.githubusercontent.com/assets/6364153/22181661/e24c81be-e090-11e6-947e-634b91f76e22.png)
![document-connections](https://cloud.githubusercontent.com/assets/6364153/22181662/e2717f5a-e090-11e6-97bf-c88e280acec0.png)
