### ISSUE TITLE
Mass deletion of documents

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#788]
I have uploaded a big number of documents on the Humphrey instance, but a big of these (haven't counted) did not upload properly but they keep showing on the upload page. I can only delete one after another. Is it possible to delete them (the ones not uploaded ONLY) all at once?

**Comment by danicatalan** [comment]
Unfortunately is not possible to perform this action right now because we can modify just one file at a time. The good news: we've been starting to work on mass modification of documents so you will be able to delete them all at once soon.

Thanks for your feedback @HSips, we will keep you informed.

**Comment by HSips** [comment]
Thanks Dani. It's not urgent as I still have many docs to add metadata.. looking forward!

**Comment by kjantin** [comment]
This will be resolved in #806
