### ISSUE TITLE
Use Title as default sorting for new instances

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#791]
We always used **Date added** to order documents chronologically in our libraries. I think this is because the natural process of adding documents on Uploads and publish them into the library seems pretty obvious for admins.

However for new users and visitors, it makes no sense - especially when the **Date added** appears in all cards with no reason (they need to see that all documents are sorted by this property to understand what they are seeing). This is fixed when the admin sets some **Priority sorting** rules, but by default it seems pretty confusing.

I think we need to change from **Date added** to **Title** to sort library results by default.

This is related to #790.

**Comment by RafaPolit** [comment]
Just a small note: this does NOT change when priority sorting is configured.

Priority sorting at the moment works like this:
- Can I keep the current sorting order? Keep it no matter what
- If not (because selected sorting property is missing from the selected templates) then override the current sorting criteria

Since all templates have Title and Creation Date, that option Ismail always valid and doesn't get overriden.

As I mentioned during discussions, as is, priority sorting is almost 'dormant' and does not take over very often in the library. In entity view it's a different story.

**Comment by kjantin** [comment]
@RafaPolit now that you have done all this new work on priority sorting, is this issue still important?

**Comment by RafaPolit** [comment]
@kjantin it is true that the priority sorting has changed.

Still the uploads follow the same rules as the library: now priority sorting takes precedence and, if there has been a user-selected option, it will keep that as long as it is possible.

I think that this allows for a one-click change to have whatever sorting you want for each working session.  So I think that is OK.  If we want to auto-change the behavior on uploads, then this needs to be discussed further.

**Comment by txau** [comment]
I think this is already fixed by setting priority sorting to title.
