### ISSUE TITLE
If a referenced entity gets its template type changed, address the 'cascade' effect.

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazi#793]
If I change the type of an entity and it was used a 'thesaury' in some other document or entity, this should be addressed.

Options:
- Don't allow changing types of used entities
- Warn about loosing that connection or reference and cascade-delete the reference

**Comment by txau** [comment]
Not to be implemented in favor of another solution: #853

**Comment by txau** [comment]
Reopening for addressing the side effects:
- Remove the values from the metadata.
- Make sure the connections are also deleted.

**Comment by daneryl** [comment]
@txau @RafaPolit @konzz the connections are already being deleted, deleting the values its pretty difficult and probably with a bad performance, since this is  a temporal solution until everything its a connection i think its better to fix this on the client side and maybe do a data migration on the moment we change to #853.

**Comment by txau** [comment]
Ok. Mot fixing this for now.
