### ISSUE TITLE
Changing document type hangs system

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#796]
I had allocated a document type to a document last week, which now I realise was wrong. I had not published document yet. Now, trying to correct but it hangs. Kindly advice.
![change of document type hangs system](https://cloud.githubusercontent.com/assets/22650647/22720222/876deb70-edba-11e6-8e06-a0390bb74b00.png)

**Comment by HSips** [comment]
System still hanging on other documents. I guess dev team is working on updates or so? Will check in later in the day

**Comment by konzz** [comment]
@HSips We recently updated some changes that fix template creation, go to settings and edit your Document and Entities templates, in all the properties that have "Thesauri" to be selected, reselect (select a different one, and then the one you want) the option that you want, may look that the option was selected, but thats because we don't have a "not selected option" and the field shows the first option in the list, but doesn't mean that is actually selected. I'm closing the issue, if you can't solve the problem feel free to reopen it or contact me directly.

**Comment by HSips** [comment]
Hey thanks Alberto! Will do that and revert (on Friday or Sat) and revert
if I face difficulties.

---
Consultant
HURIDOCS, Nairobi

HURIDOCS Secretariat
Rue de Varembé 3
1202 Geneva, Switzerland
http://www.huridocs.org

Humphrey Sipalla http://ssrn.com/author=2593184
