### ISSUE TITLE
Options for date selection such as custom date format and start/end dates

### ISSUE THREAD

**Issue by HSips** [huridocs/uwazi#815]
1. When selecting a date, the system allows for only one option, to choose a day, month, year. However, some types of documents do not have such a specific date, like reports which mostly have a year of publication and sometimes month and year.
2. Also, had noticed this earlier when working on the humphrey instance, but didn't think too much of it. Many AU documents have a start and end date (indicating the dates of the Summit). Now I have been choosing the end date, but now wondering if possible to choose a period rather than a single date. This may be useful in other types of does as well, like reports.

**Comment by danicatalan** [comment]
We don't support custom dates right now, but it is a interesting feature that we need to study. I'm going to tag this issue as _maybe?_ because it's a complicated feature that we need to study and regrettably it will take time to implement because it have a lot of parts involved, like rendering the dates, sorting the cards and filter them.

**Comment by txau** [comment]
@HSips 

1. When we are tagging per year, the best option is to use a dictionary with the years instead of a date field. IMO we shouldn't provide support for custom date formats. They are complicated.

2. We could have a period field, but instead right is support by adding to date fields "Date start", "Date end". Filtering within those periods is totally possible with our current filters so that feature is somewhat supported.

I'm closing this issue.

**Comment by HSips** [comment]
@danicatalan @txau I hear you on the complexity and need to study it better. Trust your judgment on when to implement. But would be of some use if possible.
