### ISSUE TITLE
Determine the license for Uwazi code and governance model

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#840]

**Comment by danicatalan** [comment]
Should we determine license before 1.0?

**Comment by kjantin** [comment]
Casebox uses AGPLv3, not sure what OpenEvsys is.

**Comment by kjantin** [comment]
Resources:
* https://choosealicense.com/licenses/
* https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
* https://opensource.org/licenses
* https://tldrlegal.com/

**Comment by whyfrycek** [comment]
This is one where I go back and forth between the two of them. On the one hand, I really like the freedom that MIT enables; on the other, it is weird to think that this freedom could be used to restrict derivatives further down the line.

On balance, however, I think MIT is more suitable and, perhaps, open to innovation, which is why I would advocate for it.

**Comment by kjantin** [comment]
Decision: MIT license. 
Created #1375 to apply the license to the code.
