### ISSUE TITLE
In CEJIL votos separados are not connected to the documents anymore

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#852]
Before we had a connection to the document the voto separado was talking about.

![screen shot 2017-03-10 at 13 00 18](https://cloud.githubusercontent.com/assets/489831/23794669/8dccdc1c-0591-11e7-886c-9646cad6bcf5.png)
![screen shot 2017-03-10 at 13 00 12](https://cloud.githubusercontent.com/assets/489831/23794670/8dd413c4-0591-11e7-8e42-4cb504d6f2cf.png)

**Comment by daneryl** [comment]
this "voto separado" its actually duplicated [here](https://cejil.uwazi.io/es/document/vz1ib2c5q5wetntn61icc8fr) as "sentencia de la corte"
the actual one its not linked but the duplicated one with incorrect type it is. i found another one like [this](https://cejil.uwazi.io/es/document/xn5uvy0p0q4b364lq28rggb9), has two "votos separados" linked but they are of "Sentencia de la corte type".

**Comment by danicatalan** [comment]
Thanks @daneryl for the information.

Actions to perform:

- [ ] Review those three **I.V.** documents. Fix one of them with al information correctly fulfilled, delete the others.
- [ ] Review *Yarce** separated votes. Change the document type.
- [ ] Search more separated votes with type *Sentencia de la corte*.

I self assign this issue to manage the changes.

**Comment by txau** [comment]
@danicatalan this has been in backlog/sprint for too long. Please complete and close the issue.

**Comment by danicatalan** [comment]
## Case I.V.

These documents were duplicated:

- `pxnednmz12cb7gds1walfecdi`
- `6d130putuveh0sg0m6nmm9rudi`
- `vz1ib2c5q5wetntn61icc8fr`

I deleted the first two documents moving all the metadata to the third one, and create a connection between the Separated vote and the Sentence:

![image](https://user-images.githubusercontent.com/6364153/28968111-ba83fbea-791e-11e7-93ed-d1de0a947240.png)

**Comment by danicatalan** [comment]
## Yarce

The Separated Votes from this case are already fixed. It was just a change of document type:

![image](https://user-images.githubusercontent.com/6364153/28968195-2facdf86-791f-11e7-84ef-1078fe32b184.png)

**Comment by danicatalan** [comment]
## Sawhoyamaxa

There was a separated vote without the sentence title.

![image](https://user-images.githubusercontent.com/6364153/28968371-f1ab95d2-791f-11e7-8882-7f99df3ede39.png)

The name of that separated vote was the name of the sentence. 

![image](https://user-images.githubusercontent.com/6364153/28968442-41b15fa8-7920-11e7-8894-b73932d99bad.png)

Both are fixed now.

**Comment by danicatalan** [comment]
## Trabajadores de la Hacienda Brasil Verde.

The sentence was duplicated.

- `062bu1koowqcgj6lwa51xlxr`
- `gmxtogck77fm39moud7bke29`

I deleted the first one because it was uncompleted (no ToC and no connections to their separated votes).

![image](https://user-images.githubusercontent.com/6364153/28968563-d71554c8-7920-11e7-9407-8e365bc0ac11.png)

Anyway those separated votes had wrong document type. I changed the type and checked they are now properly connected with their sentence.

![image](https://user-images.githubusercontent.com/6364153/28968614-273f6ace-7921-11e7-81d2-78d6609ed87b.png)

![image](https://user-images.githubusercontent.com/6364153/28968891-791a2e78-7922-11e7-9eb5-b2081db995dc.png)

**Comment by danicatalan** [comment]
I can't find any other anomalies on Separated votes, so I'm closing this issue.
