### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#86]

**Comment by danicatalan** [comment]
It would be great if we have it inside the header, like a dropdown or something similar, but I think the best place right now is to put it inside the admin page, because we just have one user per system. Maybe we can develop this in a further story with a more complex menu - when we develop more settings for the users.

**Comment by danicatalan** [comment]
Updated here: https://github.com/huridocs/uwazi-assets/blob/master/12_admin_page/12_admin_page.mov
