### ISSUE TITLE
Remove Uploads as independent section

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazi#862]
The current Uploads section should be the same components as in library just with a "hidden flag" to show unpublished / private documents.

**Comment by daneryl** [comment]
Agree, it needs the same functionality to be able to search when there is a lot uploaded,
also uploads its per user so a user flag will be needed.
it should be relatively easy, but its more work than it seems, for instance cards shown in uploads its a totally different component than in library because of the upload/processing status.

**Comment by konzz** [comment]
We agreed upon this and will be done in #887
