### ISSUE TITLE
Allow user to import existing metadata via CSV

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#926]
If a user has a collection of documents, and they have already identified metadata/properties for these documents, can we develop a way for them to import this existing data from a CSV file?

This issue evolved from https://github.com/huridocs/uwazi/issues/843

**Comment by txau** [comment]
@kjantin #843 was a small issue describing a very precise functionality, small and well defined. This is a broader issue describing a very big functionality that may not happen any time soon. I think we should reopen the other one and keep this one more as a nice to have.

**Comment by bertver** [comment]
This afternoon I had a talk with a client who would benefit from the import of metadata. They have field offices in areas with low Internet connectivity which would enter data on Excel sheets which then would have to be regularly imported into a database. It is a rather big project, 30,000 USD - almost all of it honoraria for HURIDOCS. Otherwise the project is rather simple - development of one single format with some sub-formats (list three persons...) and permissions.  If this can be done with Uwazi it would be great. As it brings in money, could we give it a higher priority?

**Comment by danicatalan** [comment]
@bertver Do they want to upload new data on each import or also update current documents and entities?

**Comment by bertver** [comment]
it is for uploading new data

**Comment by RafaPolit** [comment]
Solved in #2340 and #2347.  Further improvements being discussed in #2310
