### ISSUE TITLE
Define user roles and permissions

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#953]
Define what user roles are most needed by users, and identify permissions for each.

**Comment by kjantin** [comment]
Approach 1:

*User* will be able to:
- View all the documents, entities, properties, connections, etc in Uwazi (but cannot edit, create, or delete anything)
- User the search and filter functionalities

*Editor* will be able to:
- Do all the things that a *User* can do
- Upload documents and create entities
- Organize the collection (as defined in the [user guide](https://github.com/huridocs/uwazi/wiki))

*Administrator* will be able to:
- Do all the things that an *Editor* can do
- Manage settings (as defined in the [user guide](https://github.com/huridocs/uwazi/wiki))
- Configure the information architecture (as defined in the [user guide](https://github.com/huridocs/uwazi/wiki))
- Configure filters

**Comment by danicatalan** [comment]
@kjantin do you have some request from Japiqay? I would like to know more about their needs. Also, we need to think about other projects and how we can fit this story to all of them.

Regardless the specific users and permissions, this first approach seems reasonable to me and straightforward to develop. The keys:

- Fixed user roles: admins will be able to create new users (with email/password) and assign their role, but this roles will be fixed with a predefined set of permissions. We will support custom roles in the future.
- We won't create the role "User", because they don't need to login into the system. We need to focus on the experience for content curators and creators, because they will be our core users.
