### ISSUE TITLE
How to manage documents that will be regularly updated?

### ISSUE THREAD

**Issue by kjantin** [huridocs/uwazi#980]
https://pretoria.uwazi.io/ is a collection of legal commentaries on African Court of Human and Peoples Rights decisions. Each commentary is a document that will have properties, references, connections, etc. Here is an example: https://pretoria.uwazi.io/en/document/40c5tlpq3811p46a36zagx2yb9
These commentaries will be updated over time. How can the administrators/editors update these commentaries without losing all of the metadata they have already assigned to the document?

**Comment by kjantin** [comment]
**Current workflow:**
Administrator will need to delete the PDF along with the references, upload the new PDF and recreate the references and properties. 

**Ideas for future solutions:**
* When replacing the document, can we offer a "Replace document and keep references" button? And/or allow the user to redirect the references that were saved from the previous document. 
* We want to add the ability to annotate documents (comments). Maybe these "comments" could all be rendered as the "Commentary" section. 
* The "Commentary" entity is a markdown file instead of a PDF so that it is closer to living content that can be updated. User can create references/connections the same way as PDFs.

**Comment by txau** [comment]
I think the good solution goes along the line of your 3rd point:

"The "Commentary" entity is a markdown file instead of a PDF so that it is closer to living content that can be updated. User can create references/connections the same way as PDFs."

**Comment by RafaPolit** [comment]
Point # 1 is not really viable, as there is no way to ensure that the PDF structure is kept in its entirety, so text references inside the document and from other documents to the new PDF can't be kept without a major effort, probably not worth it.

Recreating the TEXT references (properties and references are not lost with the new 'replace PDF' functionality that was implemented after the original statement was written) could be cumbersome.

Point two is feasible (and a wanted functionality IMHO), but not for this scenario.

Point three is interesting, it would work, but you would not be able to 'reference' or 'annotate' those comments.

Other alternatives:
- Add the commentaries as attachments (same problems as point 3, but you keep the PDF format)
- Create an Document Type called 'Comment' which could be referenced within the main document.  Once we finish the relationships, they could show up nicely inside the document (but this is functionality not yet ready)

**Comment by danicatalan** [comment]
I like the Markdown idea, here's two approaches to solve this:

- We extend the idea to support non-PDF documents. 

  Instead of upload and render a PDF.js transformation, users will be able to write text in Markdown and render the formatted text in the document viewer. This text should be selectable so users could perform typical actions from PDFs (references, TOC). Also great for accessibility, responsive and screen readers.

  I'm concerned about the documents edition, just had a conversation with @txau about the nature of documents and their immutability.

- We add references/connections support on Markdown fields.

  This is interesting because we add a great feature to entities and pages, we just need to find a way to create those connections.

  In this specific case, _Commentaries_ can be entities with just a Markdown field, and if this markdown has references, those documents are shown on the sidepanel as connections.

**Comment by txau** [comment]
@RafaPolit "Point three is interesting, it would work, but you would not be able to 'reference' or 'annotate' those comments." 

Why not? Also from your subsequent comments I'm not sure you are understanding what they need.

**Comment by txau** [comment]
@danicatalan 

"We extend the idea to support non-PDF documents.".  No please, we just can't afford to build google drive.

"We add references/connections support on Markdown fields." Exactly, we can reference entities or documents from mark down fields. How to reference them is not a problem, we already have that developed. How to keep those references consistent while editing the markdown text is the challenge. Nevertheless, it is easy to solve if our users are ok with the idea of working with markdown.
